-- Hamburger restaurant menu seed for Replau.
-- Safe to run multiple times: api.bulk_upsert_productos upserts by cdg_prod
-- and refreshes packs/prices. Run after replau_product_import_tool/add_bulk_product_import.sql.

SELECT api.bulk_upsert_productos($json$
[
  {
    "cdg_prod": "BURGER_SINGLE",
    "nombre": "HAMBURGUESA SIMPLE",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 12.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BURGER_SINGLE_CHEESE",
    "nombre": "HAMBURGUESA SIMPLE CON QUESO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 14.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BURGER_SINGLE_BACON",
    "nombre": "HAMBURGUESA SIMPLE CON TOCINO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 16.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BURGER_SINGLE_BACON_CHEESE",
    "nombre": "HAMBURGUESA SIMPLE CON TOCINO Y QUESO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 18.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BURGER_DOUBLE",
    "nombre": "HAMBURGUESA DOBLE",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 20.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BURGER_DOUBLE_CHEESE",
    "nombre": "HAMBURGUESA DOBLE CON QUESO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 23.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BURGER_DOUBLE_BACON",
    "nombre": "HAMBURGUESA DOBLE CON TOCINO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 25.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BURGER_DOUBLE_BACON_CHEESE",
    "nombre": "HAMBURGUESA DOBLE CON TOCINO Y QUESO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 27.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BURGER_TRIPLE",
    "nombre": "HAMBURGUESA TRIPLE",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 28.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BURGER_TRIPLE_CHEESE",
    "nombre": "HAMBURGUESA TRIPLE CON QUESO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 32.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BURGER_TRIPLE_BACON",
    "nombre": "HAMBURGUESA TRIPLE CON TOCINO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 34.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BURGER_TRIPLE_BACON_CHEESE",
    "nombre": "HAMBURGUESA TRIPLE CON TOCINO Y QUESO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 36.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "FRIES_SMALL",
    "nombre": "PAPAS FRITAS PEQUENAS",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 7.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "FRIES_LARGE",
    "nombre": "PAPAS FRITAS GRANDES",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 10.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "ONION_RINGS_SMALL",
    "nombre": "AROS DE CEBOLLA PEQUENOS",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 8.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "ONION_RINGS_LARGE",
    "nombre": "AROS DE CEBOLLA GRANDES",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 12.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "CHICKEN_STRIPS_3",
    "nombre": "TIRAS DE POLLO X3",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 13.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "CHICKEN_STRIPS_5",
    "nombre": "TIRAS DE POLLO X5",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 18.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "CHICKEN_BURGER",
    "nombre": "HAMBURGUESA DE POLLO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 16.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "CHICKEN_BURGER_CHEESE",
    "nombre": "HAMBURGUESA DE POLLO CON QUESO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 18.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "COMBO_SINGLE",
    "nombre": "COMBO HAMBURGUESA SIMPLE CON PAPAS",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 18.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "COMBO_DOUBLE",
    "nombre": "COMBO HAMBURGUESA DOBLE CON PAPAS",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 26.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "COMBO_TRIPLE",
    "nombre": "COMBO HAMBURGUESA TRIPLE CON PAPAS",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 34.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "SODA_PERSONAL",
    "nombre": "GASEOSA PERSONAL",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 5.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "WATER_BOTTLE",
    "nombre": "AGUA EMBOTELLADA",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 4.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "CHEESE_EXTRA",
    "nombre": "EXTRA QUESO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 3.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "BACON_EXTRA",
    "nombre": "EXTRA TOCINO",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 4.0,
    "moneda": "PEN",
    "valid_from": "2026-04-29"
  },
  {
    "cdg_prod": "SAUCE_EXTRA",
    "nombre": "SALSA EXTRA",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 3.0,
    "moneda": "PEN",
    "valid_from": "2026-05-03"
  },
  {
    "cdg_prod": "WINGS_6",
    "nombre": "ALITAS FRITAS PICANTES X 6",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 14.0,
    "moneda": "PEN",
    "valid_from": "2026-05-03"
  },
  {
    "cdg_prod": "WINGS_12",
    "nombre": "ALITAS FRITAS PICANTES X 12",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 24.0,
    "moneda": "PEN",
    "valid_from": "2026-05-03"
  },
  {
    "cdg_prod": "WINGS_24",
    "nombre": "ALITAS FRITAS PICANTES X 24",
    "tipo_producto": "TERMINADO",
    "unidad_medida": "UND",
    "pack_default": "UNIDAD",
    "stock_minimo": 0.0,
    "controla_lote": false,
    "controla_vencimiento": false,
    "active": true,
    "pack_name": "UNIDAD",
    "pack_factor": 1.0,
    "pack_is_default": true,
    "precio_unidad": "UNIDAD",
    "precio": 42.0,
    "moneda": "PEN",
    "valid_from": "2026-05-03"
  }
]
$json$::jsonb);
