BEGIN;

CREATE TABLE IF NOT EXISTS api.producto_combo_componentes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combo_producto_id integer NOT NULL REFERENCES api.productos(id) ON DELETE CASCADE,
    componente_producto_id integer NOT NULL REFERENCES api.productos(id) ON DELETE RESTRICT,
    cantidad numeric(14,3) NOT NULL DEFAULT 1,
    sort_order integer NOT NULL DEFAULT 0,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT producto_combo_componentes_qty_check CHECK (cantidad > 0),
    CONSTRAINT producto_combo_componentes_unique UNIQUE (combo_producto_id, componente_producto_id)
);

DROP TRIGGER IF EXISTS set_updated_at_producto_combo_componentes ON api.producto_combo_componentes;
CREATE TRIGGER set_updated_at_producto_combo_componentes
BEFORE UPDATE ON api.producto_combo_componentes
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();

CREATE OR REPLACE VIEW api.v_producto_combo_componentes AS
SELECT
    c.id,
    combo.id AS combo_producto_id,
    combo.cdg_prod AS combo_cdg_prod,
    combo.nombre AS combo_nombre,
    comp.id AS componente_producto_id,
    comp.cdg_prod AS componente_cdg_prod,
    comp.nombre AS componente_nombre,
    c.cantidad,
    c.sort_order,
    c.active
FROM api.producto_combo_componentes c
JOIN api.productos combo ON combo.id = c.combo_producto_id
JOIN api.productos comp ON comp.id = c.componente_producto_id;

DELETE FROM api.producto_combo_componentes
WHERE combo_producto_id IN (
    SELECT id FROM api.productos WHERE cdg_prod IN ('COMBO_CLASSIC', 'COMBO_DOUBLE_CHEESE')
);

INSERT INTO api.producto_combo_componentes (combo_producto_id, componente_producto_id, cantidad, sort_order)
SELECT combo.id, comp.id, x.cantidad, x.sort_order
FROM (
    VALUES
        ('COMBO_CLASSIC', 'BURGER_SIMPLE', 1::numeric, 1),
        ('COMBO_CLASSIC', 'FRIES_SMALL', 1::numeric, 2),
        ('COMBO_CLASSIC', 'COCA_COLA_SMALL', 1::numeric, 3),
        ('COMBO_DOUBLE_CHEESE', 'BURGER_DOUBLE_CHEESE', 1::numeric, 1),
        ('COMBO_DOUBLE_CHEESE', 'FRIES_LARGE', 1::numeric, 2),
        ('COMBO_DOUBLE_CHEESE', 'COCA_COLA_LARGE', 1::numeric, 3)
) AS x(combo_cdg_prod, component_cdg_prod, cantidad, sort_order)
JOIN api.productos combo ON combo.cdg_prod = x.combo_cdg_prod
JOIN api.productos comp ON comp.cdg_prod = x.component_cdg_prod
ON CONFLICT (combo_producto_id, componente_producto_id)
DO UPDATE SET
    cantidad = EXCLUDED.cantidad,
    sort_order = EXCLUDED.sort_order,
    active = true,
    updated_at = now();

GRANT SELECT, INSERT, UPDATE, DELETE ON api.producto_combo_componentes TO web_anon;
GRANT SELECT ON api.v_producto_combo_componentes TO web_anon;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE api.producto_combo_componentes_id_seq TO web_anon;

NOTIFY pgrst, 'reload schema';

COMMIT;
