BEGIN;

CREATE TABLE IF NOT EXISTS api.ingredientes_costeo (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre text NOT NULL UNIQUE,
    proveedor_id integer REFERENCES api.proveedores(id) ON DELETE SET NULL,
    costo_kg numeric(14,4) NOT NULL,
    moneda text NOT NULL DEFAULT 'PEN',
    stk_in numeric(14,3) NOT NULL DEFAULT 0,
    stk_out numeric(14,3) NOT NULL DEFAULT 0,
    stk_act numeric(14,3) GENERATED ALWAYS AS (stk_in - stk_out) STORED,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ingredientes_costeo_costo_check CHECK (costo_kg > 0),
    CONSTRAINT ingredientes_costeo_stock_check CHECK (stk_in >= 0 AND stk_out >= 0)
);

CREATE TRIGGER set_updated_at_ingredientes_costeo
BEFORE UPDATE ON api.ingredientes_costeo
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();

CREATE TABLE IF NOT EXISTS api.recetas_costeo (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id integer REFERENCES api.productos(id) ON DELETE SET NULL,
    nombre text NOT NULL,
    rendimiento_unidades numeric(14,3) NOT NULL DEFAULT 1,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT recetas_costeo_rendimiento_check CHECK (rendimiento_unidades > 0)
);

CREATE TRIGGER set_updated_at_recetas_costeo
BEFORE UPDATE ON api.recetas_costeo
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();

CREATE TABLE IF NOT EXISTS api.receta_ingredientes_costeo (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receta_id integer NOT NULL REFERENCES api.recetas_costeo(id) ON DELETE CASCADE,
    ingrediente_id integer NOT NULL REFERENCES api.ingredientes_costeo(id) ON DELETE RESTRICT,
    cantidad_g numeric(14,3) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT receta_ingredientes_costeo_qty_check CHECK (cantidad_g > 0),
    CONSTRAINT receta_ingredientes_costeo_unique UNIQUE (receta_id, ingrediente_id)
);

CREATE TRIGGER set_updated_at_receta_ingredientes_costeo
BEFORE UPDATE ON api.receta_ingredientes_costeo
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();

CREATE OR REPLACE VIEW api.v_receta_costos AS
SELECT
    r.id AS receta_id,
    r.producto_id,
    p.cdg_prod,
    COALESCE(p.nombre, r.nombre) AS producto_nombre,
    r.nombre AS receta_nombre,
    r.rendimiento_unidades,
    COALESCE(SUM((ri.cantidad_g / 1000.0) * i.costo_kg), 0)::numeric(14,4) AS costo_total,
    (COALESCE(SUM((ri.cantidad_g / 1000.0) * i.costo_kg), 0) / r.rendimiento_unidades)::numeric(14,4) AS costo_por_unidad,
    COUNT(ri.id)::integer AS ingredientes_count
FROM api.recetas_costeo r
LEFT JOIN api.productos p ON p.id = r.producto_id
LEFT JOIN api.receta_ingredientes_costeo ri ON ri.receta_id = r.id
LEFT JOIN api.ingredientes_costeo i ON i.id = ri.ingrediente_id
GROUP BY r.id, r.producto_id, p.cdg_prod, p.nombre, r.nombre, r.rendimiento_unidades;

CREATE OR REPLACE VIEW api.v_receta_ingredientes_costeo AS
SELECT
    ri.id,
    ri.receta_id,
    r.nombre AS receta_nombre,
    ri.ingrediente_id,
    i.nombre AS ingrediente_nombre,
    i.proveedor_id,
    pr.nombre AS proveedor_nombre,
    ri.cantidad_g,
    i.costo_kg,
    ((ri.cantidad_g / 1000.0) * i.costo_kg)::numeric(14,4) AS costo_linea,
    i.stk_in,
    i.stk_out,
    i.stk_act
FROM api.receta_ingredientes_costeo ri
JOIN api.recetas_costeo r ON r.id = ri.receta_id
JOIN api.ingredientes_costeo i ON i.id = ri.ingrediente_id
LEFT JOIN api.proveedores pr ON pr.id = i.proveedor_id;

GRANT SELECT, INSERT, UPDATE, DELETE ON api.ingredientes_costeo TO web_anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON api.recetas_costeo TO web_anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON api.receta_ingredientes_costeo TO web_anon;
GRANT SELECT ON api.v_receta_costos TO web_anon;
GRANT SELECT ON api.v_receta_ingredientes_costeo TO web_anon;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE api.ingredientes_costeo_id_seq TO web_anon;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE api.recetas_costeo_id_seq TO web_anon;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE api.receta_ingredientes_costeo_id_seq TO web_anon;

NOTIFY pgrst, 'reload schema';

COMMIT;
