BEGIN;

CREATE SCHEMA IF NOT EXISTS api;

-- Phase 1: consolidated driver payouts.
-- Completed delivery assignments remain the source of truth; payout items only
-- group those payable route rows into one settlement/payment batch.

CREATE TABLE IF NOT EXISTS api.delivery_payout_batches (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repartidor_id integer NOT NULL REFERENCES api.repartidores(id) ON DELETE RESTRICT,
    status text NOT NULL DEFAULT 'OPEN',
    route_count integer NOT NULL DEFAULT 0,
    total_amount numeric(14,2) NOT NULL DEFAULT 0,
    payment_method text,
    payment_reference text,
    notes text,
    period_start timestamptz,
    period_end timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    paid_at timestamptz,
    cancelled_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT delivery_payout_batches_status_check
    CHECK (status IN ('OPEN','PAID','CANCELLED'))
);

CREATE TABLE IF NOT EXISTS api.delivery_payout_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id integer NOT NULL REFERENCES api.delivery_payout_batches(id) ON DELETE CASCADE,
    assignment_id integer NOT NULL REFERENCES api.delivery_asignaciones(id) ON DELETE RESTRICT,
    amount numeric(14,2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT delivery_payout_items_assignment_unique UNIQUE (assignment_id)
);

CREATE INDEX IF NOT EXISTS idx_delivery_payout_batches_repartidor_status
ON api.delivery_payout_batches(repartidor_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_delivery_payout_items_batch
ON api.delivery_payout_items(batch_id);

CREATE OR REPLACE VIEW api.v_delivery_payout_unpaid AS
SELECT
    a.id AS assignment_id,
    a.pedido_id,
    p.pedido_num,
    p.estado AS pedido_estado,
    a.repartidor_id,
    r.codigo AS repartidor_codigo,
    r.nombre AS repartidor_nombre,
    r.whatsapp_number AS repartidor_whatsapp,
    a.fee AS amount,
    a.completed_at,
    a.assigned_at,
    a.created_at,
    a.notes
FROM api.delivery_asignaciones a
JOIN api.pedidos p ON p.id = a.pedido_id
JOIN api.repartidores r ON r.id = a.repartidor_id
LEFT JOIN api.delivery_payout_items i ON i.assignment_id = a.id
WHERE a.status = 'COMPLETED'
  AND a.repartidor_id IS NOT NULL
  AND i.id IS NULL;

CREATE OR REPLACE VIEW api.v_repartidor_account_summary AS
SELECT
    r.id AS repartidor_id,
    r.codigo,
    r.nombre,
    r.whatsapp_number,
    r.activo,
    COUNT(u.assignment_id)::integer AS unpaid_route_count,
    COALESCE(SUM(u.amount), 0)::numeric(14,2) AS unpaid_total,
    COALESCE((
        SELECT SUM(b.total_amount)
        FROM api.delivery_payout_batches b
        WHERE b.repartidor_id = r.id
          AND b.status = 'PAID'
    ), 0)::numeric(14,2) AS paid_total,
    (
        SELECT b.paid_at
        FROM api.delivery_payout_batches b
        WHERE b.repartidor_id = r.id
          AND b.status = 'PAID'
        ORDER BY b.paid_at DESC NULLS LAST, b.created_at DESC
        LIMIT 1
    ) AS last_paid_at,
    (
        SELECT b.total_amount
        FROM api.delivery_payout_batches b
        WHERE b.repartidor_id = r.id
          AND b.status = 'PAID'
        ORDER BY b.paid_at DESC NULLS LAST, b.created_at DESC
        LIMIT 1
    ) AS last_paid_amount,
    (
        SELECT COUNT(*)
        FROM api.delivery_asignaciones a
        WHERE a.repartidor_id = r.id
          AND a.status IN ('OFFERED','ACCEPTED','ASSIGNED')
    )::integer AS active_route_count,
    MIN(u.completed_at) AS oldest_unpaid_completed_at,
    MAX(u.completed_at) AS newest_unpaid_completed_at
FROM api.repartidores r
LEFT JOIN api.v_delivery_payout_unpaid u ON u.repartidor_id = r.id
GROUP BY r.id, r.codigo, r.nombre, r.whatsapp_number, r.activo;

CREATE OR REPLACE VIEW api.v_delivery_payout_batches AS
SELECT
    b.id,
    b.repartidor_id,
    r.codigo AS repartidor_codigo,
    r.nombre AS repartidor_nombre,
    r.whatsapp_number AS repartidor_whatsapp,
    b.status,
    b.route_count,
    b.total_amount,
    b.payment_method,
    b.payment_reference,
    b.notes,
    b.period_start,
    b.period_end,
    b.created_at,
    b.paid_at,
    b.cancelled_at,
    b.updated_at
FROM api.delivery_payout_batches b
JOIN api.repartidores r ON r.id = b.repartidor_id;

CREATE OR REPLACE FUNCTION api.crear_delivery_payout_repartidor(
    p_repartidor_id integer,
    p_notes text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
    v_batch_id integer;
    v_count integer;
    v_total numeric(14,2);
    v_period_start timestamptz;
    v_period_end timestamptz;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM api.repartidores WHERE id = p_repartidor_id) THEN
        RETURN jsonb_build_object('ok', false, 'error', 'Repartidor not found');
    END IF;

    WITH payable AS (
        SELECT *
        FROM api.v_delivery_payout_unpaid
        WHERE repartidor_id = p_repartidor_id
        ORDER BY completed_at ASC NULLS LAST, assignment_id ASC
    )
    SELECT
        COUNT(*)::integer,
        COALESCE(SUM(amount), 0)::numeric(14,2),
        MIN(completed_at),
        MAX(completed_at)
    INTO v_count, v_total, v_period_start, v_period_end
    FROM payable;

    IF COALESCE(v_count, 0) = 0 THEN
        RETURN jsonb_build_object('ok', false, 'error', 'No completed unpaid routes');
    END IF;

    INSERT INTO api.delivery_payout_batches(
        repartidor_id,
        status,
        route_count,
        total_amount,
        notes,
        period_start,
        period_end
    )
    VALUES (
        p_repartidor_id,
        'OPEN',
        v_count,
        v_total,
        NULLIF(trim(COALESCE(p_notes, '')), ''),
        v_period_start,
        v_period_end
    )
    RETURNING id INTO v_batch_id;

    INSERT INTO api.delivery_payout_items(batch_id, assignment_id, amount)
    SELECT v_batch_id, assignment_id, amount
    FROM api.v_delivery_payout_unpaid
    WHERE repartidor_id = p_repartidor_id
    ORDER BY completed_at ASC NULLS LAST, assignment_id ASC;

    RETURN jsonb_build_object(
        'ok', true,
        'batch_id', v_batch_id,
        'repartidor_id', p_repartidor_id,
        'route_count', v_count,
        'total_amount', v_total
    );
END;
$$;

CREATE OR REPLACE FUNCTION api.marcar_delivery_payout_pagado(
    p_batch_id integer,
    p_payment_method text DEFAULT NULL,
    p_payment_reference text DEFAULT NULL,
    p_notes text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
    v_batch record;
BEGIN
    SELECT * INTO v_batch
    FROM api.delivery_payout_batches
    WHERE id = p_batch_id
    FOR UPDATE;

    IF v_batch.id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'error', 'Payout batch not found');
    END IF;

    IF v_batch.status = 'CANCELLED' THEN
        RETURN jsonb_build_object('ok', false, 'error', 'Payout batch is cancelled');
    END IF;

    UPDATE api.delivery_payout_batches
    SET status = 'PAID',
        payment_method = NULLIF(trim(COALESCE(p_payment_method, '')), ''),
        payment_reference = NULLIF(trim(COALESCE(p_payment_reference, '')), ''),
        notes = NULLIF(trim(COALESCE(p_notes, notes, '')), ''),
        paid_at = COALESCE(paid_at, now()),
        updated_at = now()
    WHERE id = p_batch_id;

    RETURN jsonb_build_object('ok', true, 'batch_id', p_batch_id, 'status', 'PAID');
END;
$$;

GRANT SELECT ON
    api.delivery_payout_batches,
    api.delivery_payout_items,
    api.v_delivery_payout_unpaid,
    api.v_repartidor_account_summary,
    api.v_delivery_payout_batches
TO web_anon;

GRANT EXECUTE ON FUNCTION api.crear_delivery_payout_repartidor(integer, text) TO web_anon;
GRANT EXECUTE ON FUNCTION api.marcar_delivery_payout_pagado(integer, text, text, text) TO web_anon;

NOTIFY pgrst, 'reload schema';

COMMIT;
