BEGIN;

CREATE UNIQUE INDEX IF NOT EXISTS recetas_costeo_one_active_product
ON api.recetas_costeo(producto_id)
WHERE active AND producto_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS api.ingredient_consumption_batches(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 pedido_id integer NOT NULL REFERENCES api.pedidos(id) ON DELETE RESTRICT,
 picking_session_id bigint REFERENCES api.picking_sessions(id) ON DELETE RESTRICT,
 warehouse_id integer NOT NULL REFERENCES api.almacenes(id) ON DELETE RESTRICT,
 status text NOT NULL DEFAULT 'POSTING' CHECK(status IN('POSTING','POSTED')),
 actor text NOT NULL,
 order_line_count integer NOT NULL DEFAULT 0 CHECK(order_line_count>=0),
 recipe_line_count integer NOT NULL DEFAULT 0 CHECK(recipe_line_count>=0),
 skipped_line_count integer NOT NULL DEFAULT 0 CHECK(skipped_line_count>=0),
 movement_count integer NOT NULL DEFAULT 0 CHECK(movement_count>=0),
 total_quantity_kg numeric(14,3) NOT NULL DEFAULT 0 CHECK(total_quantity_kg>=0),
 details jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now(),
 posted_at timestamptz,
 CONSTRAINT ingredient_consumption_batch_order_unique UNIQUE(pedido_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ingredient_consumption_batch_picking_unique
ON api.ingredient_consumption_batches(picking_session_id)
WHERE picking_session_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS api.ingredient_consumption_lines(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 batch_id bigint NOT NULL REFERENCES api.ingredient_consumption_batches(id) ON DELETE RESTRICT,
 pedido_item_id integer NOT NULL REFERENCES api.pedido_items(id) ON DELETE RESTRICT,
 producto_id integer NOT NULL REFERENCES api.productos(id) ON DELETE RESTRICT,
 receta_id integer NOT NULL REFERENCES api.recetas_costeo(id) ON DELETE RESTRICT,
 ingredient_id integer NOT NULL REFERENCES api.ingredientes_costeo(id) ON DELETE RESTRICT,
 output_quantity numeric(14,3) NOT NULL CHECK(output_quantity>0),
 quantity_kg numeric(14,3) NOT NULL CHECK(quantity_kg>0),
 unit_cost_snapshot numeric(14,4) NOT NULL CHECK(unit_cost_snapshot>=0),
 movement_id bigint NOT NULL UNIQUE REFERENCES api.ingredient_stock_movements(id) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ingredient_consumption_line_unique UNIQUE(batch_id,pedido_item_id,ingredient_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ingredient_order_consumption_movement_unique
ON api.ingredient_stock_movements(warehouse_id,ingredient_id,doc_id,doc_line_id)
WHERE movement_type='CONSUMPTION' AND doc_type='ORDER_RECIPE_CONSUMPTION';

CREATE OR REPLACE FUNCTION api.consume_order_ingredients(
 p_pedido_id integer,
 p_warehouse_id integer DEFAULT NULL,
 p_actor text DEFAULT 'scanner-picking',
 p_picking_session_id bigint DEFAULT NULL
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE
 order_row api.pedidos%ROWTYPE;
 existing_batch api.ingredient_consumption_batches%ROWTYPE;
 batch_id bigint;
 warehouse_id integer;
 order_lines integer:=0;
 recipe_lines integer:=0;
 skipped_lines integer:=0;
 movements integer:=0;
 total_kg numeric(14,3):=0;
 line record;
 quantity_kg numeric(14,3);
 movement jsonb;
 movement_id bigint;
 missing_products jsonb;
BEGIN
 IF length(trim(COALESCE(p_actor,'')))<2 THEN RAISE EXCEPTION 'Ingredient consumption actor is required';END IF;
 SELECT * INTO order_row FROM api.pedidos WHERE id=p_pedido_id FOR UPDATE;
 IF order_row.id IS NULL THEN RAISE EXCEPTION 'Order not found';END IF;
 IF order_row.estado NOT IN('CONFIRMADO','EN_PREPARACION','DESPACHADO') THEN
  RAISE EXCEPTION 'Order % cannot consume recipe ingredients from state %',p_pedido_id,order_row.estado;
 END IF;

 SELECT * INTO existing_batch FROM api.ingredient_consumption_batches WHERE pedido_id=p_pedido_id FOR UPDATE;
 IF existing_batch.id IS NOT NULL THEN
  RETURN jsonb_build_object(
   'ok',true,'already_posted',true,'batch_id',existing_batch.id,'pedido_id',p_pedido_id,
   'warehouse_id',existing_batch.warehouse_id,'order_line_count',existing_batch.order_line_count,
   'recipe_line_count',existing_batch.recipe_line_count,'skipped_line_count',existing_batch.skipped_line_count,
   'movement_count',existing_batch.movement_count,'total_quantity_kg',existing_batch.total_quantity_kg
  );
 END IF;

 warehouse_id:=COALESCE(p_warehouse_id,api.get_default_almacen_id());
 IF warehouse_id IS NULL OR NOT EXISTS(SELECT 1 FROM api.almacenes WHERE id=warehouse_id AND active) THEN
  RAISE EXCEPTION 'Active ingredient warehouse not found';
 END IF;
 IF p_picking_session_id IS NOT NULL AND NOT EXISTS(
  SELECT 1 FROM api.picking_sessions WHERE id=p_picking_session_id AND pedido_id=p_pedido_id
 ) THEN RAISE EXCEPTION 'Picking session does not belong to order';END IF;

 SELECT count(*) INTO order_lines FROM api.pedido_items WHERE pedido_id=p_pedido_id;
 SELECT count(*) INTO recipe_lines
 FROM api.pedido_items pi
 WHERE pi.pedido_id=p_pedido_id AND pi.producto_id IS NOT NULL
   AND EXISTS(
    SELECT 1 FROM api.recetas_costeo r
    WHERE r.producto_id=pi.producto_id AND r.active
      AND EXISTS(SELECT 1 FROM api.receta_ingredientes_costeo ri WHERE ri.receta_id=r.id)
      AND NOT EXISTS(
       SELECT 1 FROM api.receta_ingredientes_costeo ri
       JOIN api.ingredientes_costeo i ON i.id=ri.ingrediente_id
       WHERE ri.receta_id=r.id AND NOT i.active
      )
   );
 skipped_lines:=order_lines-recipe_lines;
 SELECT COALESCE(jsonb_agg(jsonb_build_object(
   'pedido_item_id',q.id,'producto_id',q.producto_id,'producto_texto',q.producto_texto
  ) ORDER BY q.id),'[]'::jsonb)
 INTO missing_products
 FROM (
  SELECT pi.id,pi.producto_id,pi.producto_texto
  FROM api.pedido_items pi
  WHERE pi.pedido_id=p_pedido_id AND NOT EXISTS(
   SELECT 1 FROM api.recetas_costeo r
   WHERE r.producto_id=pi.producto_id AND r.active
     AND EXISTS(SELECT 1 FROM api.receta_ingredientes_costeo ri WHERE ri.receta_id=r.id)
     AND NOT EXISTS(
      SELECT 1 FROM api.receta_ingredientes_costeo ri
      JOIN api.ingredientes_costeo i ON i.id=ri.ingrediente_id
      WHERE ri.receta_id=r.id AND NOT i.active
     )
  ) ORDER BY pi.id
 ) q;

 INSERT INTO api.ingredient_consumption_batches(
  pedido_id,picking_session_id,warehouse_id,status,actor,order_line_count,recipe_line_count,
  skipped_line_count,details
 ) VALUES(
  p_pedido_id,p_picking_session_id,warehouse_id,'POSTING',left(trim(p_actor),80),order_lines,
  recipe_lines,skipped_lines,jsonb_build_object('skipped_products',missing_products)
 ) RETURNING id INTO batch_id;

 FOR line IN
  SELECT pi.id pedido_item_id,pi.producto_id,pi.cantidad,pi.unidad,
   r.id receta_id,r.rendimiento_unidades,ri.ingrediente_id,ri.cantidad_g,i.costo_kg,i.moneda,
   round((pi.cantidad*api.get_producto_factor(pi.producto_id,pi.unidad))::numeric,3) output_quantity
  FROM api.pedido_items pi
  JOIN api.recetas_costeo r ON r.producto_id=pi.producto_id AND r.active
  JOIN api.receta_ingredientes_costeo ri ON ri.receta_id=r.id
  JOIN api.ingredientes_costeo i ON i.id=ri.ingrediente_id AND i.active
  WHERE pi.pedido_id=p_pedido_id
    AND NOT EXISTS(
     SELECT 1 FROM api.receta_ingredientes_costeo inactive_ri
     JOIN api.ingredientes_costeo inactive_i ON inactive_i.id=inactive_ri.ingrediente_id
     WHERE inactive_ri.receta_id=r.id AND NOT inactive_i.active
    )
  ORDER BY pi.id,ri.id
 LOOP
  quantity_kg:=round((line.output_quantity*line.cantidad_g/1000.0/line.rendimiento_unidades)::numeric,3);
  IF quantity_kg<=0 THEN
   RAISE EXCEPTION 'Recipe consumption for order item % is below ledger precision',line.pedido_item_id;
  END IF;
  movement:=api.post_ingredient_movement(
   line.ingrediente_id,warehouse_id,'CONSUMPTION',quantity_kg,p_actor,
   'Automatic recipe consumption for dispatched order','RECIPE_CONSUMPTION',line.costo_kg,
   line.moneda,NULL,NULL,NULL,'ORDER_RECIPE_CONSUMPTION',p_pedido_id,line.pedido_item_id,order_row.pedido_num
  );
  movement_id:=(movement->>'movement_id')::bigint;
  INSERT INTO api.ingredient_consumption_lines(
   batch_id,pedido_item_id,producto_id,receta_id,ingredient_id,output_quantity,
   quantity_kg,unit_cost_snapshot,movement_id
  ) VALUES(
   batch_id,line.pedido_item_id,line.producto_id,line.receta_id,line.ingrediente_id,
   line.output_quantity,quantity_kg,line.costo_kg,movement_id
  );
  movements:=movements+1;total_kg:=total_kg+quantity_kg;
 END LOOP;

 UPDATE api.ingredient_consumption_batches SET
  status='POSTED',movement_count=movements,total_quantity_kg=total_kg,posted_at=now(),
  details=details||jsonb_build_object('movement_count',movements,'total_quantity_kg',total_kg)
 WHERE id=batch_id;

 RETURN jsonb_build_object(
  'ok',true,'already_posted',false,'batch_id',batch_id,'pedido_id',p_pedido_id,
  'warehouse_id',warehouse_id,'order_line_count',order_lines,'recipe_line_count',recipe_lines,
  'skipped_line_count',skipped_lines,'movement_count',movements,'total_quantity_kg',total_kg,
  'skipped_products',missing_products
 );
END $$;

CREATE OR REPLACE FUNCTION api.post_ingredient_waste(p_ingredient_id integer,p_warehouse_id integer,p_quantity_kg numeric,p_actor text,p_reason_code text,p_reason text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE ingredient_cost numeric;ingredient_currency text;
BEGIN
 IF upper(trim(COALESCE(p_reason_code,''))) NOT IN('SPOILAGE','PREP_LOSS','DAMAGE','EXPIRED','QUALITY','OTHER') THEN RAISE EXCEPTION 'Invalid waste reason code';END IF;
 SELECT costo_kg,moneda INTO ingredient_cost,ingredient_currency FROM api.ingredientes_costeo WHERE id=p_ingredient_id AND active;
 IF ingredient_cost IS NULL THEN RAISE EXCEPTION 'Active ingredient not found';END IF;
 RETURN api.post_ingredient_movement(p_ingredient_id,p_warehouse_id,'WASTE',p_quantity_kg,p_actor,p_reason,upper(trim(p_reason_code)),ingredient_cost,ingredient_currency,NULL,NULL,NULL,'INGREDIENT_WASTE',NULL,NULL,NULL);
END $$;

CREATE OR REPLACE VIEW api.v_order_ingredient_consumption AS
SELECT b.id batch_id,b.pedido_id,p.pedido_num,b.picking_session_id,b.warehouse_id,a.codigo warehouse_code,
 b.status,b.actor,b.order_line_count,b.recipe_line_count,b.skipped_line_count,b.movement_count,
 b.total_quantity_kg,b.details,b.created_at,b.posted_at,
 COALESCE(sum(l.quantity_kg*l.unit_cost_snapshot),0)::numeric(14,4) theoretical_cost
FROM api.ingredient_consumption_batches b
JOIN api.pedidos p ON p.id=b.pedido_id
JOIN api.almacenes a ON a.id=b.warehouse_id
LEFT JOIN api.ingredient_consumption_lines l ON l.batch_id=b.id
GROUP BY b.id,p.pedido_num,a.codigo;

CREATE OR REPLACE VIEW api.v_ingredient_usage_variance_daily AS
SELECT timezone('America/Lima',m.movement_at)::date usage_date,m.warehouse_id,a.codigo warehouse_code,
 m.ingredient_id,i.sku,i.nombre ingredient_name,
 COALESCE(sum(m.quantity_kg) FILTER(WHERE m.movement_type='CONSUMPTION'),0)::numeric(14,3) theoretical_consumption_kg,
 COALESCE(sum(m.quantity_kg) FILTER(WHERE m.movement_type='WASTE'),0)::numeric(14,3) waste_variance_kg,
 COALESCE(sum(m.quantity_kg) FILTER(WHERE m.movement_type IN('CONSUMPTION','WASTE')),0)::numeric(14,3) actual_usage_kg,
 CASE WHEN COALESCE(sum(m.quantity_kg) FILTER(WHERE m.movement_type IN('CONSUMPTION','WASTE')),0)>0
  THEN round(100*COALESCE(sum(m.quantity_kg) FILTER(WHERE m.movement_type='WASTE'),0)
   /(sum(m.quantity_kg) FILTER(WHERE m.movement_type IN('CONSUMPTION','WASTE'))),2)
  ELSE 0 END::numeric(7,2) waste_rate_pct,
 COALESCE(sum(m.quantity_kg*COALESCE(m.unit_cost,i.costo_kg)) FILTER(WHERE m.movement_type='WASTE'),0)::numeric(14,4) waste_cost
FROM api.ingredient_stock_movements m
JOIN api.ingredientes_costeo i ON i.id=m.ingredient_id
JOIN api.almacenes a ON a.id=m.warehouse_id
WHERE m.movement_type IN('CONSUMPTION','WASTE')
GROUP BY timezone('America/Lima',m.movement_at)::date,m.warehouse_id,a.codigo,m.ingredient_id,i.sku,i.nombre,i.costo_kg;

CREATE OR REPLACE FUNCTION api.complete_scanner_picking(p_pedido_num text,p_token text,p_operator text DEFAULT 'picking')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE oid integer;sid bigint;consumed jsonb;ingredient_consumed jsonb;missing integer;warehouse_id integer;
BEGIN
 SELECT id INTO oid FROM api.pedidos WHERE pedido_num=trim(p_pedido_num) AND public_token=trim(p_token) AND public_token_expires_at>now() FOR UPDATE;
 IF oid IS NULL THEN RAISE EXCEPTION 'Invalid or expired order link';END IF;
 SELECT id INTO sid FROM api.picking_sessions WHERE pedido_id=oid AND status='ACTIVE' FOR UPDATE;
 IF sid IS NULL THEN RAISE EXCEPTION 'No active scanner picking session';END IF;
 SELECT count(*) INTO missing FROM api.picking_session_items WHERE session_id=sid AND scanned_quantity<>required_quantity;
 IF missing>0 THEN RAISE EXCEPTION 'Picking incomplete: % line(s) remain',missing;END IF;
 consumed:=api.consumir_reserva_pedido(oid);
 warehouse_id:=api.get_default_almacen_id();
 ingredient_consumed:=api.consume_order_ingredients(oid,warehouse_id,p_operator,sid);
 UPDATE api.picking_sessions SET status='COMPLETED',completed_at=now(),stock_consumed_at=now(),operator_name=left(COALESCE(p_operator,'picking'),80),updated_at=now() WHERE id=sid;
 INSERT INTO api.picking_scan_events(session_id,barcode,result,operator_name,detail) VALUES(sid,'[COMPLETE]','COMPLETED',left(COALESCE(p_operator,'picking'),80),jsonb_build_object('stock',consumed,'ingredients',ingredient_consumed));
 UPDATE api.pedidos SET estado='DESPACHADO',updated_at=now() WHERE id=oid;
 BEGIN PERFORM api.ofrecer_delivery_a_siguiente_repartidor(oid);EXCEPTION WHEN undefined_function OR undefined_table THEN NULL;END;
 RETURN jsonb_build_object('ok',true,'pedido_id',oid,'session_id',sid,'estado','DESPACHADO','stock',consumed,'ingredients',ingredient_consumed);
END $$;

GRANT SELECT ON api.ingredient_consumption_batches,api.ingredient_consumption_lines,api.v_order_ingredient_consumption,api.v_ingredient_usage_variance_daily TO web_anon;
GRANT USAGE,SELECT ON SEQUENCE api.ingredient_consumption_batches_id_seq,api.ingredient_consumption_lines_id_seq TO web_anon;
GRANT EXECUTE ON FUNCTION api.consume_order_ingredients(integer,integer,text,bigint),api.complete_scanner_picking(text,text,text) TO web_anon;

NOTIFY pgrst,'reload schema';
COMMIT;
