BEGIN;

CREATE TABLE IF NOT EXISTS api.inventory_count_sessions(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 reference text NOT NULL UNIQUE,
 warehouse_id integer NOT NULL REFERENCES api.almacenes(id) ON DELETE RESTRICT,
 count_scope text NOT NULL DEFAULT 'FULL' CHECK(count_scope IN('FULL','CYCLE')),
 status text NOT NULL DEFAULT 'ACTIVE' CHECK(status IN('ACTIVE','SUBMITTED','POSTED','VOIDED')),
 version integer NOT NULL DEFAULT 1,
 operator_name text NOT NULL,
 notes text,
 started_at timestamptz NOT NULL DEFAULT now(),
 submitted_at timestamptz,
 submitted_by text,
 submission_reason text,
 posted_at timestamptz,
 approved_by text,
 approval_reason text,
 voided_at timestamptz,
 voided_by text,
 void_reason text,
 updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS inventory_count_one_open_per_warehouse
 ON api.inventory_count_sessions(warehouse_id)
 WHERE status IN('ACTIVE','SUBMITTED');

CREATE TABLE IF NOT EXISTS api.inventory_count_lines(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 session_id bigint NOT NULL REFERENCES api.inventory_count_sessions(id) ON DELETE RESTRICT,
 product_id integer NOT NULL REFERENCES api.productos(id) ON DELETE RESTRICT,
 system_quantity numeric(14,3) NOT NULL DEFAULT 0,
 reserved_quantity numeric(14,3) NOT NULL DEFAULT 0,
 actual_quantity numeric(14,3),
 counted_at timestamptz,
 counted_by text,
 scan_count integer NOT NULL DEFAULT 0,
 movement_id integer REFERENCES api.movimientos_stock(id) ON DELETE RESTRICT,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT inventory_count_line_unique UNIQUE(session_id,product_id),
 CONSTRAINT inventory_count_values_check CHECK(system_quantity IS NOT NULL AND reserved_quantity>=0 AND (actual_quantity IS NULL OR actual_quantity>=0) AND scan_count>=0)
);

CREATE TABLE IF NOT EXISTS api.inventory_count_events(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 session_id bigint NOT NULL REFERENCES api.inventory_count_sessions(id) ON DELETE RESTRICT,
 event_type text NOT NULL,
 actor text NOT NULL,
 product_id integer REFERENCES api.productos(id) ON DELETE RESTRICT,
 details jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS inventory_count_lines_session_idx ON api.inventory_count_lines(session_id);
CREATE INDEX IF NOT EXISTS inventory_count_events_session_idx ON api.inventory_count_events(session_id,id);

CREATE OR REPLACE FUNCTION api.inventory_product_quantity(p_warehouse_id integer,p_product_id integer)
RETURNS numeric LANGUAGE sql STABLE SECURITY DEFINER SET search_path=api,public AS $$
 SELECT COALESCE(sum(stock_actual),0)::numeric FROM api.v_stock_actual
 WHERE almacen_id=p_warehouse_id AND producto_id=p_product_id
$$;

CREATE OR REPLACE FUNCTION api.inventory_product_reserved(p_warehouse_id integer,p_product_id integer)
RETURNS numeric LANGUAGE sql STABLE SECURITY DEFINER SET search_path=api,public AS $$
 SELECT COALESCE(sum(stock_reservado),0)::numeric FROM api.v_stock_reservado_productos
 WHERE almacen_id=p_warehouse_id AND producto_id=p_product_id
$$;

CREATE OR REPLACE FUNCTION api.create_inventory_count(p_warehouse_id integer,p_scope text,p_operator text,p_notes text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE sid bigint; ref text; scope_value text:=upper(trim(COALESCE(p_scope,'FULL'))); line_count integer:=0;
BEGIN
 IF NOT EXISTS(SELECT 1 FROM api.almacenes WHERE id=p_warehouse_id AND active) THEN RAISE EXCEPTION 'Active warehouse not found';END IF;
 IF scope_value NOT IN('FULL','CYCLE') THEN RAISE EXCEPTION 'Count scope must be FULL or CYCLE';END IF;
 IF length(trim(COALESCE(p_operator,'')))<2 THEN RAISE EXCEPTION 'Operator is required';END IF;
 ref:='COUNT-'||to_char(clock_timestamp(),'YYYYMMDD-HH24MISS-MS');
 INSERT INTO api.inventory_count_sessions(reference,warehouse_id,count_scope,operator_name,notes)
 VALUES(ref,p_warehouse_id,scope_value,left(trim(p_operator),80),NULLIF(trim(p_notes),'')) RETURNING id INTO sid;
 IF scope_value='FULL' THEN
  INSERT INTO api.inventory_count_lines(session_id,product_id,system_quantity,reserved_quantity)
  SELECT sid,p.id,api.inventory_product_quantity(p_warehouse_id,p.id),api.inventory_product_reserved(p_warehouse_id,p.id)
  FROM api.productos p WHERE p.active ORDER BY p.id;
  GET DIAGNOSTICS line_count=ROW_COUNT;
 END IF;
 INSERT INTO api.inventory_count_events(session_id,event_type,actor,details)
 VALUES(sid,'CREATED',left(trim(p_operator),80),jsonb_build_object('scope',scope_value,'line_count',line_count));
 RETURN jsonb_build_object('ok',true,'session_id',sid,'reference',ref,'scope',scope_value,'line_count',line_count,'version',1);
EXCEPTION WHEN unique_violation THEN
 RAISE EXCEPTION 'This warehouse already has an active or submitted count';
END $$;

CREATE OR REPLACE FUNCTION api.scan_inventory_count(p_session_id bigint,p_barcode text,p_packages numeric DEFAULT 1,p_operator text DEFAULT 'inventory')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE sess api.inventory_count_sessions%ROWTYPE; bc api.product_barcodes%ROWTYPE; line api.inventory_count_lines%ROWTYPE; clean text:=trim(COALESCE(p_barcode,'')); increment_qty numeric;
BEGIN
 IF clean='' OR p_packages<=0 OR p_packages>10000 THEN RAISE EXCEPTION 'Invalid count scan';END IF;
 SELECT * INTO sess FROM api.inventory_count_sessions WHERE id=p_session_id FOR UPDATE;
 IF sess.id IS NULL THEN RAISE EXCEPTION 'Inventory count not found';END IF;
 IF sess.status<>'ACTIVE' THEN RAISE EXCEPTION 'Inventory count is %',sess.status;END IF;
 SELECT * INTO bc FROM api.product_barcodes WHERE barcode=clean AND active;
 IF bc.id IS NULL THEN RAISE EXCEPTION 'Unknown or inactive barcode';END IF;
 increment_qty:=round((p_packages*bc.unit_factor)::numeric,3);
 INSERT INTO api.inventory_count_lines(session_id,product_id,system_quantity,reserved_quantity,actual_quantity,counted_at,counted_by,scan_count)
 VALUES(sess.id,bc.producto_id,api.inventory_product_quantity(sess.warehouse_id,bc.producto_id),api.inventory_product_reserved(sess.warehouse_id,bc.producto_id),increment_qty,now(),left(COALESCE(p_operator,'inventory'),80),1)
 ON CONFLICT(session_id,product_id) DO UPDATE SET actual_quantity=COALESCE(api.inventory_count_lines.actual_quantity,0)+EXCLUDED.actual_quantity,counted_at=now(),counted_by=EXCLUDED.counted_by,scan_count=api.inventory_count_lines.scan_count+1,updated_at=now()
 RETURNING * INTO line;
 INSERT INTO api.inventory_count_events(session_id,event_type,actor,product_id,details)
 VALUES(sess.id,'SCANNED',left(COALESCE(p_operator,'inventory'),80),bc.producto_id,jsonb_build_object('barcode',clean,'packages',p_packages,'factor',bc.unit_factor,'increment',increment_qty,'actual_quantity',line.actual_quantity));
 RETURN jsonb_build_object('ok',true,'line_id',line.id,'product_id',line.product_id,'actual_quantity',line.actual_quantity,'system_quantity',line.system_quantity,'variance',line.actual_quantity-line.system_quantity);
END $$;

CREATE OR REPLACE FUNCTION api.set_inventory_count_quantity(p_session_id bigint,p_product_id integer,p_actual_quantity numeric,p_operator text DEFAULT 'inventory')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE sess api.inventory_count_sessions%ROWTYPE; line api.inventory_count_lines%ROWTYPE; previous numeric;
BEGIN
 IF p_actual_quantity<0 THEN RAISE EXCEPTION 'Physical quantity cannot be negative';END IF;
 SELECT * INTO sess FROM api.inventory_count_sessions WHERE id=p_session_id FOR UPDATE;
 IF sess.id IS NULL THEN RAISE EXCEPTION 'Inventory count not found';END IF;
 IF sess.status<>'ACTIVE' THEN RAISE EXCEPTION 'Inventory count is %',sess.status;END IF;
 IF NOT EXISTS(SELECT 1 FROM api.productos WHERE id=p_product_id AND active) THEN RAISE EXCEPTION 'Active product not found';END IF;
 SELECT actual_quantity INTO previous FROM api.inventory_count_lines WHERE session_id=sess.id AND product_id=p_product_id;
 INSERT INTO api.inventory_count_lines(session_id,product_id,system_quantity,reserved_quantity,actual_quantity,counted_at,counted_by)
 VALUES(sess.id,p_product_id,api.inventory_product_quantity(sess.warehouse_id,p_product_id),api.inventory_product_reserved(sess.warehouse_id,p_product_id),round(p_actual_quantity,3),now(),left(COALESCE(p_operator,'inventory'),80))
 ON CONFLICT(session_id,product_id) DO UPDATE SET actual_quantity=EXCLUDED.actual_quantity,counted_at=now(),counted_by=EXCLUDED.counted_by,updated_at=now()
 RETURNING * INTO line;
 INSERT INTO api.inventory_count_events(session_id,event_type,actor,product_id,details)
 VALUES(sess.id,'QUANTITY_SET',left(COALESCE(p_operator,'inventory'),80),p_product_id,jsonb_build_object('previous',previous,'actual_quantity',line.actual_quantity));
 RETURN jsonb_build_object('ok',true,'line_id',line.id,'actual_quantity',line.actual_quantity,'system_quantity',line.system_quantity,'variance',line.actual_quantity-line.system_quantity);
END $$;

CREATE OR REPLACE FUNCTION api.submit_inventory_count(p_session_id bigint,p_operator text,p_reason text,p_expected_version integer)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE sess api.inventory_count_sessions%ROWTYPE; missing integer; counted integer;
BEGIN
 SELECT * INTO sess FROM api.inventory_count_sessions WHERE id=p_session_id FOR UPDATE;
 IF sess.id IS NULL THEN RAISE EXCEPTION 'Inventory count not found';END IF;
 IF sess.status<>'ACTIVE' THEN RAISE EXCEPTION 'Inventory count is %',sess.status;END IF;
 IF sess.version<>p_expected_version THEN RAISE EXCEPTION 'Stale inventory count version';END IF;
 IF length(trim(COALESCE(p_reason,'')))<5 THEN RAISE EXCEPTION 'Submission reason must have at least 5 characters';END IF;
 SELECT count(*) FILTER(WHERE actual_quantity IS NULL),count(*) FILTER(WHERE actual_quantity IS NOT NULL) INTO missing,counted FROM api.inventory_count_lines WHERE session_id=sess.id;
 IF sess.count_scope='FULL' AND missing>0 THEN RAISE EXCEPTION 'Full count has % uncounted product(s)',missing;END IF;
 IF counted=0 THEN RAISE EXCEPTION 'Count has no counted products';END IF;
 UPDATE api.inventory_count_sessions SET status='SUBMITTED',version=version+1,submitted_at=now(),submitted_by=left(trim(p_operator),80),submission_reason=left(trim(p_reason),500),updated_at=now() WHERE id=sess.id;
 INSERT INTO api.inventory_count_events(session_id,event_type,actor,details) VALUES(sess.id,'SUBMITTED',left(trim(p_operator),80),jsonb_build_object('reason',p_reason,'counted',counted,'variance_lines',(SELECT count(*) FROM api.inventory_count_lines WHERE session_id=sess.id AND actual_quantity<>system_quantity)));
 RETURN jsonb_build_object('ok',true,'session_id',sess.id,'status','SUBMITTED','version',sess.version+1,'counted',counted,'uncounted',missing);
END $$;

CREATE OR REPLACE FUNCTION api.approve_inventory_count(p_session_id bigint,p_approver text,p_reason text,p_expected_version integer)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE sess api.inventory_count_sessions%ROWTYPE; line api.inventory_count_lines%ROWTYPE; current_qty numeric; delta numeric; mid integer; movements integer:=0; net numeric:=0;
BEGIN
 SELECT * INTO sess FROM api.inventory_count_sessions WHERE id=p_session_id FOR UPDATE;
 IF sess.id IS NULL THEN RAISE EXCEPTION 'Inventory count not found';END IF;
 IF sess.status<>'SUBMITTED' THEN RAISE EXCEPTION 'Inventory count is %',sess.status;END IF;
 IF sess.version<>p_expected_version THEN RAISE EXCEPTION 'Stale inventory count version';END IF;
 IF length(trim(COALESCE(p_approver,'')))<2 THEN RAISE EXCEPTION 'Approver is required';END IF;
 IF lower(trim(p_approver))=lower(trim(sess.operator_name)) THEN RAISE EXCEPTION 'Approver must be different from count operator';END IF;
 IF length(trim(COALESCE(p_reason,'')))<5 THEN RAISE EXCEPTION 'Approval reason must have at least 5 characters';END IF;
 FOR line IN SELECT * FROM api.inventory_count_lines WHERE session_id=sess.id AND actual_quantity IS NOT NULL ORDER BY id FOR UPDATE LOOP
  current_qty:=api.inventory_product_quantity(sess.warehouse_id,line.product_id);
  IF current_qty<>line.system_quantity THEN RAISE EXCEPTION 'Stock changed after snapshot for product % (snapshot %, current %); restart the count',line.product_id,line.system_quantity,current_qty;END IF;
  delta:=line.actual_quantity-line.system_quantity;
  IF delta<>0 THEN
   INSERT INTO api.movimientos_stock(fecha_movimiento,movimiento_tipo,almacen_origen_id,almacen_destino_id,producto_id,cantidad,doc_tipo,doc_id,doc_linea_id,referencia,observacion)
   VALUES(now(),CASE WHEN delta>0 THEN 'AJUSTE_POSITIVO' ELSE 'AJUSTE_NEGATIVO' END,CASE WHEN delta<0 THEN sess.warehouse_id ELSE NULL END,CASE WHEN delta>0 THEN sess.warehouse_id ELSE NULL END,line.product_id,abs(delta),'INVENTORY_COUNT',sess.id,line.id,sess.reference,'Approved count: '||left(trim(p_reason),300)) RETURNING id INTO mid;
   UPDATE api.inventory_count_lines SET movement_id=mid,updated_at=now() WHERE id=line.id;
   movements:=movements+1;net:=net+delta;
  END IF;
 END LOOP;
 UPDATE api.inventory_count_sessions SET status='POSTED',version=version+1,posted_at=now(),approved_by=left(trim(p_approver),80),approval_reason=left(trim(p_reason),500),updated_at=now() WHERE id=sess.id;
 INSERT INTO api.inventory_count_events(session_id,event_type,actor,details) VALUES(sess.id,'APPROVED_AND_POSTED',left(trim(p_approver),80),jsonb_build_object('reason',p_reason,'movement_count',movements,'net_adjustment',net));
 RETURN jsonb_build_object('ok',true,'session_id',sess.id,'status','POSTED','version',sess.version+1,'movement_count',movements,'net_adjustment',net);
END $$;

CREATE OR REPLACE FUNCTION api.void_inventory_count(p_session_id bigint,p_actor text,p_reason text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE sess api.inventory_count_sessions%ROWTYPE;
BEGIN
 SELECT * INTO sess FROM api.inventory_count_sessions WHERE id=p_session_id FOR UPDATE;
 IF sess.id IS NULL THEN RAISE EXCEPTION 'Inventory count not found';END IF;
 IF sess.status NOT IN('ACTIVE','SUBMITTED') THEN RAISE EXCEPTION 'Only active or submitted counts can be voided';END IF;
 IF length(trim(COALESCE(p_reason,'')))<5 THEN RAISE EXCEPTION 'Void reason must have at least 5 characters';END IF;
 UPDATE api.inventory_count_sessions SET status='VOIDED',version=version+1,voided_at=now(),voided_by=left(trim(p_actor),80),void_reason=left(trim(p_reason),500),updated_at=now() WHERE id=sess.id;
 INSERT INTO api.inventory_count_events(session_id,event_type,actor,details) VALUES(sess.id,'VOIDED',left(trim(p_actor),80),jsonb_build_object('reason',p_reason,'from_status',sess.status));
 RETURN jsonb_build_object('ok',true,'session_id',sess.id,'status','VOIDED','version',sess.version+1);
END $$;

CREATE OR REPLACE VIEW api.v_inventory_count_lines AS
SELECT l.id,l.session_id,s.reference,s.warehouse_id,a.codigo warehouse_code,a.nombre warehouse_name,s.count_scope,s.status session_status,s.version,
 l.product_id,p.cdg_prod,p.nombre product_name,l.system_quantity,l.reserved_quantity,l.actual_quantity,
 CASE WHEN l.actual_quantity IS NULL THEN NULL ELSE l.actual_quantity-l.system_quantity END variance,
 (l.actual_quantity IS NOT NULL) counted,l.counted_at,l.counted_by,l.scan_count,l.movement_id,l.updated_at
FROM api.inventory_count_lines l JOIN api.inventory_count_sessions s ON s.id=l.session_id JOIN api.productos p ON p.id=l.product_id JOIN api.almacenes a ON a.id=s.warehouse_id;

GRANT SELECT ON api.inventory_count_sessions,api.inventory_count_lines,api.inventory_count_events,api.v_inventory_count_lines TO web_anon;
GRANT USAGE,SELECT ON SEQUENCE api.inventory_count_sessions_id_seq,api.inventory_count_lines_id_seq,api.inventory_count_events_id_seq TO web_anon;
GRANT EXECUTE ON FUNCTION api.inventory_product_quantity(integer,integer),api.inventory_product_reserved(integer,integer),api.create_inventory_count(integer,text,text,text),api.scan_inventory_count(bigint,text,numeric,text),api.set_inventory_count_quantity(bigint,integer,numeric,text),api.submit_inventory_count(bigint,text,text,integer),api.approve_inventory_count(bigint,text,text,integer),api.void_inventory_count(bigint,text,text) TO web_anon;

NOTIFY pgrst,'reload schema';
COMMIT;
