BEGIN;

CREATE TABLE IF NOT EXISTS api.product_barcodes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id integer NOT NULL REFERENCES api.productos(id) ON DELETE CASCADE,
    barcode text NOT NULL,
    label text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT product_barcodes_value_check CHECK (trim(barcode) <> ''),
    CONSTRAINT product_barcodes_unique UNIQUE (barcode)
);

INSERT INTO api.product_barcodes(producto_id, barcode, label)
SELECT id, cdg_prod, 'Código interno'
FROM api.productos
WHERE trim(COALESCE(cdg_prod,'')) <> ''
ON CONFLICT (barcode) DO NOTHING;

CREATE TABLE IF NOT EXISTS api.picking_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id integer NOT NULL REFERENCES api.pedidos(id) ON DELETE RESTRICT,
    status text NOT NULL DEFAULT 'ACTIVE',
    operator_name text NOT NULL DEFAULT 'picking',
    started_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    stock_consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT picking_sessions_status_check CHECK(status IN ('ACTIVE','COMPLETED','CANCELLED'))
);
CREATE UNIQUE INDEX IF NOT EXISTS picking_sessions_one_active_order
ON api.picking_sessions(pedido_id) WHERE status='ACTIVE';

CREATE TABLE IF NOT EXISTS api.picking_session_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL REFERENCES api.picking_sessions(id) ON DELETE CASCADE,
    pedido_item_id integer NOT NULL REFERENCES api.pedido_items(id) ON DELETE RESTRICT,
    producto_id integer REFERENCES api.productos(id) ON DELETE RESTRICT,
    required_quantity numeric(14,3) NOT NULL,
    scanned_quantity numeric(14,3) NOT NULL DEFAULT 0,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT picking_item_quantities_check CHECK(required_quantity > 0 AND scanned_quantity >= 0 AND scanned_quantity <= required_quantity),
    CONSTRAINT picking_session_item_unique UNIQUE(session_id,pedido_item_id)
);

CREATE TABLE IF NOT EXISTS api.picking_scan_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id bigint NOT NULL REFERENCES api.picking_sessions(id) ON DELETE RESTRICT,
    picking_item_id bigint REFERENCES api.picking_session_items(id) ON DELETE RESTRICT,
    barcode text NOT NULL,
    result text NOT NULL,
    operator_name text NOT NULL,
    detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT picking_scan_result_check CHECK(result IN ('ACCEPTED','UNKNOWN_BARCODE','NOT_IN_ORDER','OVER_PICK','COMPLETED'))
);

CREATE OR REPLACE FUNCTION api.ensure_picking_session(p_pedido_id integer,p_operator text DEFAULT 'picking')
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE sid bigint; order_state text;
BEGIN
 SELECT estado INTO order_state FROM api.pedidos WHERE id=p_pedido_id FOR UPDATE;
 IF order_state IS NULL THEN RAISE EXCEPTION 'Order not found'; END IF;
 IF order_state NOT IN ('CONFIRMADO','EN_PREPARACION') THEN RAISE EXCEPTION 'Order % cannot be picked from state %',p_pedido_id,order_state; END IF;
 SELECT id INTO sid FROM api.picking_sessions WHERE pedido_id=p_pedido_id AND status='ACTIVE' FOR UPDATE;
 IF sid IS NULL THEN
   INSERT INTO api.picking_sessions(pedido_id,operator_name) VALUES(p_pedido_id,left(COALESCE(NULLIF(trim(p_operator),''),'picking'),80)) RETURNING id INTO sid;
   INSERT INTO api.picking_session_items(session_id,pedido_item_id,producto_id,required_quantity)
   SELECT sid,id,producto_id,cantidad FROM api.pedido_items WHERE pedido_id=p_pedido_id ORDER BY id;
 END IF;
 RETURN sid;
END $$;

CREATE OR REPLACE FUNCTION api.scan_picking_barcode(p_pedido_num text,p_token text,p_barcode text,p_operator text DEFAULT 'picking')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE oid integer; sid bigint; pid integer; line api.picking_session_items%ROWTYPE; clean text;
BEGIN
 clean:=trim(COALESCE(p_barcode,'')); IF clean='' OR length(clean)>120 THEN RAISE EXCEPTION 'Invalid barcode'; END IF;
 SELECT id INTO oid FROM api.pedidos WHERE pedido_num=trim(p_pedido_num) AND public_token=trim(p_token) AND public_token_expires_at>now() FOR UPDATE;
 IF oid IS NULL THEN RAISE EXCEPTION 'Invalid or expired order link'; END IF;
 sid:=api.ensure_picking_session(oid,p_operator);
 SELECT producto_id INTO pid FROM api.product_barcodes WHERE barcode=clean AND active=true;
 IF pid IS NULL THEN
   INSERT INTO api.picking_scan_events(session_id,barcode,result,operator_name) VALUES(sid,clean,'UNKNOWN_BARCODE',left(COALESCE(p_operator,'picking'),80));
   RETURN jsonb_build_object('ok',false,'reason','UNKNOWN_BARCODE','barcode',clean);
 END IF;
 SELECT * INTO line FROM api.picking_session_items WHERE session_id=sid AND producto_id=pid AND scanned_quantity<required_quantity ORDER BY id LIMIT 1 FOR UPDATE;
 IF line.id IS NULL THEN
   IF EXISTS(SELECT 1 FROM api.picking_session_items WHERE session_id=sid AND producto_id=pid) THEN
     INSERT INTO api.picking_scan_events(session_id,barcode,result,operator_name,detail) VALUES(sid,clean,'OVER_PICK',left(COALESCE(p_operator,'picking'),80),jsonb_build_object('producto_id',pid));
     RETURN jsonb_build_object('ok',false,'reason','OVER_PICK','barcode',clean);
   END IF;
   INSERT INTO api.picking_scan_events(session_id,barcode,result,operator_name,detail) VALUES(sid,clean,'NOT_IN_ORDER',left(COALESCE(p_operator,'picking'),80),jsonb_build_object('producto_id',pid));
   RETURN jsonb_build_object('ok',false,'reason','NOT_IN_ORDER','barcode',clean);
 END IF;
 UPDATE api.picking_session_items SET scanned_quantity=least(required_quantity,scanned_quantity+1),updated_at=now() WHERE id=line.id;
 INSERT INTO api.picking_scan_events(session_id,picking_item_id,barcode,result,operator_name,detail) VALUES(sid,line.id,clean,'ACCEPTED',left(COALESCE(p_operator,'picking'),80),jsonb_build_object('producto_id',pid));
 RETURN jsonb_build_object('ok',true,'reason','ACCEPTED','session_id',sid,'pedido_item_id',line.pedido_item_id,'scanned_quantity',least(line.required_quantity,line.scanned_quantity+1),'required_quantity',line.required_quantity,
   'complete',NOT EXISTS(SELECT 1 FROM api.picking_session_items WHERE session_id=sid AND scanned_quantity<required_quantity));
END $$;

CREATE OR REPLACE FUNCTION api.complete_scanner_picking(p_pedido_num text,p_token text,p_operator text DEFAULT 'picking')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE oid integer; sid bigint; consumed jsonb; missing integer;
BEGIN
 SELECT id INTO oid FROM api.pedidos WHERE pedido_num=trim(p_pedido_num) AND public_token=trim(p_token) AND public_token_expires_at>now() FOR UPDATE;
 IF oid IS NULL THEN RAISE EXCEPTION 'Invalid or expired order link'; END IF;
 SELECT id INTO sid FROM api.picking_sessions WHERE pedido_id=oid AND status='ACTIVE' FOR UPDATE;
 IF sid IS NULL THEN RAISE EXCEPTION 'No active scanner picking session'; END IF;
 SELECT count(*) INTO missing FROM api.picking_session_items WHERE session_id=sid AND scanned_quantity<>required_quantity;
 IF missing>0 THEN RAISE EXCEPTION 'Picking incomplete: % line(s) remain',missing; END IF;
 consumed:=api.consumir_reserva_pedido(oid);
 UPDATE api.picking_sessions SET status='COMPLETED',completed_at=now(),stock_consumed_at=now(),operator_name=left(COALESCE(p_operator,'picking'),80),updated_at=now() WHERE id=sid;
 INSERT INTO api.picking_scan_events(session_id,barcode,result,operator_name,detail) VALUES(sid,'[COMPLETE]','COMPLETED',left(COALESCE(p_operator,'picking'),80),jsonb_build_object('stock',consumed));
 UPDATE api.pedidos SET estado='DESPACHADO',updated_at=now() WHERE id=oid;
 BEGIN PERFORM api.ofrecer_delivery_a_siguiente_repartidor(oid); EXCEPTION WHEN undefined_function OR undefined_table THEN NULL; END;
 RETURN jsonb_build_object('ok',true,'pedido_id',oid,'session_id',sid,'estado','DESPACHADO','stock',consumed);
END $$;

CREATE OR REPLACE VIEW api.v_picking_progress AS
SELECT s.id session_id,s.pedido_id,p.pedido_num,s.status,s.operator_name,s.started_at,s.completed_at,s.stock_consumed_at,
 count(i.id) line_count,count(i.id) FILTER(WHERE i.scanned_quantity=i.required_quantity) complete_lines,
 COALESCE(sum(i.required_quantity),0) required_quantity,COALESCE(sum(i.scanned_quantity),0) scanned_quantity,
 COALESCE(bool_and(i.scanned_quantity=i.required_quantity),false) complete
FROM api.picking_sessions s JOIN api.pedidos p ON p.id=s.pedido_id LEFT JOIN api.picking_session_items i ON i.session_id=s.id
GROUP BY s.id,p.pedido_num;

CREATE OR REPLACE VIEW api.v_picking_item_progress AS
SELECT s.id session_id,s.pedido_id,s.status session_status,i.id picking_item_id,i.pedido_item_id,
 i.producto_id,pi.producto_texto,p.cdg_prod,p.nombre producto_nombre,i.required_quantity,i.scanned_quantity,
 (i.required_quantity-i.scanned_quantity) remaining_quantity,(i.scanned_quantity=i.required_quantity) complete,i.updated_at
FROM api.picking_sessions s JOIN api.picking_session_items i ON i.session_id=s.id
JOIN api.pedido_items pi ON pi.id=i.pedido_item_id LEFT JOIN api.productos p ON p.id=i.producto_id;

GRANT SELECT ON api.product_barcodes,api.picking_sessions,api.picking_session_items,api.picking_scan_events,api.v_picking_progress,api.v_picking_item_progress TO web_anon;
GRANT EXECUTE ON FUNCTION api.ensure_picking_session(integer,text),api.scan_picking_barcode(text,text,text,text),api.complete_scanner_picking(text,text,text) TO web_anon;
NOTIFY pgrst,'reload schema';
COMMIT;
