BEGIN;

CREATE SCHEMA IF NOT EXISTS api;

-- =========================================================
-- REPLAU DRIVER DISPATCH MODULE
-- First version: fixed driver fee + round-robin assignment.
-- =========================================================

CREATE TABLE IF NOT EXISTS api.repartidores (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text NOT NULL UNIQUE,
    nombre text NOT NULL,
    whatsapp_number text NOT NULL UNIQUE,
    activo boolean NOT NULL DEFAULT true,
    orden_turno integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS api.delivery_config (
    key text PRIMARY KEY,
    value text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO api.delivery_config(key, value)
VALUES ('driver_fee_pen', '7.00')
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS api.delivery_asignaciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id integer NOT NULL REFERENCES api.pedidos(id) ON DELETE CASCADE,
    repartidor_id integer REFERENCES api.repartidores(id) ON DELETE SET NULL,
    status text NOT NULL DEFAULT 'OFFERED',
    fee numeric(14,2) NOT NULL DEFAULT 0,
    offered_at timestamptz NOT NULL DEFAULT now(),
    responded_at timestamptz,
    assigned_at timestamptz,
    rejected_at timestamptz,
    completed_at timestamptz,
    driver_latitude numeric(12,8),
    driver_longitude numeric(12,8),
    driver_location_at timestamptz,
    response_text text,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT delivery_asignaciones_status_check
    CHECK (status IN ('OFFERED','ACCEPTED','REJECTED','EXPIRED','ASSIGNED','COMPLETED','CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_delivery_asignaciones_pedido
ON api.delivery_asignaciones(pedido_id);

CREATE INDEX IF NOT EXISTS idx_delivery_asignaciones_repartidor_status
ON api.delivery_asignaciones(repartidor_id, status);

CREATE INDEX IF NOT EXISTS idx_delivery_asignaciones_status_created
ON api.delivery_asignaciones(status, created_at);

CREATE OR REPLACE FUNCTION api.delivery_driver_fee()
RETURNS numeric
LANGUAGE sql
STABLE
AS $$
    SELECT COALESCE(
        (SELECT value::numeric FROM api.delivery_config WHERE key = 'driver_fee_pen'),
        7.00
    );
$$;

CREATE OR REPLACE FUNCTION api.driver_accept_words(p_text text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT lower(trim(COALESCE(p_text, ''))) IN ('acepto','aceptar','si','sí','s','ok','dale','confirmo','aceptado');
$$;

CREATE OR REPLACE FUNCTION api.driver_reject_words(p_text text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT lower(trim(COALESCE(p_text, ''))) IN ('no','rechazo','rechazar','paso','no puedo','ocupado','cancelar');
$$;

CREATE OR REPLACE FUNCTION api.delivery_offer_message(p_pedido_id integer, p_fee numeric)
RETURNS text
LANGUAGE plpgsql
STABLE
SET search_path = api, public
AS $$
DECLARE
    v_order record;
BEGIN
    SELECT * INTO v_order
    FROM api.v_pedidos_logistica
    WHERE id = p_pedido_id;

    IF v_order.id IS NULL THEN
        RETURN NULL;
    END IF;

    RETURN
        'Nuevo delivery disponible 🛵' || E'\n\n' ||
        'Pedido: ' || v_order.pedido_num || E'\n' ||
        'Dirección:' || E'\n' ||
        COALESCE(v_order.direccion_confirmada, v_order.direccion_detectada, '(sin dirección)') || E'\n\n' ||
        CASE WHEN v_order.maps_url IS NOT NULL THEN 'Mapa: ' || v_order.maps_url || E'\n\n' ELSE '' END ||
        'Pago carrera: S/ ' || to_char(p_fee, 'FM999999990.00') || E'\n\n' ||
        'Responde ACEPTAR para tomarlo o NO para pasarlo.';
END;
$$;

CREATE OR REPLACE FUNCTION api.delivery_assignment_message(p_pedido_id integer)
RETURNS text
LANGUAGE plpgsql
STABLE
SET search_path = api, public
AS $$
DECLARE
    v_order record;
BEGIN
    SELECT * INTO v_order
    FROM api.v_pedidos_logistica
    WHERE id = p_pedido_id;

    IF v_order.id IS NULL THEN
        RETURN 'Pedido asignado ✅\n\nPor favor comparte tu ubicación por WhatsApp.';
    END IF;

    RETURN
        'Pedido asignado ✅' || E'\n\n' ||
        'Pedido: ' || v_order.pedido_num || E'\n' ||
        'Dirección:' || E'\n' ||
        COALESCE(v_order.direccion_confirmada, v_order.direccion_detectada, '(sin dirección)') || E'\n\n' ||
        CASE WHEN v_order.maps_url IS NOT NULL THEN 'Mapa: ' || v_order.maps_url || E'\n\n' ELSE '' END ||
        'Por favor comparte tu ubicación por WhatsApp.';
END;
$$;

CREATE OR REPLACE FUNCTION api.ofrecer_delivery_a_siguiente_repartidor(p_pedido_id integer)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
    v_driver record;
    v_last_order integer;
    v_fee numeric(14,2) := api.delivery_driver_fee();
    v_assignment_id integer;
    v_message text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM api.pedidos WHERE id = p_pedido_id) THEN
        RETURN jsonb_build_object('ok', false, 'error', 'Pedido not found');
    END IF;

    SELECT COALESCE(max(r.orden_turno), -1)
    INTO v_last_order
    FROM api.delivery_asignaciones a
    JOIN api.repartidores r ON r.id = a.repartidor_id
    WHERE a.created_at > now() - interval '24 hours';

    SELECT * INTO v_driver
    FROM api.repartidores r
    WHERE r.activo = true
      AND NOT EXISTS (
          SELECT 1
          FROM api.delivery_asignaciones a
          WHERE a.pedido_id = p_pedido_id
            AND a.repartidor_id = r.id
            AND a.status IN ('OFFERED','ACCEPTED','REJECTED','ASSIGNED')
      )
    ORDER BY
      CASE WHEN r.orden_turno > COALESCE(v_last_order, -1) THEN 0 ELSE 1 END,
      r.orden_turno,
      r.id
    LIMIT 1;

    IF v_driver.id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'error', 'No active drivers available');
    END IF;

    v_message := api.delivery_offer_message(p_pedido_id, v_fee);

    INSERT INTO api.delivery_asignaciones(pedido_id, repartidor_id, status, fee)
    VALUES (p_pedido_id, v_driver.id, 'OFFERED', v_fee)
    RETURNING id INTO v_assignment_id;

    INSERT INTO api.whatsapp_outbox(pedido_id, whatsapp_number, message_text, event_type, status)
    VALUES (p_pedido_id, v_driver.whatsapp_number, v_message, 'CUSTOM', 'PENDING');

    RETURN jsonb_build_object(
        'ok', true,
        'assignment_id', v_assignment_id,
        'pedido_id', p_pedido_id,
        'repartidor_id', v_driver.id,
        'repartidor_codigo', v_driver.codigo,
        'repartidor_nombre', v_driver.nombre,
        'fee', v_fee
    );
END;
$$;

CREATE OR REPLACE FUNCTION api.repartidor_responder_delivery(
    p_whatsapp_number text,
    p_response_text text,
    p_latitude numeric DEFAULT NULL,
    p_longitude numeric DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
    v_driver record;
    v_assignment record;
    v_accept boolean := api.driver_accept_words(p_response_text);
    v_reject boolean := api.driver_reject_words(p_response_text);
    v_message text;
    v_next jsonb;
BEGIN
    SELECT * INTO v_driver
    FROM api.repartidores
    WHERE whatsapp_number = trim(p_whatsapp_number)
      AND activo = true
    LIMIT 1;

    IF v_driver.id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'handled', false, 'error', 'Not an active driver');
    END IF;

    IF p_latitude IS NOT NULL AND p_longitude IS NOT NULL THEN
        SELECT * INTO v_assignment
        FROM api.delivery_asignaciones
        WHERE repartidor_id = v_driver.id
          AND status IN ('ACCEPTED','ASSIGNED')
        ORDER BY assigned_at DESC NULLS LAST, responded_at DESC NULLS LAST, created_at DESC
        LIMIT 1;

        IF v_assignment.id IS NULL THEN
            RETURN jsonb_build_object('ok', true, 'handled', true, 'driver_status', 'NO_ACTIVE_ASSIGNMENT');
        END IF;

        UPDATE api.delivery_asignaciones
        SET driver_latitude = p_latitude,
            driver_longitude = p_longitude,
            driver_location_at = now(),
            updated_at = now()
        WHERE id = v_assignment.id;

        INSERT INTO api.whatsapp_outbox(pedido_id, cliente_id, whatsapp_number, message_text, event_type, status)
        SELECT
            p.id,
            p.cliente_id,
            c.whatsapp_number,
            'Tu pedido está en camino 🛵' || E'\n\n' ||
            'Pedido: ' || p.pedido_num || E'\n' ||
            'Última ubicación del repartidor:' || E'\n' ||
            'https://www.google.com/maps?q=' || p_latitude::text || ',' || p_longitude::text || E'\n\n' ||
            CASE
                WHEN p.order_url IS NOT NULL THEN 'Tracking: ' || replace(p.order_url, '/order/', '/track/')
                ELSE ''
            END,
            'CUSTOM',
            'PENDING'
        FROM api.pedidos p
        JOIN api.clientes_whatsapp c ON c.id = p.cliente_id
        WHERE p.id = v_assignment.pedido_id
          AND c.whatsapp_number IS NOT NULL
          AND trim(c.whatsapp_number) <> '';

        RETURN jsonb_build_object('ok', true, 'handled', true, 'driver_status', 'LOCATION_SAVED', 'assignment_id', v_assignment.id);
    END IF;

    SELECT * INTO v_assignment
    FROM api.delivery_asignaciones
    WHERE repartidor_id = v_driver.id
      AND status = 'OFFERED'
    ORDER BY offered_at ASC
    LIMIT 1;

    IF v_assignment.id IS NULL THEN
        RETURN jsonb_build_object('ok', true, 'handled', true, 'driver_status', 'NO_PENDING_OFFER');
    END IF;

    IF v_accept THEN
        UPDATE api.delivery_asignaciones
        SET status = 'ASSIGNED',
            responded_at = now(),
            assigned_at = now(),
            response_text = p_response_text,
            updated_at = now()
        WHERE id = v_assignment.id;

        v_message := api.delivery_assignment_message(v_assignment.pedido_id);
        INSERT INTO api.whatsapp_outbox(pedido_id, whatsapp_number, message_text, event_type, status)
        VALUES (v_assignment.pedido_id, v_driver.whatsapp_number, v_message, 'CUSTOM', 'PENDING');

        RETURN jsonb_build_object('ok', true, 'handled', true, 'driver_status', 'ASSIGNED', 'assignment_id', v_assignment.id, 'pedido_id', v_assignment.pedido_id);
    END IF;

    IF v_reject THEN
        UPDATE api.delivery_asignaciones
        SET status = 'REJECTED',
            responded_at = now(),
            rejected_at = now(),
            response_text = p_response_text,
            updated_at = now()
        WHERE id = v_assignment.id;

        v_next := api.ofrecer_delivery_a_siguiente_repartidor(v_assignment.pedido_id);
        RETURN jsonb_build_object('ok', true, 'handled', true, 'driver_status', 'REJECTED', 'assignment_id', v_assignment.id, 'next_offer', v_next);
    END IF;

    RETURN jsonb_build_object('ok', true, 'handled', true, 'driver_status', 'UNKNOWN_RESPONSE', 'assignment_id', v_assignment.id);
END;
$$;

CREATE OR REPLACE VIEW api.v_delivery_asignaciones AS
SELECT
    a.id,
    a.pedido_id,
    p.pedido_num,
    p.estado AS pedido_estado,
    a.repartidor_id,
    r.codigo AS repartidor_codigo,
    r.nombre AS repartidor_nombre,
    r.whatsapp_number AS repartidor_whatsapp,
    a.status,
    a.fee,
    a.offered_at,
    a.responded_at,
    a.assigned_at,
    a.rejected_at,
    a.completed_at,
    a.driver_latitude,
    a.driver_longitude,
    a.driver_location_at,
    a.response_text,
    a.notes,
    a.created_at,
    a.updated_at
FROM api.delivery_asignaciones a
JOIN api.pedidos p ON p.id = a.pedido_id
LEFT JOIN api.repartidores r ON r.id = a.repartidor_id;

GRANT SELECT ON api.repartidores, api.delivery_config, api.delivery_asignaciones, api.v_delivery_asignaciones TO web_anon;
GRANT EXECUTE ON FUNCTION api.delivery_driver_fee() TO web_anon;
GRANT EXECUTE ON FUNCTION api.ofrecer_delivery_a_siguiente_repartidor(integer) TO web_anon;
GRANT EXECUTE ON FUNCTION api.repartidor_responder_delivery(text, text, numeric, numeric) TO web_anon;

COMMIT;
