BEGIN;

ALTER TABLE api.proveedores ADD COLUMN IF NOT EXISTS payment_terms_days integer NOT NULL DEFAULT 0;
ALTER TABLE api.proveedores ADD COLUMN IF NOT EXISTS lead_time_days integer NOT NULL DEFAULT 0;
ALTER TABLE api.proveedores ADD COLUMN IF NOT EXISTS contact_name text;
DO $$ BEGIN ALTER TABLE api.proveedores ADD CONSTRAINT proveedores_terms_check CHECK(payment_terms_days>=0 AND lead_time_days>=0); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS api.supplier_product_catalog(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 supplier_id integer NOT NULL REFERENCES api.proveedores(id) ON DELETE CASCADE,
 product_id integer NOT NULL REFERENCES api.productos(id) ON DELETE RESTRICT,
 supplier_sku text,packaging_level text NOT NULL DEFAULT 'UNIT',unit_factor numeric(14,3) NOT NULL DEFAULT 1,
 unit_price numeric(14,4) NOT NULL DEFAULT 0,currency char(3) NOT NULL DEFAULT 'PEN',minimum_order_quantity numeric(14,3) NOT NULL DEFAULT 1,
 lead_time_days integer,active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT supplier_product_unique UNIQUE(supplier_id,product_id,packaging_level),
 CONSTRAINT supplier_product_values_check CHECK(unit_factor>0 AND unit_price>=0 AND minimum_order_quantity>0 AND COALESCE(lead_time_days,0)>=0),
 CONSTRAINT supplier_product_currency_check CHECK(currency IN('PEN','USD','EUR'))
);

ALTER TABLE api.ordenes_compra ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;
ALTER TABLE api.ordenes_compra ADD COLUMN IF NOT EXISTS approved_at timestamptz;
ALTER TABLE api.ordenes_compra ADD COLUMN IF NOT EXISTS approved_by text;
ALTER TABLE api.ordenes_compra ADD COLUMN IF NOT EXISTS sent_at timestamptz;
ALTER TABLE api.ordenes_compra ADD COLUMN IF NOT EXISTS sent_by text;
ALTER TABLE api.ordenes_compra ADD COLUMN IF NOT EXISTS cancelled_at timestamptz;
ALTER TABLE api.ordenes_compra ADD COLUMN IF NOT EXISTS cancelled_by text;
ALTER TABLE api.ordenes_compra ADD COLUMN IF NOT EXISTS cancellation_reason text;
ALTER TABLE api.ordenes_compra DROP CONSTRAINT IF EXISTS ordenes_compra_estado_check;
ALTER TABLE api.ordenes_compra ADD CONSTRAINT ordenes_compra_estado_check CHECK(estado IN('BORRADOR','ABIERTA','APROBADA','ENVIADA','PARCIAL','CERRADA','ANULADA'));

CREATE TABLE IF NOT EXISTS api.purchase_order_events(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id integer NOT NULL REFERENCES api.ordenes_compra(id) ON DELETE RESTRICT,
 event_type text NOT NULL,actor text NOT NULL,from_status text,to_status text,details jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE api.inventory_receiving_sessions ADD COLUMN IF NOT EXISTS purchase_order_id integer REFERENCES api.ordenes_compra(id) ON DELETE RESTRICT;
ALTER TABLE api.inventory_receiving_sessions ADD COLUMN IF NOT EXISTS legacy_receipt_id integer REFERENCES api.recepciones(id) ON DELETE RESTRICT;
ALTER TABLE api.inventory_receiving_scans ADD COLUMN IF NOT EXISTS purchase_order_line_id integer REFERENCES api.ordenes_compra_detalle(id) ON DELETE RESTRICT;

CREATE OR REPLACE FUNCTION api.create_purchase_order(p_supplier_id integer,p_delivery_date date,p_currency text,p_actor text,p_notes text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE oid integer; ref text;
BEGIN
 IF NOT EXISTS(SELECT 1 FROM api.proveedores WHERE id=p_supplier_id AND active) THEN RAISE EXCEPTION 'Active supplier not found'; END IF;
 IF upper(p_currency) NOT IN('PEN','USD','EUR') THEN RAISE EXCEPTION 'Invalid currency'; END IF;
 ref:='PO-'||to_char(clock_timestamp(),'YYYYMMDD-HH24MISS-MS');
 INSERT INTO api.ordenes_compra(num_ocom,proveedor_id,fecha_ocom,fecha_entrega,moneda,estado,observacion)
 VALUES(ref,p_supplier_id,current_date,p_delivery_date,upper(p_currency),'BORRADOR',NULLIF(trim(p_notes),'')) RETURNING id INTO oid;
 INSERT INTO api.purchase_order_events(order_id,event_type,actor,to_status,details) VALUES(oid,'CREATED',left(COALESCE(p_actor,'procurement'),80),'BORRADOR',jsonb_build_object('reference',ref));
 RETURN jsonb_build_object('ok',true,'order_id',oid,'reference',ref,'status','BORRADOR','version',1);
END $$;

CREATE OR REPLACE FUNCTION api.add_purchase_order_line(p_order_id integer,p_product_id integer,p_quantity numeric,p_unit_price numeric,p_tax numeric DEFAULT 0,p_discount numeric DEFAULT 0,p_actor text DEFAULT 'procurement')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE ord api.ordenes_compra%ROWTYPE; line_no integer; lid integer;
BEGIN
 SELECT * INTO ord FROM api.ordenes_compra WHERE id=p_order_id FOR UPDATE;
 IF ord.id IS NULL THEN RAISE EXCEPTION 'Purchase order not found'; END IF; IF ord.estado<>'BORRADOR' THEN RAISE EXCEPTION 'Lines can change only in BORRADOR'; END IF;
 IF p_quantity<=0 OR p_unit_price<0 OR p_tax<0 OR p_discount<0 THEN RAISE EXCEPTION 'Invalid line values'; END IF;
 SELECT COALESCE(max(linea),0)+1 INTO line_no FROM api.ordenes_compra_detalle WHERE orden_id=ord.id;
 INSERT INTO api.ordenes_compra_detalle(orden_id,linea,producto_id,descripcion,cantidad_pedida,precio_unitario,impuesto,descuento)
 SELECT ord.id,line_no,p.id,p.nombre,p_quantity,p_unit_price,p_tax,p_discount FROM api.productos p WHERE p.id=p_product_id AND p.active RETURNING id INTO lid;
 IF lid IS NULL THEN RAISE EXCEPTION 'Active product not found'; END IF;
 UPDATE api.ordenes_compra SET version=version+1,updated_at=now() WHERE id=ord.id;
 INSERT INTO api.purchase_order_events(order_id,event_type,actor,from_status,to_status,details) VALUES(ord.id,'LINE_ADDED',left(COALESCE(p_actor,'procurement'),80),ord.estado,ord.estado,jsonb_build_object('line_id',lid,'product_id',p_product_id,'quantity',p_quantity,'unit_price',p_unit_price));
 RETURN jsonb_build_object('ok',true,'line_id',lid,'line_number',line_no,'version',ord.version+1);
END $$;

CREATE OR REPLACE FUNCTION api.transition_purchase_order(p_order_id integer,p_action text,p_actor text,p_expected_version integer,p_reason text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE ord api.ordenes_compra%ROWTYPE; target text; action text:=upper(trim(p_action));
BEGIN
 SELECT * INTO ord FROM api.ordenes_compra WHERE id=p_order_id FOR UPDATE;
 IF ord.id IS NULL THEN RAISE EXCEPTION 'Purchase order not found'; END IF; IF ord.version<>p_expected_version THEN RAISE EXCEPTION 'Stale purchase order version'; END IF;
 target:=CASE WHEN action='APPROVE' AND ord.estado='BORRADOR' THEN 'APROBADA' WHEN action='SEND' AND ord.estado='APROBADA' THEN 'ENVIADA' WHEN action='CANCEL' AND ord.estado IN('BORRADOR','APROBADA','ENVIADA','ABIERTA','PARCIAL') THEN 'ANULADA' ELSE NULL END;
 IF target IS NULL THEN RAISE EXCEPTION 'Action % is not allowed from %',action,ord.estado; END IF;
 IF action='APPROVE' AND NOT EXISTS(SELECT 1 FROM api.ordenes_compra_detalle WHERE orden_id=ord.id AND estado<>'ANULADA') THEN RAISE EXCEPTION 'Cannot approve an empty purchase order'; END IF;
 IF action='CANCEL' AND length(trim(COALESCE(p_reason,'')))<5 THEN RAISE EXCEPTION 'Cancellation reason must have at least 5 characters'; END IF;
 UPDATE api.ordenes_compra SET estado=target,version=version+1,approved_at=CASE WHEN action='APPROVE' THEN now() ELSE approved_at END,approved_by=CASE WHEN action='APPROVE' THEN left(p_actor,80) ELSE approved_by END,sent_at=CASE WHEN action='SEND' THEN now() ELSE sent_at END,sent_by=CASE WHEN action='SEND' THEN left(p_actor,80) ELSE sent_by END,cancelled_at=CASE WHEN action='CANCEL' THEN now() ELSE cancelled_at END,cancelled_by=CASE WHEN action='CANCEL' THEN left(p_actor,80) ELSE cancelled_by END,cancellation_reason=CASE WHEN action='CANCEL' THEN left(trim(p_reason),500) ELSE cancellation_reason END,updated_at=now() WHERE id=ord.id;
 INSERT INTO api.purchase_order_events(order_id,event_type,actor,from_status,to_status,details) VALUES(ord.id,action,left(COALESCE(p_actor,'procurement'),80),ord.estado,target,jsonb_build_object('reason',p_reason,'expected_version',p_expected_version));
 RETURN jsonb_build_object('ok',true,'order_id',ord.id,'status',target,'version',ord.version+1);
END $$;

CREATE OR REPLACE FUNCTION api.create_low_stock_draft(p_supplier_id integer,p_actor text DEFAULT 'procurement')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE created jsonb; oid integer; cat record; current_qty numeric; suggested numeric; lines integer:=0;
BEGIN
 created:=api.create_purchase_order(p_supplier_id,current_date+COALESCE((SELECT lead_time_days FROM api.proveedores WHERE id=p_supplier_id),0),'PEN',p_actor,'Draft generated from low-stock thresholds');oid:=(created->>'order_id')::integer;
 FOR cat IN SELECT c.*,p.stock_minimo,p.nombre FROM api.supplier_product_catalog c JOIN api.productos p ON p.id=c.product_id WHERE c.supplier_id=p_supplier_id AND c.active AND p.active ORDER BY p.id LOOP
  SELECT COALESCE(sum(stock_actual),0) INTO current_qty FROM api.v_stock_actual WHERE producto_id=cat.product_id;
  suggested:=greatest(cat.minimum_order_quantity,ceil(greatest(cat.stock_minimo-current_qty,0)/cat.unit_factor)*cat.unit_factor);
  IF current_qty<cat.stock_minimo THEN PERFORM api.add_purchase_order_line(oid,cat.product_id,suggested,cat.unit_price,0,0,p_actor);lines:=lines+1; END IF;
 END LOOP;
 IF lines=0 THEN DELETE FROM api.purchase_order_events WHERE order_id=oid;DELETE FROM api.ordenes_compra WHERE id=oid;RAISE EXCEPTION 'No mapped supplier products are below minimum stock'; END IF;
 RETURN jsonb_build_object('ok',true,'order_id',oid,'reference',created->>'reference','line_count',lines);
END $$;

CREATE OR REPLACE FUNCTION api.create_po_inventory_receiving(p_order_id integer,p_warehouse_id integer,p_operator text,p_notes text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE ord api.ordenes_compra%ROWTYPE; created jsonb; sid bigint;
BEGIN
 SELECT * INTO ord FROM api.ordenes_compra WHERE id=p_order_id FOR UPDATE;
 IF ord.id IS NULL OR ord.estado NOT IN('ENVIADA','ABIERTA','PARCIAL') THEN RAISE EXCEPTION 'PO must be ENVIADA, ABIERTA, or PARCIAL'; END IF;
 created:=api.create_inventory_receiving(p_warehouse_id,p_operator,(SELECT nombre FROM api.proveedores WHERE id=ord.proveedor_id),p_notes);sid:=(created->>'session_id')::bigint;
 UPDATE api.inventory_receiving_sessions SET purchase_order_id=ord.id WHERE id=sid;
 RETURN created||jsonb_build_object('purchase_order_id',ord.id,'purchase_order_number',ord.num_ocom);
END $$;

CREATE OR REPLACE FUNCTION api.scan_inventory_receiving(p_session_id bigint,p_barcode text,p_packages numeric DEFAULT 1,p_operator text DEFAULT 'inventory',p_lot_code text DEFAULT NULL,p_expires_on date DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE sess api.inventory_receiving_sessions%ROWTYPE; bc api.product_barcodes%ROWTYPE; rid bigint; clean text; po_line api.ordenes_compra_detalle%ROWTYPE; incoming numeric;
BEGIN
 clean:=trim(COALESCE(p_barcode,''));IF clean='' OR length(clean)>160 OR p_packages<=0 OR p_packages>10000 THEN RAISE EXCEPTION 'Invalid receiving scan';END IF;
 SELECT * INTO sess FROM api.inventory_receiving_sessions WHERE id=p_session_id FOR UPDATE;IF sess.id IS NULL THEN RAISE EXCEPTION 'Receiving session not found';END IF;IF sess.status<>'ACTIVE' THEN RAISE EXCEPTION 'Receiving session is %',sess.status;END IF;
 SELECT * INTO bc FROM api.product_barcodes WHERE barcode=clean;
 IF bc.id IS NULL OR NOT bc.active THEN INSERT INTO api.inventory_receiving_scans(session_id,barcode_id,barcode,product_id,package_quantity,unit_factor,result,operator_name) VALUES(sess.id,bc.id,clean,bc.producto_id,p_packages,COALESCE(bc.unit_factor,1),CASE WHEN bc.id IS NULL THEN 'UNKNOWN_BARCODE' ELSE 'INACTIVE_BARCODE' END,left(COALESCE(p_operator,'inventory'),80)) RETURNING id INTO rid;RETURN jsonb_build_object('ok',false,'reason',CASE WHEN bc.id IS NULL THEN 'UNKNOWN_BARCODE' ELSE 'INACTIVE_BARCODE' END,'scan_id',rid);END IF;
 IF sess.purchase_order_id IS NOT NULL THEN
  SELECT * INTO po_line FROM api.ordenes_compra_detalle WHERE orden_id=sess.purchase_order_id AND producto_id=bc.producto_id AND estado IN('PENDIENTE','PARCIAL') ORDER BY linea LIMIT 1 FOR UPDATE;
  IF po_line.id IS NULL THEN RAISE EXCEPTION 'Scanned product is not pending on this purchase order';END IF;
  SELECT COALESCE(sum(base_quantity),0) INTO incoming FROM api.inventory_receiving_scans WHERE session_id=sess.id AND purchase_order_line_id=po_line.id AND result='ACCEPTED';
  IF po_line.cantidad_recibida+incoming+(p_packages*bc.unit_factor)>po_line.cantidad_pedida THEN RAISE EXCEPTION 'Scan exceeds remaining purchase-order quantity';END IF;
 END IF;
 INSERT INTO api.inventory_receiving_scans(session_id,barcode_id,barcode,product_id,package_quantity,unit_factor,result,operator_name,lot_code,expires_on,purchase_order_line_id,detail) VALUES(sess.id,bc.id,clean,bc.producto_id,p_packages,bc.unit_factor,'ACCEPTED',left(COALESCE(p_operator,'inventory'),80),NULLIF(trim(p_lot_code),''),p_expires_on,po_line.id,jsonb_build_object('barcode_type',bc.barcode_type,'packaging_level',bc.packaging_level,'purchase_order_id',sess.purchase_order_id)) RETURNING id INTO rid;
 RETURN jsonb_build_object('ok',true,'scan_id',rid,'product_id',bc.producto_id,'base_quantity',p_packages*bc.unit_factor,'purchase_order_line_id',po_line.id);
END $$;

CREATE OR REPLACE FUNCTION api.post_inventory_receiving(p_session_id bigint,p_operator text DEFAULT 'inventory')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE sess api.inventory_receiving_sessions%ROWTYPE; scan api.inventory_receiving_scans%ROWTYPE; mid integer;lid integer;receipt_id integer;detail_id integer;receipt_ref text;count_rows integer:=0;total_base numeric:=0;
BEGIN
 SELECT * INTO sess FROM api.inventory_receiving_sessions WHERE id=p_session_id FOR UPDATE;IF sess.id IS NULL THEN RAISE EXCEPTION 'Receiving session not found';END IF;IF sess.status<>'ACTIVE' THEN RAISE EXCEPTION 'Receiving session is %',sess.status;END IF;
 IF NOT EXISTS(SELECT 1 FROM api.inventory_receiving_scans WHERE session_id=sess.id AND result='ACCEPTED') THEN RAISE EXCEPTION 'No accepted scans to post';END IF;
 IF sess.purchase_order_id IS NOT NULL THEN
  IF EXISTS(SELECT 1 FROM api.inventory_receiving_scans WHERE session_id=sess.id AND result='ACCEPTED' AND purchase_order_line_id IS NULL) THEN RAISE EXCEPTION 'Every accepted PO scan must match a purchase-order line';END IF;
  receipt_ref:='REC-PO-'||to_char(clock_timestamp(),'YYYYMMDD-HH24MISS-MS');
  INSERT INTO api.recepciones(num_recepcion,orden_id,almacen_id,estado,observacion) VALUES(receipt_ref,sess.purchase_order_id,sess.warehouse_id,'REGISTRADA','Scanner receiving '||sess.reference) RETURNING id INTO receipt_id;
  FOR scan IN SELECT * FROM api.inventory_receiving_scans WHERE session_id=sess.id AND result='ACCEPTED' ORDER BY id FOR UPDATE LOOP
   INSERT INTO api.recepcion_detalle(recepcion_id,oc_detalle_id,producto_id,almacen_id,lote_codigo,fecha_venc,cantidad_recibida,pack,observacion)
   VALUES(receipt_id,scan.purchase_order_line_id,scan.product_id,sess.warehouse_id,scan.lot_code,scan.expires_on,scan.base_quantity,(SELECT packaging_level FROM api.product_barcodes WHERE id=scan.barcode_id),'Scanner receiving scan '||scan.id) RETURNING id INTO detail_id;
   SELECT id INTO mid FROM api.movimientos_stock WHERE doc_tipo='RECEPCION' AND doc_id=receipt_id AND doc_linea_id=detail_id ORDER BY id DESC LIMIT 1;
   UPDATE api.inventory_receiving_scans SET movement_id=mid WHERE id=scan.id;count_rows:=count_rows+1;total_base:=total_base+scan.base_quantity;
  END LOOP;
 ELSE
  FOR scan IN SELECT * FROM api.inventory_receiving_scans WHERE session_id=sess.id AND result='ACCEPTED' ORDER BY id FOR UPDATE LOOP
   lid:=NULL;IF scan.lot_code IS NOT NULL THEN INSERT INTO api.lotes(producto_id,lote_codigo,fecha_venc,active) VALUES(scan.product_id,scan.lot_code,scan.expires_on,true) ON CONFLICT(producto_id,lote_codigo) DO UPDATE SET fecha_venc=COALESCE(EXCLUDED.fecha_venc,api.lotes.fecha_venc),active=true,updated_at=now() RETURNING id INTO lid;END IF;
   INSERT INTO api.movimientos_stock(fecha_movimiento,movimiento_tipo,almacen_destino_id,producto_id,lote_id,cantidad,doc_tipo,doc_id,doc_linea_id,referencia,observacion) VALUES(now(),'RECEPCION',sess.warehouse_id,scan.product_id,lid,scan.base_quantity,'SCANNER_RECEIVING',sess.id,scan.id,sess.reference,'Scanner receiving by '||left(COALESCE(p_operator,'inventory'),80)) RETURNING id INTO mid;
   UPDATE api.inventory_receiving_scans SET movement_id=mid WHERE id=scan.id;count_rows:=count_rows+1;total_base:=total_base+scan.base_quantity;
  END LOOP;
 END IF;
 UPDATE api.inventory_receiving_sessions SET status='POSTED',posted_at=now(),posted_by=left(COALESCE(p_operator,'inventory'),80),legacy_receipt_id=receipt_id,updated_at=now() WHERE id=sess.id;
 RETURN jsonb_build_object('ok',true,'session_id',sess.id,'status','POSTED','movement_count',count_rows,'base_quantity',total_base,'receipt_id',receipt_id);
END $$;

CREATE OR REPLACE FUNCTION api.refresh_purchase_order_receipts(p_order_id integer) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
BEGIN
 UPDATE api.ordenes_compra_detalle d SET cantidad_recibida=COALESCE((SELECT sum(rd.cantidad_recibida) FROM api.recepcion_detalle rd JOIN api.recepciones r ON r.id=rd.recepcion_id WHERE rd.oc_detalle_id=d.id AND r.estado='REGISTRADA'),0),updated_at=now() WHERE d.orden_id=p_order_id;
 UPDATE api.ordenes_compra_detalle SET estado=CASE WHEN cantidad_recibida>=cantidad_pedida THEN 'CERRADA' WHEN cantidad_recibida>0 THEN 'PARCIAL' ELSE 'PENDIENTE' END WHERE orden_id=p_order_id AND estado<>'ANULADA';
 UPDATE api.ordenes_compra o SET estado=CASE WHEN o.estado='ANULADA' THEN 'ANULADA' WHEN NOT EXISTS(SELECT 1 FROM api.ordenes_compra_detalle d WHERE d.orden_id=o.id AND d.estado<>'CERRADA') THEN 'CERRADA' WHEN EXISTS(SELECT 1 FROM api.ordenes_compra_detalle d WHERE d.orden_id=o.id AND d.cantidad_recibida>0) THEN 'PARCIAL' ELSE 'ENVIADA' END,version=version+1,updated_at=now() WHERE id=p_order_id;
END $$;

CREATE OR REPLACE FUNCTION api.void_inventory_receiving(p_session_id bigint,p_operator text,p_reason text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE sess api.inventory_receiving_sessions%ROWTYPE;scan api.inventory_receiving_scans%ROWTYPE;mid integer;lid integer;count_rows integer:=0;insufficient boolean:=false;
BEGIN
 IF length(trim(COALESCE(p_reason,'')))<5 THEN RAISE EXCEPTION 'Void reason must have at least 5 characters';END IF;
 SELECT * INTO sess FROM api.inventory_receiving_sessions WHERE id=p_session_id FOR UPDATE;IF sess.id IS NULL THEN RAISE EXCEPTION 'Receiving session not found';END IF;IF sess.status='VOIDED' THEN RAISE EXCEPTION 'Receiving session already voided';END IF;
 IF sess.status='POSTED' THEN
  WITH needed AS(SELECT s.product_id,m.lote_id,sum(s.base_quantity) qty FROM api.inventory_receiving_scans s JOIN api.movimientos_stock m ON m.id=s.movement_id WHERE s.session_id=sess.id AND s.result='ACCEPTED' GROUP BY s.product_id,m.lote_id),available AS(SELECT producto_id,lote_id,sum(stock_actual) qty FROM api.v_stock_actual WHERE almacen_id=sess.warehouse_id GROUP BY producto_id,lote_id) SELECT EXISTS(SELECT 1 FROM needed n LEFT JOIN available a ON a.producto_id=n.product_id AND a.lote_id IS NOT DISTINCT FROM n.lote_id WHERE COALESCE(a.qty,0)<n.qty) INTO insufficient;
  IF insufficient THEN RAISE EXCEPTION 'Cannot void receiving: some received stock has already been consumed';END IF;
  FOR scan IN SELECT * FROM api.inventory_receiving_scans WHERE session_id=sess.id AND result='ACCEPTED' AND movement_id IS NOT NULL ORDER BY id FOR UPDATE LOOP
   SELECT lote_id INTO lid FROM api.movimientos_stock WHERE id=scan.movement_id;
   INSERT INTO api.movimientos_stock(fecha_movimiento,movimiento_tipo,almacen_origen_id,producto_id,lote_id,cantidad,doc_tipo,doc_id,doc_linea_id,referencia,observacion) VALUES(now(),'AJUSTE_NEGATIVO',sess.warehouse_id,scan.product_id,lid,scan.base_quantity,'SCANNER_RECEIVING_VOID',sess.id,scan.id,sess.reference,'Receiving void: '||left(trim(p_reason),300)) RETURNING id INTO mid;
   UPDATE api.inventory_receiving_scans SET reversal_movement_id=mid WHERE id=scan.id;count_rows:=count_rows+1;
  END LOOP;
 END IF;
 IF sess.legacy_receipt_id IS NOT NULL THEN UPDATE api.recepciones SET estado='ANULADA',observacion=concat_ws(' | ',observacion,'Voided: '||left(trim(p_reason),300)),updated_at=now() WHERE id=sess.legacy_receipt_id;PERFORM api.refresh_purchase_order_receipts(sess.purchase_order_id);END IF;
 UPDATE api.inventory_receiving_sessions SET status='VOIDED',voided_at=now(),voided_by=left(COALESCE(p_operator,'inventory'),80),void_reason=left(trim(p_reason),500),updated_at=now() WHERE id=sess.id;
 RETURN jsonb_build_object('ok',true,'session_id',sess.id,'status','VOIDED','reversal_count',count_rows);
END $$;

CREATE OR REPLACE VIEW api.v_purchase_order_variance AS
SELECT d.id line_id,d.orden_id,o.num_ocom,o.estado order_status,o.proveedor_id,p.nombre product_name,p.cdg_prod,d.cantidad_pedida,d.cantidad_recibida,(d.cantidad_recibida-d.cantidad_pedida) quantity_variance,d.precio_unitario,
 COALESCE((SELECT c.unit_price FROM api.supplier_product_catalog c WHERE c.supplier_id=o.proveedor_id AND c.product_id=d.producto_id AND c.active ORDER BY c.updated_at DESC LIMIT 1),d.precio_unitario) catalog_price,
 d.precio_unitario-COALESCE((SELECT c.unit_price FROM api.supplier_product_catalog c WHERE c.supplier_id=o.proveedor_id AND c.product_id=d.producto_id AND c.active ORDER BY c.updated_at DESC LIMIT 1),d.precio_unitario) price_variance
FROM api.ordenes_compra_detalle d JOIN api.ordenes_compra o ON o.id=d.orden_id JOIN api.productos p ON p.id=d.producto_id;

GRANT SELECT,INSERT,UPDATE ON api.supplier_product_catalog,api.purchase_order_events TO web_anon;
GRANT USAGE,SELECT ON SEQUENCE api.supplier_product_catalog_id_seq,api.purchase_order_events_id_seq TO web_anon;
GRANT SELECT ON api.v_purchase_order_variance TO web_anon;
GRANT EXECUTE ON FUNCTION api.create_purchase_order(integer,date,text,text,text),api.add_purchase_order_line(integer,integer,numeric,numeric,numeric,numeric,text),api.transition_purchase_order(integer,text,text,integer,text),api.create_low_stock_draft(integer,text),api.create_po_inventory_receiving(integer,integer,text,text),api.scan_inventory_receiving(bigint,text,numeric,text,text,date),api.post_inventory_receiving(bigint,text),api.refresh_purchase_order_receipts(integer),api.void_inventory_receiving(bigint,text,text) TO web_anon;
NOTIFY pgrst,'reload schema';
COMMIT;
