BEGIN;

CREATE TABLE IF NOT EXISTS api.ingredientes_costeo(
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nombre text NOT NULL UNIQUE,
 proveedor_id integer REFERENCES api.proveedores(id) ON DELETE SET NULL,
 costo_kg numeric(14,4) NOT NULL CHECK(costo_kg>0),
 moneda text NOT NULL DEFAULT 'PEN' CHECK(moneda IN('PEN','USD','EUR')),
 stk_in numeric(14,3) NOT NULL DEFAULT 0 CHECK(stk_in>=0),
 stk_out numeric(14,3) NOT NULL DEFAULT 0 CHECK(stk_out>=0),
 stk_act numeric(14,3) GENERATED ALWAYS AS(stk_in-stk_out) STORED,
 active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE api.ingredientes_costeo ADD COLUMN IF NOT EXISTS sku text;
ALTER TABLE api.ingredientes_costeo ADD COLUMN IF NOT EXISTS base_unit text NOT NULL DEFAULT 'KG';
ALTER TABLE api.ingredientes_costeo ADD COLUMN IF NOT EXISTS stock_minimo numeric(14,3) NOT NULL DEFAULT 0;
ALTER TABLE api.ingredientes_costeo ADD COLUMN IF NOT EXISTS inventory_enforced boolean NOT NULL DEFAULT false;
DO $$ BEGIN ALTER TABLE api.ingredientes_costeo ADD CONSTRAINT ingredientes_inventory_values CHECK(base_unit='KG' AND stock_minimo>=0);EXCEPTION WHEN duplicate_object THEN NULL;END $$;
CREATE UNIQUE INDEX IF NOT EXISTS ingredientes_costeo_sku_unique ON api.ingredientes_costeo(sku) WHERE sku IS NOT NULL;

CREATE TABLE IF NOT EXISTS api.recetas_costeo(
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 producto_id integer REFERENCES api.productos(id) ON DELETE SET NULL,
 nombre text NOT NULL,rendimiento_unidades numeric(14,3) NOT NULL DEFAULT 1 CHECK(rendimiento_unidades>0),
 active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS api.receta_ingredientes_costeo(
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,receta_id integer NOT NULL REFERENCES api.recetas_costeo(id) ON DELETE CASCADE,
 ingrediente_id integer NOT NULL REFERENCES api.ingredientes_costeo(id) ON DELETE RESTRICT,cantidad_g numeric(14,3) NOT NULL CHECK(cantidad_g>0),
 created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT receta_ingrediente_unique UNIQUE(receta_id,ingrediente_id)
);

CREATE TABLE IF NOT EXISTS api.ingredient_lots(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,ingredient_id integer NOT NULL REFERENCES api.ingredientes_costeo(id) ON DELETE RESTRICT,
 warehouse_id integer NOT NULL REFERENCES api.almacenes(id) ON DELETE RESTRICT,lot_code text NOT NULL,expires_on date,supplier_id integer REFERENCES api.proveedores(id) ON DELETE SET NULL,
 active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ingredient_lot_unique UNIQUE(ingredient_id,warehouse_id,lot_code)
);

CREATE TABLE IF NOT EXISTS api.ingredient_stock_movements(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,movement_at timestamptz NOT NULL DEFAULT now(),movement_type text NOT NULL CHECK(movement_type IN('RECEIPT','CONSUMPTION','WASTE','ADJUST_POSITIVE','ADJUST_NEGATIVE','RETURN')),
 warehouse_id integer NOT NULL REFERENCES api.almacenes(id) ON DELETE RESTRICT,ingredient_id integer NOT NULL REFERENCES api.ingredientes_costeo(id) ON DELETE RESTRICT,
 lot_id bigint REFERENCES api.ingredient_lots(id) ON DELETE RESTRICT,quantity_kg numeric(14,3) NOT NULL CHECK(quantity_kg>0),unit_cost numeric(14,4),currency char(3) NOT NULL DEFAULT 'PEN' CHECK(currency IN('PEN','USD','EUR')),
 doc_type text,doc_id bigint,doc_line_id bigint,reference text,reason_code text,reason text NOT NULL,actor text NOT NULL,created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ingredient_movements_stock_idx ON api.ingredient_stock_movements(warehouse_id,ingredient_id,movement_at);
CREATE INDEX IF NOT EXISTS ingredient_movements_doc_idx ON api.ingredient_stock_movements(doc_type,doc_id);

CREATE OR REPLACE FUNCTION api.reject_ingredient_movement_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Ingredient stock movements are append-only';END $$;
DROP TRIGGER IF EXISTS ingredient_movements_append_only ON api.ingredient_stock_movements;
CREATE TRIGGER ingredient_movements_append_only BEFORE UPDATE OR DELETE ON api.ingredient_stock_movements FOR EACH ROW EXECUTE FUNCTION api.reject_ingredient_movement_mutation();

DROP TRIGGER IF EXISTS set_updated_at_ingredientes_costeo ON api.ingredientes_costeo;
CREATE TRIGGER set_updated_at_ingredientes_costeo BEFORE UPDATE ON api.ingredientes_costeo FOR EACH ROW EXECUTE FUNCTION api.set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at_recetas_costeo ON api.recetas_costeo;
CREATE TRIGGER set_updated_at_recetas_costeo BEFORE UPDATE ON api.recetas_costeo FOR EACH ROW EXECUTE FUNCTION api.set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at_receta_ingredientes_costeo ON api.receta_ingredientes_costeo;
CREATE TRIGGER set_updated_at_receta_ingredientes_costeo BEFORE UPDATE ON api.receta_ingredientes_costeo FOR EACH ROW EXECUTE FUNCTION api.set_updated_at();
DROP TRIGGER IF EXISTS set_updated_at_ingredient_lots ON api.ingredient_lots;
CREATE TRIGGER set_updated_at_ingredient_lots BEFORE UPDATE ON api.ingredient_lots FOR EACH ROW EXECUTE FUNCTION api.set_updated_at();

CREATE OR REPLACE VIEW api.v_ingredient_stock AS
SELECT a.id warehouse_id,a.codigo warehouse_code,a.nombre warehouse_name,i.id ingredient_id,i.sku,i.nombre ingredient_name,i.base_unit,i.stock_minimo,i.inventory_enforced,
 COALESCE(sum(CASE WHEN m.movement_type IN('RECEIPT','ADJUST_POSITIVE','RETURN') THEN m.quantity_kg ELSE -m.quantity_kg END),0)::numeric(14,3) stock_kg,
 COALESCE(sum(m.quantity_kg) FILTER(WHERE m.movement_type='WASTE'),0)::numeric(14,3) waste_kg,
 COALESCE(sum(m.quantity_kg) FILTER(WHERE m.movement_type='CONSUMPTION'),0)::numeric(14,3) consumed_kg
FROM api.almacenes a CROSS JOIN api.ingredientes_costeo i LEFT JOIN api.ingredient_stock_movements m ON m.warehouse_id=a.id AND m.ingredient_id=i.id
WHERE a.active AND i.active GROUP BY a.id,a.codigo,a.nombre,i.id,i.sku,i.nombre,i.base_unit,i.stock_minimo,i.inventory_enforced;

CREATE OR REPLACE VIEW api.v_ingredient_inventory_summary AS
SELECT i.id,i.nombre,i.proveedor_id,i.costo_kg,i.moneda,i.sku,i.base_unit,i.stock_minimo,i.inventory_enforced,i.active,i.created_at,i.updated_at,
 COALESCE(sum(m.quantity_kg) FILTER(WHERE m.movement_type IN('RECEIPT','ADJUST_POSITIVE','RETURN')),0)::numeric(14,3) stk_in,
 COALESCE(sum(m.quantity_kg) FILTER(WHERE m.movement_type IN('CONSUMPTION','WASTE','ADJUST_NEGATIVE')),0)::numeric(14,3) stk_out,
 COALESCE(sum(CASE WHEN m.movement_type IN('RECEIPT','ADJUST_POSITIVE','RETURN') THEN m.quantity_kg ELSE -m.quantity_kg END),0)::numeric(14,3) stk_act
FROM api.ingredientes_costeo i LEFT JOIN api.ingredient_stock_movements m ON m.ingredient_id=i.id GROUP BY i.id;

CREATE OR REPLACE VIEW api.v_receta_costos AS
SELECT r.id receta_id,r.producto_id,p.cdg_prod,COALESCE(p.nombre,r.nombre) producto_nombre,r.nombre receta_nombre,r.rendimiento_unidades,
 COALESCE(sum((ri.cantidad_g/1000.0)*i.costo_kg),0)::numeric(14,4) costo_total,
 (COALESCE(sum((ri.cantidad_g/1000.0)*i.costo_kg),0)/r.rendimiento_unidades)::numeric(14,4) costo_por_unidad,count(ri.id)::integer ingredientes_count
FROM api.recetas_costeo r LEFT JOIN api.productos p ON p.id=r.producto_id LEFT JOIN api.receta_ingredientes_costeo ri ON ri.receta_id=r.id LEFT JOIN api.ingredientes_costeo i ON i.id=ri.ingrediente_id
GROUP BY r.id,r.producto_id,p.cdg_prod,p.nombre,r.nombre,r.rendimiento_unidades;

CREATE OR REPLACE VIEW api.v_receta_ingredientes_costeo AS
SELECT ri.id,ri.receta_id,r.nombre receta_nombre,ri.ingrediente_id,i.nombre ingrediente_nombre,i.proveedor_id,pr.nombre proveedor_nombre,ri.cantidad_g,i.costo_kg,
 ((ri.cantidad_g/1000.0)*i.costo_kg)::numeric(14,4) costo_linea,s.stk_in,s.stk_out,s.stk_act
FROM api.receta_ingredientes_costeo ri JOIN api.recetas_costeo r ON r.id=ri.receta_id JOIN api.ingredientes_costeo i ON i.id=ri.ingrediente_id
LEFT JOIN api.proveedores pr ON pr.id=i.proveedor_id LEFT JOIN api.v_ingredient_inventory_summary s ON s.id=i.id;

CREATE OR REPLACE FUNCTION api.ingredient_stock_quantity(p_warehouse_id integer,p_ingredient_id integer)
RETURNS numeric LANGUAGE sql STABLE SECURITY DEFINER SET search_path=api,public AS $$
 SELECT COALESCE((SELECT stock_kg FROM api.v_ingredient_stock WHERE warehouse_id=p_warehouse_id AND ingredient_id=p_ingredient_id),0)::numeric
$$;

CREATE OR REPLACE FUNCTION api.post_ingredient_movement(p_ingredient_id integer,p_warehouse_id integer,p_movement_type text,p_quantity_kg numeric,p_actor text,p_reason text,p_reason_code text DEFAULT NULL,p_unit_cost numeric DEFAULT NULL,p_currency text DEFAULT 'PEN',p_supplier_id integer DEFAULT NULL,p_lot_code text DEFAULT NULL,p_expires_on date DEFAULT NULL,p_doc_type text DEFAULT NULL,p_doc_id bigint DEFAULT NULL,p_doc_line_id bigint DEFAULT NULL,p_reference text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE ing api.ingredientes_costeo%ROWTYPE;kind text:=upper(trim(p_movement_type));lot_id bigint;movement_id bigint;current_qty numeric;new_cost numeric;
BEGIN
 IF kind NOT IN('RECEIPT','CONSUMPTION','WASTE','ADJUST_POSITIVE','ADJUST_NEGATIVE','RETURN') THEN RAISE EXCEPTION 'Invalid ingredient movement type';END IF;
 IF p_quantity_kg<=0 OR length(trim(COALESCE(p_actor,'')))<2 OR length(trim(COALESCE(p_reason,'')))<5 THEN RAISE EXCEPTION 'Quantity, actor, and reason are required';END IF;
 IF upper(p_currency) NOT IN('PEN','USD','EUR') OR COALESCE(p_unit_cost,0)<0 THEN RAISE EXCEPTION 'Invalid ingredient movement cost';END IF;
 SELECT * INTO ing FROM api.ingredientes_costeo WHERE id=p_ingredient_id AND active FOR UPDATE;IF ing.id IS NULL THEN RAISE EXCEPTION 'Active ingredient not found';END IF;
 IF NOT EXISTS(SELECT 1 FROM api.almacenes WHERE id=p_warehouse_id AND active) THEN RAISE EXCEPTION 'Active warehouse not found';END IF;
 PERFORM pg_advisory_xact_lock(p_warehouse_id,p_ingredient_id);current_qty:=api.ingredient_stock_quantity(p_warehouse_id,p_ingredient_id);
 IF kind IN('CONSUMPTION','WASTE','ADJUST_NEGATIVE') AND ing.inventory_enforced AND current_qty<p_quantity_kg THEN RAISE EXCEPTION 'Insufficient ingredient stock: required %, available %',p_quantity_kg,current_qty;END IF;
 IF NULLIF(trim(COALESCE(p_lot_code,'')),'') IS NOT NULL THEN
  INSERT INTO api.ingredient_lots(ingredient_id,warehouse_id,lot_code,expires_on,supplier_id) VALUES(ing.id,p_warehouse_id,trim(p_lot_code),p_expires_on,p_supplier_id)
  ON CONFLICT(ingredient_id,warehouse_id,lot_code) DO UPDATE SET expires_on=COALESCE(EXCLUDED.expires_on,api.ingredient_lots.expires_on),supplier_id=COALESCE(EXCLUDED.supplier_id,api.ingredient_lots.supplier_id),active=true,updated_at=now() RETURNING id INTO lot_id;
 END IF;
 INSERT INTO api.ingredient_stock_movements(movement_type,warehouse_id,ingredient_id,lot_id,quantity_kg,unit_cost,currency,doc_type,doc_id,doc_line_id,reference,reason_code,reason,actor)
 VALUES(kind,p_warehouse_id,ing.id,lot_id,round(p_quantity_kg,3),p_unit_cost,upper(p_currency),NULLIF(trim(p_doc_type),''),p_doc_id,p_doc_line_id,NULLIF(trim(p_reference),''),NULLIF(trim(p_reason_code),''),left(trim(p_reason),500),left(trim(p_actor),80)) RETURNING id INTO movement_id;
 IF kind='RECEIPT' AND p_unit_cost IS NOT NULL THEN
  new_cost:=((greatest(current_qty,0)*ing.costo_kg)+(p_quantity_kg*p_unit_cost))/(greatest(current_qty,0)+p_quantity_kg);
  UPDATE api.ingredientes_costeo SET costo_kg=round(new_cost,4),proveedor_id=COALESCE(p_supplier_id,proveedor_id),moneda=upper(p_currency),updated_at=now() WHERE id=ing.id;
 END IF;
 RETURN jsonb_build_object('ok',true,'movement_id',movement_id,'ingredient_id',ing.id,'movement_type',kind,'quantity_kg',p_quantity_kg,'previous_stock_kg',current_qty,'stock_kg',api.ingredient_stock_quantity(p_warehouse_id,ing.id),'lot_id',lot_id);
END $$;

CREATE OR REPLACE FUNCTION api.post_ingredient_receipt(p_ingredient_id integer,p_warehouse_id integer,p_quantity_kg numeric,p_unit_cost numeric,p_currency text,p_supplier_id integer,p_actor text,p_reason text,p_lot_code text DEFAULT NULL,p_expires_on date DEFAULT NULL,p_reference text DEFAULT NULL)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=api,public AS $$
 SELECT api.post_ingredient_movement(p_ingredient_id,p_warehouse_id,'RECEIPT',p_quantity_kg,p_actor,p_reason,'PURCHASE_RECEIPT',p_unit_cost,p_currency,p_supplier_id,p_lot_code,p_expires_on,'INGREDIENT_RECEIPT',NULL,NULL,p_reference)
$$;

CREATE OR REPLACE FUNCTION api.post_ingredient_waste(p_ingredient_id integer,p_warehouse_id integer,p_quantity_kg numeric,p_actor text,p_reason_code text,p_reason text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
BEGIN
 IF upper(trim(COALESCE(p_reason_code,''))) NOT IN('SPOILAGE','PREP_LOSS','DAMAGE','EXPIRED','QUALITY','OTHER') THEN RAISE EXCEPTION 'Invalid waste reason code';END IF;
 RETURN api.post_ingredient_movement(p_ingredient_id,p_warehouse_id,'WASTE',p_quantity_kg,p_actor,p_reason,upper(trim(p_reason_code)),NULL,'PEN',NULL,NULL,NULL,'INGREDIENT_WASTE',NULL,NULL,NULL);
END $$;

INSERT INTO api.ingredient_stock_movements(movement_type,warehouse_id,ingredient_id,quantity_kg,unit_cost,currency,doc_type,reference,reason,actor)
SELECT 'ADJUST_POSITIVE',api.get_default_almacen_id(),i.id,i.stk_in,i.costo_kg,i.moneda,'LEGACY_INGREDIENT_BALANCE','LEGACY-'||i.id,'Legacy stk_in migration','migration'
FROM api.ingredientes_costeo i WHERE i.stk_in>0 AND NOT EXISTS(SELECT 1 FROM api.ingredient_stock_movements m WHERE m.doc_type='LEGACY_INGREDIENT_BALANCE' AND m.ingredient_id=i.id);
INSERT INTO api.ingredient_stock_movements(movement_type,warehouse_id,ingredient_id,quantity_kg,unit_cost,currency,doc_type,reference,reason,actor)
SELECT 'ADJUST_NEGATIVE',api.get_default_almacen_id(),i.id,i.stk_out,i.costo_kg,i.moneda,'LEGACY_INGREDIENT_BALANCE','LEGACY-'||i.id,'Legacy stk_out migration','migration'
FROM api.ingredientes_costeo i WHERE i.stk_out>0 AND NOT EXISTS(SELECT 1 FROM api.ingredient_stock_movements m WHERE m.doc_type='LEGACY_INGREDIENT_BALANCE' AND m.ingredient_id=i.id AND m.movement_type='ADJUST_NEGATIVE');
UPDATE api.ingredientes_costeo SET stk_in=0,stk_out=0 WHERE stk_in<>0 OR stk_out<>0;
DO $$ BEGIN ALTER TABLE api.ingredientes_costeo ADD CONSTRAINT ingredientes_legacy_counters_zero CHECK(stk_in=0 AND stk_out=0);EXCEPTION WHEN duplicate_object THEN NULL;END $$;

GRANT SELECT,INSERT,UPDATE,DELETE ON api.ingredientes_costeo,api.recetas_costeo,api.receta_ingredientes_costeo TO web_anon;
GRANT SELECT ON api.ingredient_lots,api.ingredient_stock_movements,api.v_ingredient_stock,api.v_ingredient_inventory_summary,api.v_receta_costos,api.v_receta_ingredientes_costeo TO web_anon;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA api TO web_anon;
GRANT EXECUTE ON FUNCTION api.ingredient_stock_quantity(integer,integer),api.post_ingredient_movement(integer,integer,text,numeric,text,text,text,numeric,text,integer,text,date,text,bigint,bigint,text),api.post_ingredient_receipt(integer,integer,numeric,numeric,text,integer,text,text,text,date,text),api.post_ingredient_waste(integer,integer,numeric,text,text,text) TO web_anon;

NOTIFY pgrst,'reload schema';
COMMIT;
