BEGIN;

CREATE TABLE IF NOT EXISTS api.inventory_stock_controls(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 warehouse_id integer NOT NULL REFERENCES api.almacenes(id) ON DELETE RESTRICT,
 product_id integer NOT NULL REFERENCES api.productos(id) ON DELETE RESTRICT,
 enforcement_enabled boolean NOT NULL DEFAULT false,
 safety_stock numeric(14,3) NOT NULL DEFAULT 0 CHECK(safety_stock>=0),
 reservation_ttl_minutes integer NOT NULL DEFAULT 120 CHECK(reservation_ttl_minutes BETWEEN 15 AND 10080),
 configured_by text NOT NULL,
 notes text,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT inventory_stock_control_unique UNIQUE(warehouse_id,product_id)
);

CREATE TABLE IF NOT EXISTS api.inventory_stock_control_events(
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 control_id bigint NOT NULL REFERENCES api.inventory_stock_controls(id) ON DELETE RESTRICT,
 event_type text NOT NULL,
 actor text NOT NULL,
 details jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE api.stock_reservas ADD COLUMN IF NOT EXISTS expires_at timestamptz;
ALTER TABLE api.stock_reservas ADD COLUMN IF NOT EXISTS expired_at timestamptz;
ALTER TABLE api.stock_reservas ADD COLUMN IF NOT EXISTS expired_by text;
CREATE INDEX IF NOT EXISTS stock_reservas_expiry_idx ON api.stock_reservas(expires_at) WHERE estado='RESERVADA';

UPDATE api.stock_reservas SET expires_at=reserved_at+interval '120 minutes'
WHERE estado='RESERVADA' AND expires_at IS NULL;

CREATE OR REPLACE FUNCTION api.inventory_available_to_promise(p_warehouse_id integer,p_product_id integer,p_exclude_reservation_id integer DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=api,public AS $$
DECLARE control_row api.inventory_stock_controls%ROWTYPE; actual_qty numeric; reserved_qty numeric; available_qty numeric;
BEGIN
 SELECT * INTO control_row FROM api.inventory_stock_controls WHERE warehouse_id=p_warehouse_id AND product_id=p_product_id;
 actual_qty:=api.inventory_product_quantity(p_warehouse_id,p_product_id);
 SELECT COALESCE(sum(cantidad_base),0) INTO reserved_qty FROM api.stock_reservas
 WHERE almacen_id=p_warehouse_id AND producto_id=p_product_id AND estado='RESERVADA' AND (p_exclude_reservation_id IS NULL OR id<>p_exclude_reservation_id);
 available_qty:=actual_qty-reserved_qty-COALESCE(control_row.safety_stock,0);
 RETURN jsonb_build_object('warehouse_id',p_warehouse_id,'product_id',p_product_id,'enforcement_enabled',COALESCE(control_row.enforcement_enabled,false),'actual_quantity',actual_qty,'reserved_quantity',reserved_qty,'safety_stock',COALESCE(control_row.safety_stock,0),'available_quantity',available_qty,'reservation_ttl_minutes',COALESCE(control_row.reservation_ttl_minutes,120));
END $$;

CREATE OR REPLACE FUNCTION api.assert_inventory_availability(p_warehouse_id integer,p_product_id integer,p_required_quantity numeric,p_exclude_reservation_id integer DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE availability jsonb;
BEGIN
 IF p_required_quantity<=0 THEN RAISE EXCEPTION 'Required stock quantity must be positive';END IF;
 PERFORM pg_advisory_xact_lock(p_warehouse_id,p_product_id);
 availability:=api.inventory_available_to_promise(p_warehouse_id,p_product_id,p_exclude_reservation_id);
 IF COALESCE((availability->>'enforcement_enabled')::boolean,false) AND (availability->>'available_quantity')::numeric<p_required_quantity THEN
  RAISE EXCEPTION 'Insufficient available stock for product %: required %, available %',p_product_id,p_required_quantity,availability->>'available_quantity';
 END IF;
 RETURN availability||jsonb_build_object('required_quantity',p_required_quantity,'allowed',true);
END $$;

CREATE OR REPLACE FUNCTION api.configure_inventory_stock_control(p_warehouse_id integer,p_product_id integer,p_enabled boolean,p_safety_stock numeric,p_ttl_minutes integer,p_actor text,p_notes text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE cid bigint; previous api.inventory_stock_controls%ROWTYPE;
BEGIN
 IF NOT EXISTS(SELECT 1 FROM api.almacenes WHERE id=p_warehouse_id AND active) THEN RAISE EXCEPTION 'Active warehouse not found';END IF;
 IF NOT EXISTS(SELECT 1 FROM api.productos WHERE id=p_product_id AND active) THEN RAISE EXCEPTION 'Active product not found';END IF;
 IF p_safety_stock<0 OR p_ttl_minutes NOT BETWEEN 15 AND 10080 THEN RAISE EXCEPTION 'Invalid stock-control values';END IF;
 IF length(trim(COALESCE(p_actor,'')))<2 THEN RAISE EXCEPTION 'Actor is required';END IF;
 IF p_enabled AND NOT EXISTS(
  SELECT 1 FROM api.inventory_count_sessions s JOIN api.inventory_count_lines l ON l.session_id=s.id
  WHERE s.warehouse_id=p_warehouse_id AND l.product_id=p_product_id AND s.status='POSTED' AND l.actual_quantity IS NOT NULL AND s.posted_at>=now()-interval '30 days'
 ) THEN RAISE EXCEPTION 'A posted physical count from the last 30 days is required before enforcement';END IF;
 SELECT * INTO previous FROM api.inventory_stock_controls WHERE warehouse_id=p_warehouse_id AND product_id=p_product_id FOR UPDATE;
 INSERT INTO api.inventory_stock_controls(warehouse_id,product_id,enforcement_enabled,safety_stock,reservation_ttl_minutes,configured_by,notes)
 VALUES(p_warehouse_id,p_product_id,p_enabled,p_safety_stock,p_ttl_minutes,left(trim(p_actor),80),NULLIF(trim(p_notes),''))
 ON CONFLICT(warehouse_id,product_id) DO UPDATE SET enforcement_enabled=EXCLUDED.enforcement_enabled,safety_stock=EXCLUDED.safety_stock,reservation_ttl_minutes=EXCLUDED.reservation_ttl_minutes,configured_by=EXCLUDED.configured_by,notes=EXCLUDED.notes,updated_at=now()
 RETURNING id INTO cid;
 INSERT INTO api.inventory_stock_control_events(control_id,event_type,actor,details)
 VALUES(cid,'CONFIGURED',left(trim(p_actor),80),jsonb_build_object('previous_enabled',previous.enforcement_enabled,'enabled',p_enabled,'safety_stock',p_safety_stock,'reservation_ttl_minutes',p_ttl_minutes,'notes',p_notes));
 RETURN api.inventory_available_to_promise(p_warehouse_id,p_product_id,NULL)||jsonb_build_object('ok',true,'control_id',cid);
END $$;

CREATE OR REPLACE FUNCTION api.reservar_stock_pedido_item(p_pedido_item_id integer)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE v_item record;v_factor numeric(14,3);v_cantidad_base numeric(14,3);v_almacen_id integer;v_existing api.stock_reservas%ROWTYPE;v_availability jsonb;v_ttl integer;
BEGIN
 SELECT pi.id,pi.pedido_id,pi.producto_id,pi.producto_texto,pi.cantidad,pi.unidad,p.estado AS pedido_estado INTO v_item
 FROM api.pedido_items pi JOIN api.pedidos p ON p.id=pi.pedido_id WHERE pi.id=p_pedido_item_id;
 IF v_item.id IS NULL THEN RETURN jsonb_build_object('ok',false,'error','pedido_item not found','pedido_item_id',p_pedido_item_id);END IF;
 IF v_item.producto_id IS NULL THEN RETURN jsonb_build_object('ok',false,'error','pedido_item has no producto_id','pedido_item_id',p_pedido_item_id);END IF;
 IF v_item.pedido_estado NOT IN('CONFIRMADO','EN_PREPARACION','DESPACHADO') THEN RETURN jsonb_build_object('ok',false,'skipped',true,'reason','pedido status does not reserve stock','estado',v_item.pedido_estado);END IF;
 v_factor:=api.get_producto_factor(v_item.producto_id,v_item.unidad);v_cantidad_base:=round((v_item.cantidad*v_factor)::numeric,3);v_almacen_id:=api.get_default_almacen_id();
 SELECT * INTO v_existing FROM api.stock_reservas WHERE pedido_item_id=p_pedido_item_id FOR UPDATE;
 IF v_existing.id IS NOT NULL AND v_existing.estado IN('RESERVADA','CONSUMIDA') THEN RETURN jsonb_build_object('ok',true,'already_exists',true,'reserva_id',v_existing.id,'estado',v_existing.estado);END IF;
 v_availability:=api.assert_inventory_availability(v_almacen_id,v_item.producto_id,v_cantidad_base,v_existing.id);v_ttl:=COALESCE((v_availability->>'reservation_ttl_minutes')::integer,120);
 IF v_existing.id IS NOT NULL THEN
  UPDATE api.stock_reservas SET estado='RESERVADA',cantidad=v_item.cantidad,unidad=v_item.unidad,factor=v_factor,cantidad_base=v_cantidad_base,almacen_id=v_almacen_id,reserved_at=now(),released_at=NULL,expired_at=NULL,expired_by=NULL,expires_at=now()+make_interval(mins=>v_ttl),observacion='Reserva reactivada al avanzar el pedido',updated_at=now() WHERE id=v_existing.id;
  RETURN jsonb_build_object('ok',true,'reactivated',true,'reserva_id',v_existing.id,'cantidad_base',v_cantidad_base,'expires_at',now()+make_interval(mins=>v_ttl),'availability',v_availability);
 END IF;
 INSERT INTO api.stock_reservas(pedido_id,pedido_item_id,producto_id,almacen_id,cantidad,unidad,factor,cantidad_base,estado,expires_at,observacion)
 VALUES(v_item.pedido_id,v_item.id,v_item.producto_id,v_almacen_id,v_item.cantidad,v_item.unidad,v_factor,v_cantidad_base,'RESERVADA',now()+make_interval(mins=>v_ttl),'Reserva automática por pedido') RETURNING * INTO v_existing;
 RETURN jsonb_build_object('ok',true,'reserva_id',v_existing.id,'pedido_id',v_item.pedido_id,'pedido_item_id',v_item.id,'producto_id',v_item.producto_id,'cantidad_base',v_cantidad_base,'almacen_id',v_almacen_id,'expires_at',v_existing.expires_at,'availability',v_availability);
END $$;

CREATE OR REPLACE FUNCTION api.expire_stale_stock_reservations(p_now timestamptz DEFAULT now(),p_actor text DEFAULT 'reservation-expiry',p_dry_run boolean DEFAULT true)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE candidate record;candidate_count integer:=0;released_count integer:=0;order_ids jsonb:='[]'::jsonb;
BEGIN
 FOR candidate IN
  SELECT sr.id,sr.pedido_id FROM api.stock_reservas sr JOIN api.pedidos p ON p.id=sr.pedido_id
  WHERE sr.estado='RESERVADA' AND sr.expires_at IS NOT NULL AND sr.expires_at<=p_now AND p.estado='CONFIRMADO'
    AND COALESCE(p.payment_status,'PENDING')<>'PAID_VERIFIED'
    AND NOT EXISTS(SELECT 1 FROM api.picking_sessions ps WHERE ps.pedido_id=p.id AND ps.status IN('ACTIVE','COMPLETED'))
  ORDER BY sr.id FOR UPDATE OF sr
 LOOP
  candidate_count:=candidate_count+1;order_ids:=order_ids||jsonb_build_array(candidate.pedido_id);
  IF NOT p_dry_run THEN
   UPDATE api.stock_reservas SET estado='LIBERADA',released_at=now(),expired_at=now(),expired_by=left(COALESCE(p_actor,'reservation-expiry'),80),observacion='Reserva vencida; se revalidará antes de preparación',updated_at=now() WHERE id=candidate.id;
   released_count:=released_count+1;
  END IF;
 END LOOP;
 RETURN jsonb_build_object('ok',true,'dry_run',p_dry_run,'candidate_count',candidate_count,'released_count',released_count,'order_ids',(SELECT COALESCE(jsonb_agg(DISTINCT value),'[]'::jsonb) FROM jsonb_array_elements(order_ids)));
END $$;

CREATE OR REPLACE VIEW api.v_inventory_availability AS
SELECT c.id control_id,c.warehouse_id,a.codigo warehouse_code,a.nombre warehouse_name,c.product_id,p.cdg_prod,p.nombre product_name,c.enforcement_enabled,c.safety_stock,c.reservation_ttl_minutes,
 api.inventory_product_quantity(c.warehouse_id,c.product_id) stock_actual,api.inventory_product_reserved(c.warehouse_id,c.product_id) stock_reserved,
 api.inventory_product_quantity(c.warehouse_id,c.product_id)-api.inventory_product_reserved(c.warehouse_id,c.product_id)-c.safety_stock available_to_promise,c.configured_by,c.notes,c.updated_at
FROM api.inventory_stock_controls c JOIN api.almacenes a ON a.id=c.warehouse_id JOIN api.productos p ON p.id=c.product_id;

CREATE OR REPLACE VIEW api.v_expiring_stock_reservations AS
SELECT sr.id reservation_id,sr.pedido_id,p.pedido_num,p.estado order_status,p.payment_status,sr.producto_id,pr.cdg_prod,pr.nombre product_name,sr.cantidad_base,sr.reserved_at,sr.expires_at,
 (sr.expires_at<=now() AND p.estado='CONFIRMADO' AND COALESCE(p.payment_status,'PENDING')<>'PAID_VERIFIED') eligible_for_expiry
FROM api.stock_reservas sr JOIN api.pedidos p ON p.id=sr.pedido_id JOIN api.productos pr ON pr.id=sr.producto_id WHERE sr.estado='RESERVADA';

GRANT SELECT ON api.inventory_stock_controls,api.inventory_stock_control_events,api.v_inventory_availability,api.v_expiring_stock_reservations TO web_anon;
GRANT USAGE,SELECT ON SEQUENCE api.inventory_stock_controls_id_seq,api.inventory_stock_control_events_id_seq TO web_anon;
GRANT EXECUTE ON FUNCTION api.inventory_available_to_promise(integer,integer,integer),api.assert_inventory_availability(integer,integer,numeric,integer),api.configure_inventory_stock_control(integer,integer,boolean,numeric,integer,text,text),api.reservar_stock_pedido_item(integer),api.expire_stale_stock_reservations(timestamptz,text,boolean) TO web_anon;

NOTIFY pgrst,'reload schema';
COMMIT;
