BEGIN;

-- =========================================================
-- WHATSAPP ORDERS MODULE FOR POSTGREST
-- Development script:
-- Drops/recreates only WhatsApp/order-specific objects.
-- Does NOT drop your inventory / receiving tables.
-- =========================================================


-- =========================================================
-- 0. BASIC REQUIREMENTS
-- =========================================================

CREATE SCHEMA IF NOT EXISTS api;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'web_anon') THEN
        CREATE ROLE web_anon NOLOGIN;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticator') THEN
        CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD 'soinfo';
    END IF;
END $$;

GRANT web_anon TO authenticator;
GRANT USAGE ON SCHEMA api TO web_anon;


-- Recreate set_updated_at if it does not exist.
CREATE OR REPLACE FUNCTION api.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


-- =========================================================
-- 1. DROP WHATSAPP MODULE OBJECTS ONLY
-- =========================================================

DROP VIEW IF EXISTS api.v_whatsapp_conversaciones CASCADE;
DROP VIEW IF EXISTS api.v_pedido_items_logistica CASCADE;
DROP VIEW IF EXISTS api.v_pedidos_logistica CASCADE;

DROP FUNCTION IF EXISTS api.confirmar_pedido_whatsapp(
    text,
    text,
    text,
    numeric,
    numeric,
    text,
    text,
    jsonb,
    text,
    numeric,
    text
) CASCADE;

DROP FUNCTION IF EXISTS api.registrar_whatsapp_mensaje(
    text,
    text,
    text,
    text,
    numeric,
    numeric,
    jsonb
) CASCADE;

DROP TABLE IF EXISTS api.email_logistica_log CASCADE;
DROP TABLE IF EXISTS api.whatsapp_mensajes CASCADE;
DROP TABLE IF EXISTS api.whatsapp_conversaciones CASCADE;
DROP TABLE IF EXISTS api.pedido_direcciones CASCADE;
DROP TABLE IF EXISTS api.pedido_items CASCADE;
DROP TABLE IF EXISTS api.pedidos CASCADE;
DROP TABLE IF EXISTS api.producto_precios CASCADE;
DROP TABLE IF EXISTS api.clientes_whatsapp CASCADE;

DROP SEQUENCE IF EXISTS api.pedido_num_seq CASCADE;


-- =========================================================
-- 2. SEQUENCE FOR ORDER NUMBERS
-- =========================================================

CREATE SEQUENCE api.pedido_num_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


-- =========================================================
-- 3. CUSTOMERS FROM WHATSAPP
-- =========================================================

CREATE TABLE api.clientes_whatsapp (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whatsapp_number text NOT NULL UNIQUE,
    nombre text,
    email text,
    active boolean NOT NULL DEFAULT true,
    last_order_at timestamptz,
    last_order_id integer,
    last_order_num text,
    last_order_total numeric(14,2),
    last_payment_method text,
    last_latitude numeric(12,8),
    last_longitude numeric(12,8),
    last_maps_url text,
    last_written_address text,
    last_detected_address text,
    last_confirmed_address text,
    last_order_snapshot jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT clientes_whatsapp_number_check
    CHECK (trim(whatsapp_number) <> '')
);

CREATE TRIGGER set_updated_at_clientes_whatsapp
BEFORE UPDATE ON api.clientes_whatsapp
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 4. PRODUCT PRICES FOR WHATSAPP ORDERS
-- =========================================================

CREATE TABLE api.producto_precios (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id integer NOT NULL REFERENCES api.productos(id) ON DELETE CASCADE,
    unidad text NOT NULL,
    precio numeric(14,2) NOT NULL,
    moneda char(3) NOT NULL DEFAULT 'PEN',
    active boolean NOT NULL DEFAULT true,
    valid_from date NOT NULL DEFAULT current_date,
    valid_to date,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT producto_precios_unique
    UNIQUE (producto_id, unidad, moneda, valid_from),

    CONSTRAINT producto_precios_precio_check
    CHECK (precio >= 0),

    CONSTRAINT producto_precios_moneda_check
    CHECK (moneda IN ('PEN', 'USD', 'EUR'))
);

CREATE TRIGGER set_updated_at_producto_precios
BEFORE UPDATE ON api.producto_precios
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 5. ORDER HEADER
-- =========================================================

CREATE TABLE api.pedidos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_num text NOT NULL UNIQUE,
    cliente_id integer NOT NULL REFERENCES api.clientes_whatsapp(id) ON DELETE RESTRICT,

    canal text NOT NULL DEFAULT 'WHATSAPP',
    estado text NOT NULL DEFAULT 'CONFIRMADO',

    metodo_pago text NOT NULL,
    moneda char(3) NOT NULL DEFAULT 'PEN',

    subtotal numeric(14,2) NOT NULL DEFAULT 0,
    delivery numeric(14,2) NOT NULL DEFAULT 0,
    total numeric(14,2) NOT NULL DEFAULT 0,

    order_url text,
    items_url text,
    maps_url text,

    observacion text,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pedidos_canal_check
    CHECK (canal IN ('WHATSAPP', 'WEB', 'APP', 'MANUAL')),

    CONSTRAINT pedidos_estado_check
    CHECK (estado IN (
        'BORRADOR',
        'PENDIENTE',
        'CONFIRMADO',
        'EN_PREPARACION',
        'DESPACHADO',
        'ENTREGADO',
        'ANULADO'
    )),

    CONSTRAINT pedidos_pago_check
    CHECK (metodo_pago IN (
        'YAPE',
        'PLIN',
        'TRANSFERENCIA',
        'CONTRA_ENTREGA'
    )),

    CONSTRAINT pedidos_moneda_check
    CHECK (moneda IN ('PEN', 'USD', 'EUR')),

    CONSTRAINT pedidos_totales_check
    CHECK (
        subtotal >= 0
        AND delivery >= 0
        AND total >= 0
    )
);

CREATE TRIGGER set_updated_at_pedidos
BEFORE UPDATE ON api.pedidos
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 6. ORDER ITEMS
-- =========================================================

CREATE TABLE api.pedido_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id integer NOT NULL REFERENCES api.pedidos(id) ON DELETE CASCADE,

    producto_id integer REFERENCES api.productos(id) ON DELETE SET NULL,
    producto_texto text NOT NULL,

    cantidad numeric(14,3) NOT NULL,
    unidad text,
    precio_unitario numeric(14,2) NOT NULL DEFAULT 0,
    total_linea numeric(14,2) NOT NULL DEFAULT 0,

    raw_item jsonb,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pedido_items_producto_texto_check
    CHECK (trim(producto_texto) <> ''),

    CONSTRAINT pedido_items_cantidad_check
    CHECK (cantidad > 0),

    CONSTRAINT pedido_items_precio_check
    CHECK (precio_unitario >= 0 AND total_linea >= 0)
);


-- =========================================================
-- 7. DELIVERY ADDRESS
-- =========================================================

CREATE TABLE api.pedido_direcciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id integer NOT NULL REFERENCES api.pedidos(id) ON DELETE CASCADE,

    latitud numeric(12,8),
    longitud numeric(12,8),

    direccion_detectada text,
    direccion_confirmada text,

    distrito text,
    ciudad text,
    pais text NOT NULL DEFAULT 'Perú',

    confirmed boolean NOT NULL DEFAULT true,

    raw_geocode jsonb,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT pedido_direcciones_lat_check
    CHECK (latitud IS NULL OR latitud BETWEEN -90 AND 90),

    CONSTRAINT pedido_direcciones_lon_check
    CHECK (longitud IS NULL OR longitud BETWEEN -180 AND 180)
);


-- =========================================================
-- 8. WHATSAPP CONVERSATION STATE
-- =========================================================

CREATE TABLE api.whatsapp_conversaciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    whatsapp_number text NOT NULL UNIQUE,
    cliente_id integer REFERENCES api.clientes_whatsapp(id) ON DELETE SET NULL,

    estado text NOT NULL DEFAULT 'NEW',

    pedido_id integer REFERENCES api.pedidos(id) ON DELETE SET NULL,
    pedido_borrador jsonb,

    last_inbound_text text,
    last_outbound_text text,
    last_message_at timestamptz NOT NULL DEFAULT now(),

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT whatsapp_estado_check
    CHECK (estado IN (
        'NEW',
        'ASKING_NAME_AND_ITEMS',
        'WAITING_PAYMENT_AND_LOCATION',
        'WAITING_ADDRESS_CONFIRMATION',
        'CONFIRMED',
        'CANCELLED',
        'ERROR'
    ))
);

CREATE TRIGGER set_updated_at_whatsapp_conversaciones
BEFORE UPDATE ON api.whatsapp_conversaciones
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 9. WHATSAPP MESSAGE LOG
-- =========================================================

CREATE TABLE api.whatsapp_mensajes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    whatsapp_number text NOT NULL,
    direction text NOT NULL,
    message_type text,
    message_text text,

    latitude numeric(12,8),
    longitude numeric(12,8),

    raw_payload jsonb,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT whatsapp_direction_check
    CHECK (direction IN ('INBOUND', 'OUTBOUND')),

    CONSTRAINT whatsapp_message_lat_check
    CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),

    CONSTRAINT whatsapp_message_lon_check
    CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180)
);


-- =========================================================
-- 10. EMAIL LOGISTICS OUTBOX
-- The app/OpenClaw/middleware sends the email and then updates status.
-- =========================================================

CREATE TABLE api.email_logistica_log (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    pedido_id integer REFERENCES api.pedidos(id) ON DELETE CASCADE,

    recipient text NOT NULL DEFAULT 'logistica@replau.com',
    subject text NOT NULL,
    body text NOT NULL,

    status text NOT NULL DEFAULT 'PENDING',
    error_message text,

    sent_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT email_status_check
    CHECK (status IN ('PENDING', 'SENT', 'ERROR'))
);

CREATE TRIGGER set_updated_at_email_logistica_log
BEFORE UPDATE ON api.email_logistica_log
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 11. INDEXES
-- =========================================================

CREATE INDEX idx_clientes_whatsapp_number
ON api.clientes_whatsapp(whatsapp_number);

CREATE INDEX idx_producto_precios_producto
ON api.producto_precios(producto_id);

CREATE INDEX idx_pedidos_cliente
ON api.pedidos(cliente_id);

CREATE INDEX idx_pedidos_num
ON api.pedidos(pedido_num);

CREATE INDEX idx_pedidos_estado
ON api.pedidos(estado);

CREATE INDEX idx_pedido_items_pedido
ON api.pedido_items(pedido_id);

CREATE INDEX idx_pedido_direcciones_pedido
ON api.pedido_direcciones(pedido_id);

CREATE INDEX idx_whatsapp_conversaciones_number
ON api.whatsapp_conversaciones(whatsapp_number);

CREATE INDEX idx_whatsapp_mensajes_number
ON api.whatsapp_mensajes(whatsapp_number);

CREATE INDEX idx_email_logistica_status
ON api.email_logistica_log(status);


-- =========================================================
-- 12. SAMPLE PRICE DATA
-- Uses products already created in your previous database script.
-- =========================================================

INSERT INTO api.producto_precios (
    producto_id,
    unidad,
    precio,
    moneda
)
SELECT
    p.id,
    'SACO',
    12.50,
    'PEN'
FROM api.productos p
WHERE p.cdg_prod = 'MP00100008'
ON CONFLICT DO NOTHING;

INSERT INTO api.producto_precios (
    producto_id,
    unidad,
    precio,
    moneda
)
SELECT
    p.id,
    'BOLSA',
    10.00,
    'PEN'
FROM api.productos p
WHERE p.cdg_prod = 'COND001'
ON CONFLICT DO NOTHING;

INSERT INTO api.producto_precios (
    producto_id,
    unidad,
    precio,
    moneda
)
SELECT
    p.id,
    'POTE',
    12.00,
    'PEN'
FROM api.productos p
WHERE p.cdg_prod = 'COND002'
ON CONFLICT DO NOTHING;


-- =========================================================
-- 13. LOGISTICS VIEWS
-- =========================================================

CREATE OR REPLACE VIEW api.v_pedidos_logistica AS
SELECT
    p.id,
    p.pedido_num,
    p.estado,

    c.nombre AS cliente_nombre,
    c.whatsapp_number,

    p.canal,
    p.metodo_pago,
    p.moneda,

    p.subtotal,
    p.delivery,
    p.total,

    d.direccion_confirmada,
    d.direccion_detectada,
    d.latitud,
    d.longitud,
    d.distrito,
    d.ciudad,
    d.pais,

    p.order_url,
    p.items_url,
    p.maps_url,

    p.observacion,
    p.created_at,
    p.updated_at
FROM api.pedidos p
JOIN api.clientes_whatsapp c
    ON c.id = p.cliente_id
LEFT JOIN api.pedido_direcciones d
    ON d.pedido_id = p.id;


CREATE OR REPLACE VIEW api.v_pedido_items_logistica AS
SELECT
    pi.id,
    pi.pedido_id,
    p.pedido_num,

    pi.producto_id,
    pr.cdg_prod,
    pi.producto_texto,
    pr.nombre AS producto_nombre_maestro,

    pi.cantidad,
    pi.unidad,
    pi.precio_unitario,
    pi.total_linea,

    pi.created_at
FROM api.pedido_items pi
JOIN api.pedidos p
    ON p.id = pi.pedido_id
LEFT JOIN api.productos pr
    ON pr.id = pi.producto_id;


CREATE OR REPLACE VIEW api.v_whatsapp_conversaciones AS
SELECT
    wc.id,
    wc.whatsapp_number,
    c.nombre AS cliente_nombre,
    wc.estado,
    wc.pedido_id,
    p.pedido_num,
    p.total,
    wc.last_inbound_text,
    wc.last_outbound_text,
    wc.last_message_at,
    wc.created_at,
    wc.updated_at
FROM api.whatsapp_conversaciones wc
LEFT JOIN api.clientes_whatsapp c
    ON c.id = wc.cliente_id
LEFT JOIN api.pedidos p
    ON p.id = wc.pedido_id;


-- =========================================================
-- 14. FUNCTION: REGISTER WHATSAPP MESSAGE
-- Useful for OpenClaw webhook logging.
-- =========================================================

CREATE OR REPLACE FUNCTION api.registrar_whatsapp_mensaje(
    p_whatsapp_number text,
    p_direction text,
    p_message_type text DEFAULT 'text',
    p_message_text text DEFAULT NULL,
    p_latitude numeric DEFAULT NULL,
    p_longitude numeric DEFAULT NULL,
    p_raw_payload jsonb DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
    v_direction text;
    v_message_id integer;
BEGIN
    v_direction := upper(trim(p_direction));

    IF v_direction NOT IN ('INBOUND', 'OUTBOUND') THEN
        RAISE EXCEPTION 'Invalid direction: %. Use INBOUND or OUTBOUND.', p_direction;
    END IF;

    INSERT INTO api.whatsapp_mensajes (
        whatsapp_number,
        direction,
        message_type,
        message_text,
        latitude,
        longitude,
        raw_payload
    )
    VALUES (
        trim(p_whatsapp_number),
        v_direction,
        p_message_type,
        p_message_text,
        p_latitude,
        p_longitude,
        p_raw_payload
    )
    RETURNING id INTO v_message_id;

    INSERT INTO api.whatsapp_conversaciones (
        whatsapp_number,
        estado,
        last_inbound_text,
        last_outbound_text,
        last_message_at
    )
    VALUES (
        trim(p_whatsapp_number),
        CASE
            WHEN v_direction = 'INBOUND' THEN 'ASKING_NAME_AND_ITEMS'
            ELSE 'NEW'
        END,
        CASE WHEN v_direction = 'INBOUND' THEN p_message_text ELSE NULL END,
        CASE WHEN v_direction = 'OUTBOUND' THEN p_message_text ELSE NULL END,
        now()
    )
    ON CONFLICT (whatsapp_number)
    DO UPDATE SET
        last_inbound_text =
            CASE
                WHEN v_direction = 'INBOUND' THEN p_message_text
                ELSE api.whatsapp_conversaciones.last_inbound_text
            END,
        last_outbound_text =
            CASE
                WHEN v_direction = 'OUTBOUND' THEN p_message_text
                ELSE api.whatsapp_conversaciones.last_outbound_text
            END,
        last_message_at = now(),
        updated_at = now();

    RETURN jsonb_build_object(
        'ok', true,
        'message_id', v_message_id
    );
END;
$$;


-- =========================================================
-- 15. FUNCTION: CONFIRM WHATSAPP ORDER
--
-- This is the main PostgREST RPC endpoint:
-- POST /rpc/confirmar_pedido_whatsapp
-- =========================================================

CREATE OR REPLACE FUNCTION api.confirmar_pedido_whatsapp(
    p_whatsapp_number text,
    p_customer_name text,
    p_payment_method text,
    p_latitude numeric,
    p_longitude numeric,
    p_detected_address text,
    p_confirmed_address text,
    p_items jsonb,
    p_base_url text DEFAULT 'http://localhost:3000',
    p_delivery numeric DEFAULT 0,
    p_observacion text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
    v_cliente_id integer;
    v_pedido_id integer;
    v_pedido_num text;

    v_payment_method text;
    v_item jsonb;
    v_index integer := 0;

    v_producto_id integer;
    v_producto_texto text;
    v_cantidad numeric(14,3);
    v_unidad text;
    v_precio_unitario numeric(14,2);
    v_total_linea numeric(14,2);

    v_subtotal numeric(14,2) := 0;
    v_delivery numeric(14,2) := COALESCE(p_delivery, 0);
    v_total numeric(14,2);

    v_order_url text;
    v_items_url text;
    v_maps_url text;

    v_email_subject text;
    v_email_body text;
    v_items_text text := '';

    v_email_log_id integer;
BEGIN
    -- -----------------------------------------------------
    -- Basic validations
    -- -----------------------------------------------------

    IF p_whatsapp_number IS NULL OR trim(p_whatsapp_number) = '' THEN
        RAISE EXCEPTION 'whatsapp_number is required';
    END IF;

    IF p_customer_name IS NULL OR trim(p_customer_name) = '' THEN
        RAISE EXCEPTION 'customer_name is required';
    END IF;

    IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
        RAISE EXCEPTION 'items must be a non-empty JSON array';
    END IF;

    IF v_delivery < 0 THEN
        RAISE EXCEPTION 'delivery cannot be negative';
    END IF;

    v_payment_method := upper(replace(trim(p_payment_method), ' ', '_'));

    IF v_payment_method NOT IN ('YAPE', 'PLIN', 'TRANSFERENCIA', 'CONTRA_ENTREGA') THEN
        RAISE EXCEPTION 'Invalid payment_method: %. Use YAPE, PLIN, TRANSFERENCIA, or CONTRA_ENTREGA.', p_payment_method;
    END IF;


    -- -----------------------------------------------------
    -- Upsert customer
    -- -----------------------------------------------------

    INSERT INTO api.clientes_whatsapp (
        whatsapp_number,
        nombre,
        last_order_at
    )
    VALUES (
        trim(p_whatsapp_number),
        trim(p_customer_name),
        now()
    )
    ON CONFLICT (whatsapp_number)
    DO UPDATE SET
        nombre = EXCLUDED.nombre,
        last_order_at = now(),
        updated_at = now()
    RETURNING id INTO v_cliente_id;


    -- -----------------------------------------------------
    -- Create order header
    -- -----------------------------------------------------

    v_pedido_num := 'PED-' || lpad(nextval('api.pedido_num_seq')::text, 6, '0');

    INSERT INTO api.pedidos (
        pedido_num,
        cliente_id,
        canal,
        estado,
        metodo_pago,
        moneda,
        subtotal,
        delivery,
        total,
        observacion
    )
    VALUES (
        v_pedido_num,
        v_cliente_id,
        'WHATSAPP',
        'CONFIRMADO',
        v_payment_method,
        'PEN',
        0,
        v_delivery,
        0,
        p_observacion
    )
    RETURNING id INTO v_pedido_id;


    -- -----------------------------------------------------
    -- Insert items
    -- -----------------------------------------------------

    FOR v_item IN
        SELECT value
        FROM jsonb_array_elements(p_items)
    LOOP
        v_index := v_index + 1;

        v_producto_id := NULL;
        v_producto_texto := NULL;
        v_cantidad := NULL;
        v_unidad := NULL;
        v_precio_unitario := NULL;
        v_total_linea := NULL;

        -- Product text
        v_producto_texto := COALESCE(
            NULLIF(trim(v_item ->> 'producto_texto'), ''),
            NULLIF(trim(v_item ->> 'product'), ''),
            NULLIF(trim(v_item ->> 'nombre'), '')
        );

        IF v_producto_texto IS NULL THEN
            RAISE EXCEPTION 'Item % is missing producto_texto/product/nombre', v_index;
        END IF;

        -- Quantity
        v_cantidad := NULLIF(trim(v_item ->> 'cantidad'), '')::numeric;

        IF v_cantidad IS NULL OR v_cantidad <= 0 THEN
            RAISE EXCEPTION 'Item % has invalid cantidad', v_index;
        END IF;

        -- Unit
        v_unidad := upper(NULLIF(trim(COALESCE(v_item ->> 'unidad', v_item ->> 'unit')), ''));

        -- Product id from JSON if present
        IF NULLIF(trim(v_item ->> 'producto_id'), '') IS NOT NULL THEN
            v_producto_id := (v_item ->> 'producto_id')::integer;
        END IF;

        -- Product lookup by text if producto_id was not provided
        IF v_producto_id IS NULL THEN
            SELECT p.id
            INTO v_producto_id
            FROM api.productos p
            WHERE
                upper(p.cdg_prod) = upper(v_producto_texto)
                OR upper(p.nombre) = upper(v_producto_texto)
            ORDER BY p.id
            LIMIT 1;
        END IF;

        -- Price from JSON if present
        IF NULLIF(trim(v_item ->> 'precio_unitario'), '') IS NOT NULL THEN
            v_precio_unitario := (v_item ->> 'precio_unitario')::numeric;
        END IF;

        -- Price lookup if not passed
        IF v_precio_unitario IS NULL AND v_producto_id IS NOT NULL THEN
            SELECT pp.precio
            INTO v_precio_unitario
            FROM api.producto_precios pp
            WHERE pp.producto_id = v_producto_id
              AND pp.active = true
              AND pp.moneda = 'PEN'
              AND (v_unidad IS NULL OR upper(pp.unidad) = upper(v_unidad))
              AND pp.valid_from <= current_date
              AND (pp.valid_to IS NULL OR pp.valid_to >= current_date)
            ORDER BY
                CASE
                    WHEN v_unidad IS NOT NULL AND upper(pp.unidad) = upper(v_unidad) THEN 0
                    ELSE 1
                END,
                pp.valid_from DESC,
                pp.id DESC
            LIMIT 1;
        END IF;

        v_precio_unitario := COALESCE(v_precio_unitario, 0);

        IF v_precio_unitario < 0 THEN
            RAISE EXCEPTION 'Item % has invalid precio_unitario', v_index;
        END IF;

        v_total_linea := round((v_cantidad * v_precio_unitario)::numeric, 2);

        INSERT INTO api.pedido_items (
            pedido_id,
            producto_id,
            producto_texto,
            cantidad,
            unidad,
            precio_unitario,
            total_linea,
            raw_item
        )
        VALUES (
            v_pedido_id,
            v_producto_id,
            v_producto_texto,
            v_cantidad,
            v_unidad,
            v_precio_unitario,
            v_total_linea,
            v_item
        );

        v_subtotal := v_subtotal + v_total_linea;

        v_items_text := v_items_text ||
            v_index::text || '. ' ||
            v_producto_texto || ' x ' ||
            v_cantidad::text || ' ' ||
            COALESCE(v_unidad, '') ||
            ' — S/ ' || to_char(v_total_linea, 'FM999999990.00') ||
            E'\n';
    END LOOP;


    -- -----------------------------------------------------
    -- Address
    -- -----------------------------------------------------

    INSERT INTO api.pedido_direcciones (
        pedido_id,
        latitud,
        longitud,
        direccion_detectada,
        direccion_confirmada,
        confirmed
    )
    VALUES (
        v_pedido_id,
        p_latitude,
        p_longitude,
        p_detected_address,
        p_confirmed_address,
        true
    );


    -- -----------------------------------------------------
    -- URLs
    -- -----------------------------------------------------

    v_total := v_subtotal + v_delivery;

    v_order_url := rtrim(p_base_url, '/') ||
        '/v_pedidos_logistica?id=eq.' ||
        v_pedido_id::text;

    v_items_url := rtrim(p_base_url, '/') ||
        '/v_pedido_items_logistica?pedido_id=eq.' ||
        v_pedido_id::text;

    IF p_latitude IS NOT NULL AND p_longitude IS NOT NULL THEN
        v_maps_url := 'https://www.google.com/maps?q=' ||
            p_latitude::text ||
            ',' ||
            p_longitude::text;
    END IF;


    -- -----------------------------------------------------
    -- Update order totals and URLs
    -- -----------------------------------------------------

    UPDATE api.pedidos
    SET
        subtotal = v_subtotal,
        delivery = v_delivery,
        total = v_total,
        order_url = v_order_url,
        items_url = v_items_url,
        maps_url = v_maps_url,
        updated_at = now()
    WHERE id = v_pedido_id;

    UPDATE api.clientes_whatsapp
    SET
        last_order_at = now(),
        last_order_id = v_pedido_id,
        last_order_num = v_pedido_num,
        last_order_total = v_total,
        last_payment_method = v_payment_method,
        last_latitude = p_latitude,
        last_longitude = p_longitude,
        last_maps_url = v_maps_url,
        last_written_address = CASE
            WHEN p_confirmed_address IS NOT NULL AND position(E'\nReferencia del mapa:' in p_confirmed_address) > 0
                THEN split_part(p_confirmed_address, E'\nReferencia del mapa:', 1)
            ELSE p_confirmed_address
        END,
        last_detected_address = p_detected_address,
        last_confirmed_address = p_confirmed_address,
        last_order_snapshot = jsonb_build_object(
            'pedido_id', v_pedido_id,
            'pedido_num', v_pedido_num,
            'total', v_total,
            'payment_method', v_payment_method,
            'items', p_items,
            'order_url', v_order_url,
            'maps_url', v_maps_url
        ),
        updated_at = now()
    WHERE id = v_cliente_id;


    -- -----------------------------------------------------
    -- Update conversation state
    -- -----------------------------------------------------

    INSERT INTO api.whatsapp_conversaciones (
        whatsapp_number,
        cliente_id,
        estado,
        pedido_id,
        pedido_borrador,
        last_message_at
    )
    VALUES (
        trim(p_whatsapp_number),
        v_cliente_id,
        'CONFIRMED',
        v_pedido_id,
        jsonb_build_object(
            'pedido_id', v_pedido_id,
            'pedido_num', v_pedido_num,
            'total', v_total,
            'items', p_items
        ),
        now()
    )
    ON CONFLICT (whatsapp_number)
    DO UPDATE SET
        cliente_id = EXCLUDED.cliente_id,
        estado = 'CONFIRMED',
        pedido_id = EXCLUDED.pedido_id,
        pedido_borrador = EXCLUDED.pedido_borrador,
        last_message_at = now(),
        updated_at = now();


    -- -----------------------------------------------------
    -- Create logistics email outbox row
    -- -----------------------------------------------------

    v_email_subject := 'Nuevo pedido WhatsApp ' || v_pedido_num;

    v_email_body :=
        'Nuevo pedido confirmado por WhatsApp.' || E'\n\n' ||
        'Pedido: ' || v_pedido_num || E'\n' ||
        'Cliente: ' || trim(p_customer_name) || E'\n' ||
        'WhatsApp: ' || trim(p_whatsapp_number) || E'\n' ||
        'Pago: ' || v_payment_method || E'\n' ||
        'Subtotal: S/ ' || to_char(v_subtotal, 'FM999999990.00') || E'\n' ||
        'Delivery: S/ ' || to_char(v_delivery, 'FM999999990.00') || E'\n' ||
        'Total: S/ ' || to_char(v_total, 'FM999999990.00') || E'\n\n' ||
        'Items:' || E'\n' ||
        v_items_text || E'\n' ||
        'Dirección confirmada:' || E'\n' ||
        COALESCE(p_confirmed_address, p_detected_address, '(sin dirección)') || E'\n\n' ||
        'Pedido:' || E'\n' ||
        v_order_url || E'\n\n' ||
        'Items:' || E'\n' ||
        v_items_url || E'\n\n' ||
        'Ubicación:' || E'\n' ||
        COALESCE(v_maps_url, '(sin ubicación)') || E'\n';

    INSERT INTO api.email_logistica_log (
        pedido_id,
        recipient,
        subject,
        body,
        status
    )
    VALUES (
        v_pedido_id,
        'logistica@replau.com',
        v_email_subject,
        v_email_body,
        'PENDING'
    )
    RETURNING id INTO v_email_log_id;


    -- -----------------------------------------------------
    -- Return response to OpenClaw / PostgREST
    -- -----------------------------------------------------

    RETURN jsonb_build_object(
        'ok', true,
        'pedido_id', v_pedido_id,
        'pedido_num', v_pedido_num,
        'cliente_id', v_cliente_id,
        'subtotal', v_subtotal,
        'delivery', v_delivery,
        'total', v_total,
        'payment_method', v_payment_method,
        'order_url', v_order_url,
        'items_url', v_items_url,
        'maps_url', v_maps_url,
        'email_log_id', v_email_log_id,
        'email_to', 'logistica@replau.com',
        'email_status', 'PENDING',
        'whatsapp_confirmation_text',
            'Pedido confirmado ✅' || E'\n\n' ||
            'Pedido: ' || v_pedido_num || E'\n' ||
            'Cliente: ' || trim(p_customer_name) || E'\n' ||
            'Total: S/ ' || to_char(v_total, 'FM999999990.00') || E'\n' ||
            'Pago: ' || v_payment_method || E'\n\n' ||
            'Dirección:' || E'\n' ||
            COALESCE(p_confirmed_address, p_detected_address, '(sin dirección)') || E'\n\n' ||
            'Puedes ver tu pedido aquí:' || E'\n' ||
            v_order_url
    );
END;
$$;


-- =========================================================
-- 16. PERMISSIONS FOR POSTGREST
-- Development permissions.
-- Later we should replace this with JWT roles.
-- =========================================================

GRANT USAGE ON SCHEMA api TO web_anon;

GRANT SELECT, INSERT, UPDATE, DELETE
ON api.clientes_whatsapp,
   api.producto_precios,
   api.pedidos,
   api.pedido_items,
   api.pedido_direcciones,
   api.whatsapp_conversaciones,
   api.whatsapp_mensajes,
   api.email_logistica_log
TO web_anon;

GRANT SELECT
ON api.v_pedidos_logistica,
   api.v_pedido_items_logistica,
   api.v_whatsapp_conversaciones
TO web_anon;

GRANT USAGE, SELECT, UPDATE
ON SEQUENCE api.pedido_num_seq
TO web_anon;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA api
TO web_anon;

GRANT EXECUTE
ON FUNCTION api.confirmar_pedido_whatsapp(
    text,
    text,
    text,
    numeric,
    numeric,
    text,
    text,
    jsonb,
    text,
    numeric,
    text
)
TO web_anon;

GRANT EXECUTE
ON FUNCTION api.registrar_whatsapp_mensaje(
    text,
    text,
    text,
    text,
    numeric,
    numeric,
    jsonb
)
TO web_anon;


-- Ask PostgREST to reload schema cache.
NOTIFY pgrst, 'reload schema';

COMMIT;
