BEGIN;

-- =========================================================
-- 0. SCHEMA AND ROLES
-- =========================================================

CREATE SCHEMA IF NOT EXISTS api;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'web_anon') THEN
        CREATE ROLE web_anon NOLOGIN;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticator') THEN
        CREATE ROLE authenticator NOINHERIT LOGIN PASSWORD 'ChangeThisPassword123!';
    END IF;
END $$;

GRANT web_anon TO authenticator;
GRANT USAGE ON SCHEMA api TO web_anon;


-- =========================================================
-- 1. DROP OLD APP OBJECTS
-- =========================================================

DROP VIEW IF EXISTS api.v_kardex CASCADE;
DROP VIEW IF EXISTS api.v_stock_actual CASCADE;
DROP VIEW IF EXISTS api.v_recepciones_detalle CASCADE;
DROP VIEW IF EXISTS api.v_ordenes_compra_detalle CASCADE;
DROP VIEW IF EXISTS api.v_ordenes_compra_resumen CASCADE;
DROP VIEW IF EXISTS api.v_productos CASCADE;

DROP TABLE IF EXISTS api.movimientos_stock CASCADE;
DROP TABLE IF EXISTS api.recepcion_detalle CASCADE;
DROP TABLE IF EXISTS api.recepciones CASCADE;
DROP TABLE IF EXISTS api.ordenes_compra_detalle CASCADE;
DROP TABLE IF EXISTS api.ordenes_compra CASCADE;
DROP TABLE IF EXISTS api.lotes CASCADE;
DROP TABLE IF EXISTS api.producto_packs CASCADE;
DROP TABLE IF EXISTS api.productos CASCADE;
DROP TABLE IF EXISTS api.almacenes CASCADE;
DROP TABLE IF EXISTS api.proveedores CASCADE;
DROP TABLE IF EXISTS api.app_users CASCADE;

DROP FUNCTION IF EXISTS api.set_updated_at() CASCADE;
DROP FUNCTION IF EXISTS api.recalcular_estado_oc(integer) CASCADE;
DROP FUNCTION IF EXISTS api.trg_recepcion_detalle_before() CASCADE;
DROP FUNCTION IF EXISTS api.trg_recepcion_detalle_after() CASCADE;


-- =========================================================
-- 2. GENERIC UPDATED_AT TRIGGER
-- =========================================================

CREATE OR REPLACE FUNCTION api.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


-- =========================================================
-- 3. USERS / OPERATORS
-- =========================================================

CREATE TABLE api.app_users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    full_name text NOT NULL,
    email text UNIQUE,
    role_name text NOT NULL DEFAULT 'operator',
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT app_users_role_check
    CHECK (role_name IN ('admin', 'supervisor', 'operator', 'viewer'))
);

CREATE TRIGGER set_updated_at_app_users
BEFORE UPDATE ON api.app_users
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 4. SUPPLIERS
-- =========================================================

CREATE TABLE api.proveedores (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc_sunat varchar(11),
    ruc_prv_internal char(8),
    nombre text NOT NULL,
    direccion text,
    telefono text,
    email text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT proveedores_ruc_sunat_unique UNIQUE (ruc_sunat),
    CONSTRAINT proveedores_ruc_internal_unique UNIQUE (ruc_prv_internal)
);

CREATE TRIGGER set_updated_at_proveedores
BEFORE UPDATE ON api.proveedores
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 5. WAREHOUSES
-- =========================================================

CREATE TABLE api.almacenes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text NOT NULL UNIQUE,
    nombre text NOT NULL,
    ubicacion text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER set_updated_at_almacenes
BEFORE UPDATE ON api.almacenes
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 6. PRODUCTS
-- =========================================================

CREATE TABLE api.productos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cdg_prod text NOT NULL UNIQUE,
    nombre text NOT NULL,
    tipo_producto text NOT NULL,
    unidad_medida text NOT NULL DEFAULT 'UND',
    pack_default text,
    envase_default text,
    stock_minimo numeric(14,3) NOT NULL DEFAULT 0,
    controla_lote boolean NOT NULL DEFAULT true,
    controla_vencimiento boolean NOT NULL DEFAULT true,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT productos_tipo_check
    CHECK (tipo_producto IN ('GRANELES', 'CONDIMENTOS', 'INSUMOS', 'TERMINADO', 'OTRO')),

    CONSTRAINT productos_stock_minimo_check
    CHECK (stock_minimo >= 0)
);

CREATE TRIGGER set_updated_at_productos
BEFORE UPDATE ON api.productos
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 7. PRODUCT PACKS
-- =========================================================

CREATE TABLE api.producto_packs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id integer NOT NULL REFERENCES api.productos(id) ON DELETE CASCADE,
    pack_name text NOT NULL,
    factor numeric(14,3) NOT NULL DEFAULT 1,
    is_default boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT producto_packs_unique UNIQUE (producto_id, pack_name),
    CONSTRAINT producto_packs_factor_check CHECK (factor > 0)
);

CREATE TRIGGER set_updated_at_producto_packs
BEFORE UPDATE ON api.producto_packs
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 8. LOTS / BATCHES
-- =========================================================

CREATE TABLE api.lotes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id integer NOT NULL REFERENCES api.productos(id) ON DELETE RESTRICT,
    lote_codigo text NOT NULL,
    batch text,
    fecha_venc date,
    observacion text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT lotes_unique UNIQUE (producto_id, lote_codigo)
);

CREATE TRIGGER set_updated_at_lotes
BEFORE UPDATE ON api.lotes
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 9. PURCHASE ORDER HEADER
-- =========================================================

CREATE TABLE api.ordenes_compra (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_ocom text NOT NULL UNIQUE,
    proveedor_id integer REFERENCES api.proveedores(id) ON DELETE RESTRICT,
    fecha_ocom date NOT NULL DEFAULT current_date,
    fecha_entrega date,
    moneda char(3) NOT NULL DEFAULT 'PEN',
    estado text NOT NULL DEFAULT 'ABIERTA',
    observacion text,
    created_by integer REFERENCES api.app_users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ordenes_compra_estado_check
    CHECK (estado IN ('ABIERTA', 'PARCIAL', 'CERRADA', 'ANULADA')),

    CONSTRAINT ordenes_compra_moneda_check
    CHECK (moneda IN ('PEN', 'USD', 'EUR'))
);

CREATE TRIGGER set_updated_at_ordenes_compra
BEFORE UPDATE ON api.ordenes_compra
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 10. PURCHASE ORDER DETAIL
-- =========================================================

CREATE TABLE api.ordenes_compra_detalle (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_id integer NOT NULL REFERENCES api.ordenes_compra(id) ON DELETE CASCADE,
    linea integer NOT NULL,
    producto_id integer NOT NULL REFERENCES api.productos(id) ON DELETE RESTRICT,
    descripcion text,
    cantidad_pedida numeric(14,3) NOT NULL,
    cantidad_recibida numeric(14,3) NOT NULL DEFAULT 0,
    precio_unitario numeric(14,4) NOT NULL DEFAULT 0,
    impuesto numeric(14,4) NOT NULL DEFAULT 0,
    descuento numeric(14,4) NOT NULL DEFAULT 0,
    estado text NOT NULL DEFAULT 'PENDIENTE',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT oc_detalle_unique_linea UNIQUE (orden_id, linea),

    CONSTRAINT oc_detalle_cantidad_pedida_check
    CHECK (cantidad_pedida > 0),

    CONSTRAINT oc_detalle_cantidad_recibida_check
    CHECK (cantidad_recibida >= 0),

    CONSTRAINT oc_detalle_estado_check
    CHECK (estado IN ('PENDIENTE', 'PARCIAL', 'CERRADA', 'ANULADA'))
);

CREATE TRIGGER set_updated_at_ordenes_compra_detalle
BEFORE UPDATE ON api.ordenes_compra_detalle
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 11. RECEIVING HEADER
-- =========================================================

CREATE TABLE api.recepciones (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    num_recepcion text NOT NULL UNIQUE,
    orden_id integer REFERENCES api.ordenes_compra(id) ON DELETE RESTRICT,
    fecha_recepcion timestamptz NOT NULL DEFAULT now(),
    almacen_id integer NOT NULL REFERENCES api.almacenes(id) ON DELETE RESTRICT,
    operador_id integer REFERENCES api.app_users(id) ON DELETE SET NULL,
    estado text NOT NULL DEFAULT 'REGISTRADA',
    observacion text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT recepciones_estado_check
    CHECK (estado IN ('REGISTRADA', 'ANULADA'))
);

CREATE TRIGGER set_updated_at_recepciones
BEFORE UPDATE ON api.recepciones
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 12. RECEIVING DETAIL
-- =========================================================

CREATE TABLE api.recepcion_detalle (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recepcion_id integer NOT NULL REFERENCES api.recepciones(id) ON DELETE CASCADE,
    oc_detalle_id integer NOT NULL REFERENCES api.ordenes_compra_detalle(id) ON DELETE RESTRICT,
    producto_id integer NOT NULL REFERENCES api.productos(id) ON DELETE RESTRICT,
    almacen_id integer NOT NULL REFERENCES api.almacenes(id) ON DELETE RESTRICT,

    lote_id integer REFERENCES api.lotes(id) ON DELETE RESTRICT,
    lote_codigo text,
    batch text,
    fecha_venc date,

    cantidad_recibida numeric(14,3) NOT NULL,
    pack text,
    envase text,
    observacion text,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT recepcion_detalle_cantidad_check
    CHECK (cantidad_recibida > 0)
);

CREATE TRIGGER set_updated_at_recepcion_detalle
BEFORE UPDATE ON api.recepcion_detalle
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- 13. STOCK MOVEMENTS / KARDEX BASE
-- =========================================================

CREATE TABLE api.movimientos_stock (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_movimiento timestamptz NOT NULL DEFAULT now(),

    movimiento_tipo text NOT NULL,
    almacen_origen_id integer REFERENCES api.almacenes(id) ON DELETE RESTRICT,
    almacen_destino_id integer REFERENCES api.almacenes(id) ON DELETE RESTRICT,

    producto_id integer NOT NULL REFERENCES api.productos(id) ON DELETE RESTRICT,
    lote_id integer REFERENCES api.lotes(id) ON DELETE RESTRICT,

    cantidad numeric(14,3) NOT NULL,

    doc_tipo text,
    doc_id integer,
    doc_linea_id integer,
    referencia text,

    operador_id integer REFERENCES api.app_users(id) ON DELETE SET NULL,
    observacion text,

    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT movimientos_stock_tipo_check
    CHECK (movimiento_tipo IN (
        'RECEPCION',
        'INGRESO',
        'SALIDA',
        'AJUSTE_POSITIVO',
        'AJUSTE_NEGATIVO'
    )),

    CONSTRAINT movimientos_stock_cantidad_check
    CHECK (cantidad > 0),

    CONSTRAINT movimientos_stock_almacen_check
    CHECK (
        (
            movimiento_tipo IN ('RECEPCION', 'INGRESO', 'AJUSTE_POSITIVO')
            AND almacen_destino_id IS NOT NULL
        )
        OR
        (
            movimiento_tipo IN ('SALIDA', 'AJUSTE_NEGATIVO')
            AND almacen_origen_id IS NOT NULL
        )
    )
);


-- =========================================================
-- 14. FUNCTIONS FOR AUTOMATIC RECEIVING LOGIC
-- =========================================================

CREATE OR REPLACE FUNCTION api.recalcular_estado_oc(p_orden_id integer)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_total_lines integer;
    v_closed_lines integer;
    v_received_lines integer;
BEGIN
    SELECT
        COUNT(*),
        COUNT(*) FILTER (WHERE estado = 'CERRADA'),
        COUNT(*) FILTER (WHERE cantidad_recibida > 0)
    INTO
        v_total_lines,
        v_closed_lines,
        v_received_lines
    FROM api.ordenes_compra_detalle
    WHERE orden_id = p_orden_id;

    UPDATE api.ordenes_compra
    SET estado =
        CASE
            WHEN estado = 'ANULADA' THEN 'ANULADA'
            WHEN v_total_lines > 0 AND v_closed_lines = v_total_lines THEN 'CERRADA'
            WHEN v_received_lines > 0 THEN 'PARCIAL'
            ELSE 'ABIERTA'
        END,
        updated_at = now()
    WHERE id = p_orden_id;
END;
$$;


CREATE OR REPLACE FUNCTION api.trg_recepcion_detalle_before()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_lote_id integer;
BEGIN
    -- If lote_id is missing but lote_codigo exists, create or reuse lote automatically.
    IF NEW.lote_id IS NULL AND NEW.lote_codigo IS NOT NULL AND trim(NEW.lote_codigo) <> '' THEN

        INSERT INTO api.lotes (
            producto_id,
            lote_codigo,
            batch,
            fecha_venc
        )
        VALUES (
            NEW.producto_id,
            trim(NEW.lote_codigo),
            NEW.batch,
            NEW.fecha_venc
        )
        ON CONFLICT (producto_id, lote_codigo)
        DO UPDATE SET
            batch = COALESCE(EXCLUDED.batch, api.lotes.batch),
            fecha_venc = COALESCE(EXCLUDED.fecha_venc, api.lotes.fecha_venc),
            updated_at = now()
        RETURNING id INTO v_lote_id;

        NEW.lote_id := v_lote_id;
    END IF;

    RETURN NEW;
END;
$$;


CREATE OR REPLACE FUNCTION api.trg_recepcion_detalle_after()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_orden_id integer;
    v_recepcion_num text;
    v_operador_id integer;
BEGIN
    SELECT
        r.orden_id,
        r.num_recepcion,
        r.operador_id
    INTO
        v_orden_id,
        v_recepcion_num,
        v_operador_id
    FROM api.recepciones r
    WHERE r.id = NEW.recepcion_id;

    -- Create automatic stock movement.
    INSERT INTO api.movimientos_stock (
        fecha_movimiento,
        movimiento_tipo,
        almacen_destino_id,
        producto_id,
        lote_id,
        cantidad,
        doc_tipo,
        doc_id,
        doc_linea_id,
        referencia,
        operador_id,
        observacion
    )
    VALUES (
        now(),
        'RECEPCION',
        NEW.almacen_id,
        NEW.producto_id,
        NEW.lote_id,
        NEW.cantidad_recibida,
        'RECEPCION',
        NEW.recepcion_id,
        NEW.id,
        v_recepcion_num,
        v_operador_id,
        NEW.observacion
    );

    -- Recalculate received quantity in the PO line.
    UPDATE api.ordenes_compra_detalle d
    SET
        cantidad_recibida = COALESCE((
            SELECT SUM(rd.cantidad_recibida)
            FROM api.recepcion_detalle rd
            WHERE rd.oc_detalle_id = d.id
        ), 0),
        estado =
            CASE
                WHEN COALESCE((
                    SELECT SUM(rd.cantidad_recibida)
                    FROM api.recepcion_detalle rd
                    WHERE rd.oc_detalle_id = d.id
                ), 0) >= d.cantidad_pedida THEN 'CERRADA'

                WHEN COALESCE((
                    SELECT SUM(rd.cantidad_recibida)
                    FROM api.recepcion_detalle rd
                    WHERE rd.oc_detalle_id = d.id
                ), 0) > 0 THEN 'PARCIAL'

                ELSE 'PENDIENTE'
            END,
        updated_at = now()
    WHERE d.id = NEW.oc_detalle_id;

    PERFORM api.recalcular_estado_oc(v_orden_id);

    RETURN NEW;
END;
$$;


CREATE TRIGGER recepcion_detalle_before_insert
BEFORE INSERT ON api.recepcion_detalle
FOR EACH ROW
EXECUTE FUNCTION api.trg_recepcion_detalle_before();


CREATE TRIGGER recepcion_detalle_after_insert
AFTER INSERT ON api.recepcion_detalle
FOR EACH ROW
EXECUTE FUNCTION api.trg_recepcion_detalle_after();


-- =========================================================
-- 15. API VIEWS
-- =========================================================

CREATE OR REPLACE VIEW api.v_productos AS
SELECT
    p.id,
    p.cdg_prod,
    p.nombre,
    p.tipo_producto,
    p.unidad_medida,
    p.pack_default,
    p.envase_default,
    p.stock_minimo,
    p.controla_lote,
    p.controla_vencimiento,
    p.active,
    p.created_at,
    p.updated_at
FROM api.productos p;


CREATE OR REPLACE VIEW api.v_ordenes_compra_resumen AS
SELECT
    oc.id,
    oc.num_ocom,
    oc.fecha_ocom,
    oc.fecha_entrega,
    oc.moneda,
    oc.estado,
    pr.nombre AS proveedor_nombre,
    pr.ruc_sunat,
    pr.ruc_prv_internal,
    COUNT(d.id) AS total_lineas,
    COALESCE(SUM(d.cantidad_pedida), 0) AS total_cantidad_pedida,
    COALESCE(SUM(d.cantidad_recibida), 0) AS total_cantidad_recibida,
    COALESCE(SUM(d.cantidad_pedida * d.precio_unitario), 0) AS subtotal,
    oc.observacion,
    oc.created_at,
    oc.updated_at
FROM api.ordenes_compra oc
LEFT JOIN api.proveedores pr ON pr.id = oc.proveedor_id
LEFT JOIN api.ordenes_compra_detalle d ON d.orden_id = oc.id
GROUP BY
    oc.id,
    pr.nombre,
    pr.ruc_sunat,
    pr.ruc_prv_internal;


CREATE OR REPLACE VIEW api.v_ordenes_compra_detalle AS
SELECT
    d.id,
    d.orden_id,
    oc.num_ocom,
    oc.estado AS estado_oc,
    d.linea,
    d.producto_id,
    p.cdg_prod,
    p.nombre AS producto_nombre,
    p.tipo_producto,
    d.descripcion,
    d.cantidad_pedida,
    d.cantidad_recibida,
    d.cantidad_pedida - d.cantidad_recibida AS cantidad_pendiente,
    d.precio_unitario,
    d.impuesto,
    d.descuento,
    d.estado AS estado_linea,
    d.created_at,
    d.updated_at
FROM api.ordenes_compra_detalle d
JOIN api.ordenes_compra oc ON oc.id = d.orden_id
JOIN api.productos p ON p.id = d.producto_id;


CREATE OR REPLACE VIEW api.v_recepciones_detalle AS
SELECT
    rd.id,
    rd.recepcion_id,
    r.num_recepcion,
    r.fecha_recepcion,
    r.estado AS estado_recepcion,
    oc.num_ocom,
    rd.oc_detalle_id,
    rd.producto_id,
    p.cdg_prod,
    p.nombre AS producto_nombre,
    rd.almacen_id,
    a.codigo AS almacen_codigo,
    a.nombre AS almacen_nombre,
    rd.lote_id,
    l.lote_codigo,
    l.batch,
    l.fecha_venc,
    rd.cantidad_recibida,
    rd.pack,
    rd.envase,
    u.full_name AS operador_nombre,
    rd.observacion,
    rd.created_at
FROM api.recepcion_detalle rd
JOIN api.recepciones r ON r.id = rd.recepcion_id
LEFT JOIN api.ordenes_compra oc ON oc.id = r.orden_id
JOIN api.productos p ON p.id = rd.producto_id
JOIN api.almacenes a ON a.id = rd.almacen_id
LEFT JOIN api.lotes l ON l.id = rd.lote_id
LEFT JOIN api.app_users u ON u.id = r.operador_id;


CREATE OR REPLACE VIEW api.v_kardex AS
SELECT
    ms.id,
    ms.fecha_movimiento,
    ms.movimiento_tipo,
    CASE
        WHEN ms.movimiento_tipo IN ('RECEPCION', 'INGRESO', 'AJUSTE_POSITIVO') THEN 'ENTRADA'
        WHEN ms.movimiento_tipo IN ('SALIDA', 'AJUSTE_NEGATIVO') THEN 'SALIDA'
    END AS entrada_salida,

    COALESCE(ms.almacen_destino_id, ms.almacen_origen_id) AS almacen_id,
    a.codigo AS almacen_codigo,
    a.nombre AS almacen_nombre,

    ms.producto_id,
    p.cdg_prod,
    p.nombre AS producto_nombre,
    p.tipo_producto,

    ms.lote_id,
    l.lote_codigo,
    l.batch,
    l.fecha_venc,

    ms.cantidad,

    CASE
        WHEN ms.movimiento_tipo IN ('RECEPCION', 'INGRESO', 'AJUSTE_POSITIVO') THEN ms.cantidad
        WHEN ms.movimiento_tipo IN ('SALIDA', 'AJUSTE_NEGATIVO') THEN ms.cantidad * -1
    END AS cantidad_signo,

    ms.doc_tipo,
    ms.doc_id,
    ms.doc_linea_id,
    ms.referencia,
    u.full_name AS operador_nombre,
    ms.observacion,
    ms.created_at
FROM api.movimientos_stock ms
JOIN api.productos p ON p.id = ms.producto_id
LEFT JOIN api.lotes l ON l.id = ms.lote_id
LEFT JOIN api.almacenes a ON a.id = COALESCE(ms.almacen_destino_id, ms.almacen_origen_id)
LEFT JOIN api.app_users u ON u.id = ms.operador_id;


CREATE OR REPLACE VIEW api.v_stock_actual AS
SELECT
    almacen_id,
    almacen_codigo,
    almacen_nombre,
    producto_id,
    cdg_prod,
    producto_nombre,
    tipo_producto,
    lote_id,
    lote_codigo,
    batch,
    fecha_venc,
    SUM(cantidad_signo) AS stock_actual
FROM api.v_kardex
GROUP BY
    almacen_id,
    almacen_codigo,
    almacen_nombre,
    producto_id,
    cdg_prod,
    producto_nombre,
    tipo_producto,
    lote_id,
    lote_codigo,
    batch,
    fecha_venc
HAVING SUM(cantidad_signo) <> 0;


-- =========================================================
-- 16. INDEXES
-- =========================================================

CREATE INDEX idx_productos_cdg_prod ON api.productos(cdg_prod);
CREATE INDEX idx_productos_nombre ON api.productos(nombre);
CREATE INDEX idx_lotes_producto ON api.lotes(producto_id);
CREATE INDEX idx_lotes_codigo ON api.lotes(lote_codigo);
CREATE INDEX idx_oc_num ON api.ordenes_compra(num_ocom);
CREATE INDEX idx_oc_estado ON api.ordenes_compra(estado);
CREATE INDEX idx_oc_detalle_orden ON api.ordenes_compra_detalle(orden_id);
CREATE INDEX idx_oc_detalle_producto ON api.ordenes_compra_detalle(producto_id);
CREATE INDEX idx_recepciones_num ON api.recepciones(num_recepcion);
CREATE INDEX idx_recepciones_orden ON api.recepciones(orden_id);
CREATE INDEX idx_recepcion_detalle_recepcion ON api.recepcion_detalle(recepcion_id);
CREATE INDEX idx_recepcion_detalle_oc_detalle ON api.recepcion_detalle(oc_detalle_id);
CREATE INDEX idx_movimientos_producto ON api.movimientos_stock(producto_id);
CREATE INDEX idx_movimientos_lote ON api.movimientos_stock(lote_id);
CREATE INDEX idx_movimientos_fecha ON api.movimientos_stock(fecha_movimiento);


-- =========================================================
-- 17. SAMPLE DATA
-- =========================================================

INSERT INTO api.app_users (username, full_name, email, role_name)
VALUES
    ('admin', 'Administrador Local', 'admin@example.local', 'admin'),
    ('operador1', 'Operador de Almacén', 'operador1@example.local', 'operator');


INSERT INTO api.almacenes (codigo, nombre, ubicacion)
VALUES
    ('ALM-PRIN', 'Almacén Principal', 'Planta principal'),
    ('ALM-PROD', 'Almacén Producción', 'Zona de producción');


INSERT INTO api.proveedores (
    ruc_sunat,
    ruc_prv_internal,
    nombre,
    direccion
)
VALUES
    ('20123456789', '00001126', 'Proveedor Demo S.A.C.', 'Lima, Perú');


INSERT INTO api.productos (
    cdg_prod,
    nombre,
    tipo_producto,
    unidad_medida,
    pack_default,
    envase_default,
    stock_minimo,
    controla_lote,
    controla_vencimiento
)
VALUES
    ('MP00100008', 'OREJONES', 'GRANELES', 'KG', 'SACO', NULL, 10, true, true),
    ('COND001', 'PIMIENTA MOLIDA', 'CONDIMENTOS', 'KG', 'BOLSA', 'BOLSA', 5, true, true),
    ('COND002', 'CANELA MOLIDA', 'CONDIMENTOS', 'KG', 'POTE', 'POTE', 5, true, true);


INSERT INTO api.producto_packs (producto_id, pack_name, factor, is_default)
SELECT id, 'SACO', 1, true
FROM api.productos
WHERE cdg_prod = 'MP00100008';

INSERT INTO api.producto_packs (producto_id, pack_name, factor, is_default)
SELECT id, 'BOLSA', 1, true
FROM api.productos
WHERE cdg_prod = 'COND001';

INSERT INTO api.producto_packs (producto_id, pack_name, factor, is_default)
SELECT id, 'POTE', 1, true
FROM api.productos
WHERE cdg_prod = 'COND002';


INSERT INTO api.ordenes_compra (
    num_ocom,
    proveedor_id,
    fecha_ocom,
    fecha_entrega,
    moneda,
    estado,
    created_by,
    observacion
)
SELECT
    '000001',
    pr.id,
    current_date,
    current_date + 7,
    'PEN',
    'ABIERTA',
    u.id,
    'Orden de compra demo'
FROM api.proveedores pr
CROSS JOIN api.app_users u
WHERE pr.ruc_prv_internal = '00001126'
  AND u.username = 'admin';


INSERT INTO api.ordenes_compra_detalle (
    orden_id,
    linea,
    producto_id,
    descripcion,
    cantidad_pedida,
    precio_unitario
)
SELECT
    oc.id,
    1,
    p.id,
    p.nombre,
    100,
    12.50
FROM api.ordenes_compra oc
JOIN api.productos p ON p.cdg_prod = 'MP00100008'
WHERE oc.num_ocom = '000001';


INSERT INTO api.ordenes_compra_detalle (
    orden_id,
    linea,
    producto_id,
    descripcion,
    cantidad_pedida,
    precio_unitario
)
SELECT
    oc.id,
    2,
    p.id,
    p.nombre,
    50,
    20.00
FROM api.ordenes_compra oc
JOIN api.productos p ON p.cdg_prod = 'COND001'
WHERE oc.num_ocom = '000001';


-- Sample reception for first line.
INSERT INTO api.recepciones (
    num_recepcion,
    orden_id,
    almacen_id,
    operador_id,
    observacion
)
SELECT
    'REC-000001',
    oc.id,
    a.id,
    u.id,
    'Recepción demo'
FROM api.ordenes_compra oc
JOIN api.almacenes a ON a.codigo = 'ALM-PRIN'
JOIN api.app_users u ON u.username = 'operador1'
WHERE oc.num_ocom = '000001';


INSERT INTO api.recepcion_detalle (
    recepcion_id,
    oc_detalle_id,
    producto_id,
    almacen_id,
    lote_codigo,
    batch,
    fecha_venc,
    cantidad_recibida,
    pack,
    envase,
    observacion
)
SELECT
    r.id,
    d.id,
    d.producto_id,
    r.almacen_id,
    '20260423-01',
    '01',
    current_date + 180,
    25,
    'SACO',
    NULL,
    'Ingreso demo desde recepción'
FROM api.recepciones r
JOIN api.ordenes_compra oc ON oc.id = r.orden_id
JOIN api.ordenes_compra_detalle d ON d.orden_id = oc.id AND d.linea = 1
WHERE r.num_recepcion = 'REC-000001';


-- =========================================================
-- 18. POSTGREST DEVELOPMENT PERMISSIONS
-- =========================================================

GRANT USAGE ON SCHEMA api TO web_anon;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA api
TO web_anon;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA api
TO web_anon;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO web_anon;

ALTER DEFAULT PRIVILEGES IN SCHEMA api
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO web_anon;

COMMIT;
