\set ON_ERROR_STOP on

CREATE SCHEMA api;
CREATE TABLE api.clientes_whatsapp (
    id integer PRIMARY KEY, whatsapp_number text, channel_kind text DEFAULT 'whatsapp',
    channel_id text DEFAULT 'replau-main', account_id text, customer_address text
);
CREATE TABLE api.pedidos (id integer PRIMARY KEY);
CREATE TABLE api.whatsapp_conversaciones (
    id integer PRIMARY KEY, whatsapp_number text, cliente_id integer, estado text,
    pedido_id integer, pedido_borrador jsonb, last_inbound_text text,
    last_outbound_text text, last_message_at timestamptz, created_at timestamptz,
    updated_at timestamptz, channel_kind text, channel_id text, account_id text,
    customer_address text
);
CREATE TABLE api.whatsapp_mensajes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, whatsapp_number text,
    channel_kind text, channel_id text, account_id text, customer_address text,
    direction text, message_type text, message_text text, latitude numeric,
    longitude numeric, raw_payload jsonb, created_at timestamptz DEFAULT now()
);

INSERT INTO api.clientes_whatsapp VALUES
    (1,'51999999999','whatsapp','replau-main',NULL,'51999999999');
INSERT INTO api.whatsapp_conversaciones VALUES
    (1,'51999999999',1,'WAITING_PAYMENT_AND_LOCATION',NULL,'{"item":"legacy"}',
     NULL,NULL,now(),now(),now(),'whatsapp','replau-main',NULL,'51999999999');

\ir add_channel_boundaries_phase3.sql

SELECT api.registrar_whatsapp_mensaje_canal(
    'whatsapp','whatsapp-account:a','a','51999999999','INBOUND','text','draft A',NULL,NULL,'{}'
);
SELECT api.registrar_whatsapp_mensaje_canal(
    'whatsapp','whatsapp-account:b','b','51999999999','INBOUND','text','draft B',NULL,NULL,'{}'
);
UPDATE api.whatsapp_conversation_states SET pedido_borrador='{"account":"A"}' WHERE channel_id='whatsapp-account:a';
UPDATE api.whatsapp_conversation_states SET pedido_borrador='{"account":"B"}' WHERE channel_id='whatsapp-account:b';

DO $$
DECLARE
    v_count integer;
    v_legacy jsonb;
    v_a jsonb;
    v_b jsonb;
BEGIN
    SELECT count(*) INTO v_count FROM api.whatsapp_conversation_states WHERE customer_address='51999999999';
    IF v_count <> 3 THEN RAISE EXCEPTION 'expected 3 isolated states, got %', v_count; END IF;
    SELECT pedido_borrador INTO v_legacy FROM api.whatsapp_conversation_states WHERE channel_id='replau-main';
    SELECT pedido_borrador INTO v_a FROM api.whatsapp_conversation_states WHERE channel_id='whatsapp-account:a';
    SELECT pedido_borrador INTO v_b FROM api.whatsapp_conversation_states WHERE channel_id='whatsapp-account:b';
    IF v_legacy <> '{"item":"legacy"}'::jsonb THEN RAISE EXCEPTION 'legacy migration changed draft'; END IF;
    IF v_a <> '{"account":"A"}'::jsonb OR v_b <> '{"account":"B"}'::jsonb THEN
        RAISE EXCEPTION 'account drafts collided';
    END IF;
END $$;
