BEGIN;

CREATE SCHEMA IF NOT EXISTS api;

-- 1) Add payment status fields to pedidos.
ALTER TABLE api.pedidos
  ADD COLUMN IF NOT EXISTS payment_status text NOT NULL DEFAULT 'PENDING',
  ADD COLUMN IF NOT EXISTS payment_proof_required boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS payment_verified_at timestamp with time zone,
  ADD COLUMN IF NOT EXISTS payment_verified_by text,
  ADD COLUMN IF NOT EXISTS payment_notes text;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pedidos_payment_status_check'
      AND conrelid = 'api.pedidos'::regclass
  ) THEN
    ALTER TABLE api.pedidos
      ADD CONSTRAINT pedidos_payment_status_check
      CHECK (payment_status = ANY (ARRAY[
        'PENDING',
        'PROOF_REQUIRED',
        'PROOF_RECEIVED',
        'PAID_VERIFIED',
        'PAYMENT_REJECTED',
        'PAYMENT_ON_DELIVERY'
      ]));
  END IF;
END $$;

-- 2) Payment proof table.
CREATE TABLE IF NOT EXISTS api.pedido_payment_proofs (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id integer REFERENCES api.pedidos(id) ON DELETE CASCADE,
  cliente_id integer REFERENCES api.clientes_whatsapp(id) ON DELETE SET NULL,
  whatsapp_number text NOT NULL,
  media_type text NOT NULL DEFAULT 'image',
  media_id text,
  media_url text,
  local_path text,
  original_filename text,
  caption text,
  status text NOT NULL DEFAULT 'RECEIVED',
  verified_by text,
  verified_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pedido_payment_proofs_status_check CHECK (status = ANY (ARRAY[
    'RECEIVED',
    'VERIFIED',
    'REJECTED',
    'CANCELLED'
  ]))
);

CREATE INDEX IF NOT EXISTS idx_payment_proofs_pedido_id ON api.pedido_payment_proofs(pedido_id);
CREATE INDEX IF NOT EXISTS idx_payment_proofs_status ON api.pedido_payment_proofs(status);
CREATE INDEX IF NOT EXISTS idx_payment_proofs_whatsapp_number ON api.pedido_payment_proofs(whatsapp_number);
CREATE INDEX IF NOT EXISTS idx_payment_proofs_created_at ON api.pedido_payment_proofs(created_at DESC);

DROP TRIGGER IF EXISTS set_updated_at_pedido_payment_proofs ON api.pedido_payment_proofs;
CREATE TRIGGER set_updated_at_pedido_payment_proofs
BEFORE UPDATE ON api.pedido_payment_proofs
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();

-- 3) View for review UI.
CREATE OR REPLACE VIEW api.v_payment_proofs_logistica AS
SELECT
  pr.id,
  pr.pedido_id,
  vpl.pedido_num,
  pr.cliente_id,
  COALESCE(vpl.cliente_nombre, '') AS cliente_nombre,
  pr.whatsapp_number,
  vpl.estado AS pedido_estado,
  vpl.total,
  p.payment_status,
  p.payment_proof_required,
  pr.media_type,
  pr.media_id,
  pr.media_url,
  pr.local_path,
  pr.original_filename,
  pr.caption,
  pr.status,
  pr.verified_by,
  pr.verified_at,
  pr.review_notes,
  pr.created_at,
  pr.updated_at
FROM api.pedido_payment_proofs pr
LEFT JOIN api.pedidos p ON p.id = pr.pedido_id
LEFT JOIN api.v_pedidos_logistica vpl ON vpl.id = pr.pedido_id;

-- 4) RPC: mark an order as payment-proof-required.
CREATE OR REPLACE FUNCTION api.marcar_pago_requiere_comprobante(
  p_pedido_id integer,
  p_required boolean DEFAULT true,
  p_notes text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_row api.pedidos%ROWTYPE;
BEGIN
  UPDATE api.pedidos
  SET payment_proof_required = p_required,
      payment_status = CASE WHEN p_required THEN 'PROOF_REQUIRED' ELSE payment_status END,
      payment_notes = COALESCE(p_notes, payment_notes)
  WHERE id = p_pedido_id
  RETURNING * INTO v_row;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pedido id % not found', p_pedido_id;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'pedido_id', p_pedido_id,
    'payment_status', v_row.payment_status,
    'payment_proof_required', v_row.payment_proof_required
  );
END;
$$;

-- 5) RPC: register inbound WhatsApp payment proof.
CREATE OR REPLACE FUNCTION api.registrar_comprobante_pago_whatsapp(
  p_whatsapp_number text,
  p_media_url text DEFAULT NULL,
  p_local_path text DEFAULT NULL,
  p_caption text DEFAULT NULL,
  p_media_type text DEFAULT 'image',
  p_media_id text DEFAULT NULL,
  p_original_filename text DEFAULT NULL,
  p_pedido_id integer DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_norm_number text;
  v_cliente_id integer;
  v_pedido_id integer;
  v_proof_id integer;
  v_pedido_num text;
  v_reply text;
BEGIN
  v_norm_number := regexp_replace(COALESCE(p_whatsapp_number, ''), '\D', '', 'g');

  IF v_norm_number = '' THEN
    RAISE EXCEPTION 'p_whatsapp_number is required';
  END IF;

  SELECT id
  INTO v_cliente_id
  FROM api.clientes_whatsapp
  WHERE regexp_replace(COALESCE(whatsapp_number, ''), '\D', '', 'g') = v_norm_number
  ORDER BY id DESC
  LIMIT 1;

  IF p_pedido_id IS NOT NULL THEN
    v_pedido_id := p_pedido_id;
  ELSE
    SELECT p.id
    INTO v_pedido_id
    FROM api.pedidos p
    WHERE (v_cliente_id IS NOT NULL AND p.cliente_id = v_cliente_id)
      AND COALESCE(p.estado, '') NOT IN ('CANCELADO', 'CANCELLED', 'ENTREGADO', 'DELIVERED')
    ORDER BY p.id DESC
    LIMIT 1;
  END IF;

  IF v_pedido_id IS NULL THEN
    SELECT p.id
    INTO v_pedido_id
    FROM api.pedidos p
    WHERE COALESCE(p.estado, '') NOT IN ('CANCELADO', 'CANCELLED', 'ENTREGADO', 'DELIVERED')
    ORDER BY p.id DESC
    LIMIT 1;
  END IF;

  IF v_pedido_id IS NULL THEN
    RAISE EXCEPTION 'No active pedido found for WhatsApp number %', p_whatsapp_number;
  END IF;

  INSERT INTO api.pedido_payment_proofs (
    pedido_id,
    cliente_id,
    whatsapp_number,
    media_type,
    media_id,
    media_url,
    local_path,
    original_filename,
    caption,
    status
  ) VALUES (
    v_pedido_id,
    v_cliente_id,
    v_norm_number,
    COALESCE(NULLIF(p_media_type, ''), 'image'),
    p_media_id,
    p_media_url,
    p_local_path,
    p_original_filename,
    p_caption,
    'RECEIVED'
  )
  RETURNING id INTO v_proof_id;

  UPDATE api.pedidos
  SET payment_status = 'PROOF_RECEIVED',
      payment_proof_required = true,
      payment_notes = COALESCE(payment_notes, '') || CASE WHEN COALESCE(payment_notes, '') = '' THEN '' ELSE E'\n' END || 'Comprobante recibido por WhatsApp.'
  WHERE id = v_pedido_id;

  SELECT pedido_num INTO v_pedido_num
  FROM api.pedidos
  WHERE id = v_pedido_id;

  v_reply := 'Recibí tu comprobante de pago ✅' || E'\n\n' ||
             'Pedido: ' || COALESCE(v_pedido_num, v_pedido_id::text) || E'\n' ||
             'Lo enviaremos a revisión. Te avisaremos cuando sea verificado.';

  RETURN jsonb_build_object(
    'ok', true,
    'proof_id', v_proof_id,
    'pedido_id', v_pedido_id,
    'pedido_num', v_pedido_num,
    'cliente_id', v_cliente_id,
    'payment_status', 'PROOF_RECEIVED',
    'whatsapp_reply_text', v_reply
  );
END;
$$;

-- 6) RPC: review/verify/reject payment proof.
CREATE OR REPLACE FUNCTION api.revisar_comprobante_pago(
  p_proof_id integer,
  p_status text,
  p_verified_by text DEFAULT 'logistica',
  p_notes text DEFAULT NULL,
  p_notify boolean DEFAULT true
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_proof api.pedido_payment_proofs%ROWTYPE;
  v_pedido api.pedidos%ROWTYPE;
  v_cliente_id integer;
  v_whatsapp_number text;
  v_event_type text;
  v_message text;
  v_outbox_id integer;
BEGIN
  IF p_status NOT IN ('VERIFIED', 'REJECTED', 'CANCELLED') THEN
    RAISE EXCEPTION 'Invalid proof status: %', p_status;
  END IF;

  SELECT * INTO v_proof
  FROM api.pedido_payment_proofs
  WHERE id = p_proof_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Payment proof id % not found', p_proof_id;
  END IF;

  UPDATE api.pedido_payment_proofs
  SET status = p_status,
      verified_by = p_verified_by,
      verified_at = CASE WHEN p_status IN ('VERIFIED', 'REJECTED') THEN now() ELSE verified_at END,
      review_notes = p_notes
  WHERE id = p_proof_id
  RETURNING * INTO v_proof;

  SELECT * INTO v_pedido
  FROM api.pedidos
  WHERE id = v_proof.pedido_id;

  IF FOUND THEN
    UPDATE api.pedidos
    SET payment_status = CASE
          WHEN p_status = 'VERIFIED' THEN 'PAID_VERIFIED'
          WHEN p_status = 'REJECTED' THEN 'PAYMENT_REJECTED'
          ELSE payment_status
        END,
        payment_verified_at = CASE WHEN p_status = 'VERIFIED' THEN now() ELSE payment_verified_at END,
        payment_verified_by = CASE WHEN p_status = 'VERIFIED' THEN p_verified_by ELSE payment_verified_by END,
        payment_notes = p_notes
    WHERE id = v_proof.pedido_id
    RETURNING * INTO v_pedido;
  END IF;

  v_cliente_id := v_proof.cliente_id;
  v_whatsapp_number := v_proof.whatsapp_number;

  IF p_status = 'VERIFIED' THEN
    v_event_type := 'PAYMENT_VERIFIED';
    v_message := 'Tu pago fue verificado ✅' || E'\n\n' ||
                 'Pedido: ' || COALESCE(v_pedido.pedido_num, v_proof.pedido_id::text) || E'\n' ||
                 'Gracias. Continuaremos con tu pedido.';
  ELSIF p_status = 'REJECTED' THEN
    v_event_type := 'PAYMENT_REJECTED';
    v_message := 'No pudimos verificar tu comprobante de pago ⚠️' || E'\n\n' ||
                 'Pedido: ' || COALESCE(v_pedido.pedido_num, v_proof.pedido_id::text) || E'\n' ||
                 COALESCE(NULLIF(p_notes, ''), 'Por favor envía un nuevo comprobante o comunícate con logística.');
  ELSE
    v_event_type := 'PAYMENT_CANCELLED';
    v_message := 'El comprobante de pago fue cancelado para revisión interna.';
  END IF;

  IF p_notify AND p_status IN ('VERIFIED', 'REJECTED') THEN
    INSERT INTO api.whatsapp_outbox (
      pedido_id,
      cliente_id,
      whatsapp_number,
      event_type,
      message_text,
      status
    ) VALUES (
      v_proof.pedido_id,
      v_cliente_id,
      v_whatsapp_number,
      v_event_type,
      v_message,
      'PENDING'
    )
    RETURNING id INTO v_outbox_id;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'proof_id', p_proof_id,
    'proof_status', p_status,
    'pedido_id', v_proof.pedido_id,
    'pedido_num', v_pedido.pedido_num,
    'payment_status', v_pedido.payment_status,
    'notify', p_notify,
    'outbox_id', v_outbox_id
  );
END;
$$;

GRANT SELECT, INSERT, UPDATE ON api.pedido_payment_proofs TO web_anon;
GRANT SELECT ON api.v_payment_proofs_logistica TO web_anon;
GRANT EXECUTE ON FUNCTION api.marcar_pago_requiere_comprobante(integer, boolean, text) TO web_anon;
GRANT EXECUTE ON FUNCTION api.registrar_comprobante_pago_whatsapp(text, text, text, text, text, text, text, integer) TO web_anon;
GRANT EXECUTE ON FUNCTION api.revisar_comprobante_pago(integer, text, text, text, boolean) TO web_anon;

NOTIFY pgrst, 'reload schema';

COMMIT;
