BEGIN;

CREATE SCHEMA IF NOT EXISTS api;

CREATE TABLE IF NOT EXISTS api.payment_fulfillments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id integer NOT NULL UNIQUE REFERENCES api.pedidos(id) ON DELETE RESTRICT,
  payment_method text NOT NULL,
  expected_amount numeric(12,2) NOT NULL CHECK (expected_amount >= 0),
  received_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (received_amount >= 0),
  refunded_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (refunded_amount >= 0),
  status text NOT NULL,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  last_actor text NOT NULL DEFAULT 'system',
  last_note text,
  verified_at timestamptz,
  released_at timestamptz,
  reconciled_at timestamptz,
  settled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT payment_fulfillments_status_check CHECK (status = ANY (ARRAY[
    'PAYMENT_REQUESTED', 'PROOF_REQUIRED', 'UNDER_REVIEW', 'VERIFIED',
    'RELEASED', 'COD_DUE', 'COD_COLLECTED', 'RECONCILED', 'SETTLED',
    'REJECTED', 'REFUND_PENDING', 'PARTIALLY_REFUNDED', 'REFUNDED', 'CANCELLED'
  ])),
  CONSTRAINT payment_fulfillments_amounts_check CHECK (refunded_amount <= received_amount)
);

CREATE INDEX IF NOT EXISTS idx_payment_fulfillments_status
  ON api.payment_fulfillments(status, updated_at);

DROP TRIGGER IF EXISTS set_updated_at_payment_fulfillments ON api.payment_fulfillments;
CREATE TRIGGER set_updated_at_payment_fulfillments
BEFORE UPDATE ON api.payment_fulfillments
FOR EACH ROW EXECUTE FUNCTION api.set_updated_at();

CREATE TABLE IF NOT EXISTS api.payment_fulfillment_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fulfillment_id bigint NOT NULL REFERENCES api.payment_fulfillments(id) ON DELETE RESTRICT,
  pedido_id integer NOT NULL REFERENCES api.pedidos(id) ON DELETE RESTRICT,
  event_type text NOT NULL,
  from_status text,
  to_status text NOT NULL,
  amount numeric(12,2),
  actor text NOT NULL,
  note text,
  source text NOT NULL DEFAULT 'payment_fulfillment',
  source_reference text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_payment_fulfillment_events_fulfillment
  ON api.payment_fulfillment_events(fulfillment_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_payment_fulfillment_events_pedido
  ON api.payment_fulfillment_events(pedido_id, id DESC);

CREATE OR REPLACE FUNCTION api.reject_payment_event_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'payment_fulfillment_events is append-only';
END;
$$;

DROP TRIGGER IF EXISTS payment_fulfillment_events_append_only
  ON api.payment_fulfillment_events;
CREATE TRIGGER payment_fulfillment_events_append_only
BEFORE UPDATE OR DELETE ON api.payment_fulfillment_events
FOR EACH ROW EXECUTE FUNCTION api.reject_payment_event_mutation();

CREATE OR REPLACE FUNCTION api.payment_initial_fulfillment_status(
  p_method text,
  p_payment_status text
)
RETURNS text
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT CASE upper(COALESCE(p_payment_status, ''))
    WHEN 'PROOF_REQUIRED' THEN 'PROOF_REQUIRED'
    WHEN 'PROOF_RECEIVED' THEN 'UNDER_REVIEW'
    WHEN 'PAID_VERIFIED' THEN 'VERIFIED'
    WHEN 'PAYMENT_REJECTED' THEN 'REJECTED'
    WHEN 'PAYMENT_ON_DELIVERY' THEN 'COD_DUE'
    ELSE CASE WHEN upper(COALESCE(p_method, '')) = 'CONTRA_ENTREGA'
      THEN 'COD_DUE' ELSE 'PAYMENT_REQUESTED' END
  END
$$;

CREATE OR REPLACE FUNCTION api.ensure_payment_fulfillment(p_pedido_id integer)
RETURNS api.payment_fulfillments
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
  v_order api.pedidos%ROWTYPE;
  v_result api.payment_fulfillments%ROWTYPE;
BEGIN
  SELECT * INTO v_order FROM api.pedidos WHERE id = p_pedido_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pedido id % not found', p_pedido_id;
  END IF;

  INSERT INTO api.payment_fulfillments (
    pedido_id, payment_method, expected_amount, status, last_actor, last_note
  ) VALUES (
    v_order.id,
    v_order.metodo_pago,
    v_order.total,
    api.payment_initial_fulfillment_status(v_order.metodo_pago, v_order.payment_status),
    'system',
    'Created from order payment state'
  )
  ON CONFLICT (pedido_id) DO UPDATE SET
    payment_method = EXCLUDED.payment_method,
    expected_amount = EXCLUDED.expected_amount
  RETURNING * INTO v_result;

  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION api.payment_transition_allowed(p_from text, p_to text)
RETURNS boolean
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT p_from = p_to OR (p_from, p_to) IN (
    ('PAYMENT_REQUESTED','PROOF_REQUIRED'),
    ('PAYMENT_REQUESTED','UNDER_REVIEW'),
    ('PAYMENT_REQUESTED','VERIFIED'),
    ('PAYMENT_REQUESTED','CANCELLED'),
    ('PROOF_REQUIRED','UNDER_REVIEW'),
    ('PROOF_REQUIRED','CANCELLED'),
    ('UNDER_REVIEW','VERIFIED'),
    ('UNDER_REVIEW','REJECTED'),
    ('UNDER_REVIEW','CANCELLED'),
    ('REJECTED','PROOF_REQUIRED'),
    ('REJECTED','UNDER_REVIEW'),
    ('REJECTED','CANCELLED'),
    ('VERIFIED','RELEASED'),
    ('VERIFIED','RECONCILED'),
    ('VERIFIED','REFUND_PENDING'),
    ('RELEASED','RECONCILED'),
    ('RELEASED','REFUND_PENDING'),
    ('COD_DUE','COD_COLLECTED'),
    ('COD_DUE','CANCELLED'),
    ('COD_COLLECTED','RECONCILED'),
    ('COD_COLLECTED','REFUND_PENDING'),
    ('RECONCILED','SETTLED'),
    ('RECONCILED','REFUND_PENDING'),
    ('SETTLED','REFUND_PENDING'),
    ('REFUND_PENDING','PARTIALLY_REFUNDED'),
    ('REFUND_PENDING','REFUNDED'),
    ('PARTIALLY_REFUNDED','REFUND_PENDING'),
    ('PARTIALLY_REFUNDED','REFUNDED')
  )
$$;

CREATE OR REPLACE FUNCTION api.transition_payment_fulfillment(
  p_pedido_id integer,
  p_to_status text,
  p_actor text,
  p_note text DEFAULT NULL,
  p_amount numeric DEFAULT NULL,
  p_expected_version integer DEFAULT NULL,
  p_source text DEFAULT 'manual',
  p_source_reference text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
  v_row api.payment_fulfillments%ROWTYPE;
  v_from text;
  v_to text := upper(trim(COALESCE(p_to_status, '')));
  v_actor text := trim(COALESCE(p_actor, ''));
BEGIN
  IF v_actor = '' THEN RAISE EXCEPTION 'p_actor is required'; END IF;
  PERFORM api.ensure_payment_fulfillment(p_pedido_id);

  SELECT * INTO v_row FROM api.payment_fulfillments
  WHERE pedido_id = p_pedido_id FOR UPDATE;
  v_from := v_row.status;

  IF p_expected_version IS NOT NULL AND p_expected_version <> v_row.version THEN
    RAISE EXCEPTION 'Stale payment fulfillment version: expected %, current %',
      p_expected_version, v_row.version;
  END IF;
  IF NOT api.payment_transition_allowed(v_from, v_to) THEN
    RAISE EXCEPTION 'Invalid payment fulfillment transition: % -> %', v_from, v_to;
  END IF;
  IF p_amount IS NOT NULL AND p_amount < 0 THEN
    RAISE EXCEPTION 'p_amount cannot be negative';
  END IF;
  IF v_to IN ('VERIFIED','COD_COLLECTED') AND COALESCE(p_amount, v_row.expected_amount) <= 0 THEN
    RAISE EXCEPTION 'A positive collected amount is required for %', v_to;
  END IF;
  IF v_to IN ('PARTIALLY_REFUNDED','REFUNDED') AND p_amount IS NULL THEN
    RAISE EXCEPTION 'p_amount is required for refunds';
  END IF;
  IF v_to IN ('PARTIALLY_REFUNDED','REFUNDED')
     AND v_row.refunded_amount + p_amount > v_row.received_amount THEN
    RAISE EXCEPTION 'Refund exceeds received amount';
  END IF;

  UPDATE api.payment_fulfillments SET
    status = v_to,
    received_amount = CASE WHEN v_to IN ('VERIFIED','COD_COLLECTED')
      THEN COALESCE(p_amount, expected_amount) ELSE received_amount END,
    refunded_amount = CASE WHEN v_to IN ('PARTIALLY_REFUNDED','REFUNDED')
      THEN refunded_amount + p_amount ELSE refunded_amount END,
    verified_at = CASE WHEN v_to IN ('VERIFIED','COD_COLLECTED') THEN now() ELSE verified_at END,
    released_at = CASE WHEN v_to = 'RELEASED' THEN now() ELSE released_at END,
    reconciled_at = CASE WHEN v_to = 'RECONCILED' THEN now() ELSE reconciled_at END,
    settled_at = CASE WHEN v_to = 'SETTLED' THEN now() ELSE settled_at END,
    version = version + 1,
    last_actor = v_actor,
    last_note = p_note
  WHERE id = v_row.id
  RETURNING * INTO v_row;

  INSERT INTO api.payment_fulfillment_events (
    fulfillment_id, pedido_id, event_type, from_status, to_status, amount,
    actor, note, source, source_reference, metadata
  ) VALUES (
    v_row.id, v_row.pedido_id, 'STATUS_CHANGED', v_from, v_to, p_amount,
    v_actor, p_note, COALESCE(NULLIF(p_source,''),'manual'), p_source_reference,
    COALESCE(p_metadata, '{}'::jsonb)
  );

  RETURN jsonb_build_object(
    'ok', true, 'fulfillment_id', v_row.id, 'pedido_id', v_row.pedido_id,
    'from_status', v_from, 'status', v_row.status, 'version', v_row.version,
    'expected_amount', v_row.expected_amount, 'received_amount', v_row.received_amount,
    'refunded_amount', v_row.refunded_amount
  );
END;
$$;

CREATE OR REPLACE FUNCTION api.sync_payment_fulfillment_from_order()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
  v_row api.payment_fulfillments%ROWTYPE;
  v_target text;
BEGIN
  v_row := api.ensure_payment_fulfillment(NEW.id);
  v_target := api.payment_initial_fulfillment_status(NEW.metodo_pago, NEW.payment_status);

  IF v_target <> v_row.status AND api.payment_transition_allowed(v_row.status, v_target) THEN
    PERFORM api.transition_payment_fulfillment(
      NEW.id, v_target, COALESCE(NEW.payment_verified_by, 'system'), NEW.payment_notes,
      CASE WHEN v_target IN ('VERIFIED','COD_COLLECTED') THEN NEW.total ELSE NULL END,
      v_row.version, 'pedidos.payment_status', NEW.payment_status, '{}'::jsonb
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS sync_payment_fulfillment_from_order ON api.pedidos;
CREATE TRIGGER sync_payment_fulfillment_from_order
AFTER INSERT OR UPDATE OF payment_status, metodo_pago, total ON api.pedidos
FOR EACH ROW EXECUTE FUNCTION api.sync_payment_fulfillment_from_order();

CREATE OR REPLACE FUNCTION api.audit_payment_proof_fulfillment_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
  v_fulfillment api.payment_fulfillments%ROWTYPE;
BEGIN
  v_fulfillment := api.ensure_payment_fulfillment(NEW.pedido_id);
  IF TG_OP = 'INSERT' OR NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO api.payment_fulfillment_events (
      fulfillment_id, pedido_id, event_type, from_status, to_status, actor,
      note, source, source_reference, metadata
    ) VALUES (
      v_fulfillment.id, NEW.pedido_id, 'PROOF_' || NEW.status,
      v_fulfillment.status, v_fulfillment.status,
      COALESCE(NULLIF(NEW.verified_by,''), 'system'), NEW.review_notes,
      'pedido_payment_proofs', NEW.id::text,
      jsonb_build_object('proof_id', NEW.id, 'proof_status', NEW.status)
    );
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS audit_payment_proof_fulfillment_event
  ON api.pedido_payment_proofs;
CREATE TRIGGER audit_payment_proof_fulfillment_event
AFTER INSERT OR UPDATE OF status ON api.pedido_payment_proofs
FOR EACH ROW EXECUTE FUNCTION api.audit_payment_proof_fulfillment_event();

INSERT INTO api.payment_fulfillments (
  pedido_id, payment_method, expected_amount, received_amount, status,
  last_actor, last_note, verified_at
)
SELECT
  p.id, p.metodo_pago, p.total,
  CASE WHEN p.payment_status = 'PAID_VERIFIED' THEN p.total ELSE 0 END,
  api.payment_initial_fulfillment_status(p.metodo_pago, p.payment_status),
  COALESCE(NULLIF(p.payment_verified_by,''), 'migration'),
  'Backfilled from existing order payment state', p.payment_verified_at
FROM api.pedidos p
ON CONFLICT (pedido_id) DO NOTHING;

INSERT INTO api.payment_fulfillment_events (
  fulfillment_id, pedido_id, event_type, from_status, to_status, amount,
  actor, note, source, source_reference
)
SELECT f.id, f.pedido_id, 'BACKFILLED', NULL, f.status,
  CASE WHEN f.received_amount > 0 THEN f.received_amount ELSE NULL END,
  'migration', 'Created from existing order payment state', 'migration', 'add_payment_fulfillment.sql'
FROM api.payment_fulfillments f
WHERE NOT EXISTS (
  SELECT 1 FROM api.payment_fulfillment_events e WHERE e.fulfillment_id = f.id
);

CREATE OR REPLACE VIEW api.v_payment_fulfillments AS
SELECT
  f.*, p.pedido_num, p.estado AS pedido_estado, p.payment_status AS legacy_payment_status,
  COALESCE(c.nombre, '') AS cliente_nombre
FROM api.payment_fulfillments f
JOIN api.pedidos p ON p.id = f.pedido_id
LEFT JOIN api.clientes_whatsapp c ON c.id = p.cliente_id;

GRANT SELECT ON api.payment_fulfillments, api.payment_fulfillment_events,
  api.v_payment_fulfillments TO web_anon;
GRANT EXECUTE ON FUNCTION api.ensure_payment_fulfillment(integer) TO web_anon;
GRANT EXECUTE ON FUNCTION api.transition_payment_fulfillment(integer, text, text, text, numeric, integer, text, text, jsonb) TO web_anon;

NOTIFY pgrst, 'reload schema';
COMMIT;
