BEGIN;

ALTER TABLE api.pedidos
  ADD COLUMN IF NOT EXISTS kitchen_version integer NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS api.kitchen_order_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id integer NOT NULL REFERENCES api.pedidos(id) ON DELETE RESTRICT,
  event_type text NOT NULL,
  from_status text,
  to_status text,
  kitchen_version integer NOT NULL,
  actor text NOT NULL,
  notes text,
  idempotency_key text UNIQUE,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_kitchen_events_order
  ON api.kitchen_order_events(pedido_id, id DESC);

CREATE TABLE IF NOT EXISTS api.kitchen_board_acknowledgements (
  pedido_id integer PRIMARY KEY REFERENCES api.pedidos(id) ON DELETE CASCADE,
  acknowledged_version integer NOT NULL,
  actor text NOT NULL,
  reason text,
  acknowledged_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION api.reject_kitchen_event_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'kitchen_order_events is append-only';
END $$;
DROP TRIGGER IF EXISTS kitchen_order_events_append_only ON api.kitchen_order_events;
CREATE TRIGGER kitchen_order_events_append_only
BEFORE UPDATE OR DELETE ON api.kitchen_order_events
FOR EACH ROW EXECUTE FUNCTION api.reject_kitchen_event_mutation();

CREATE OR REPLACE FUNCTION api.transition_kitchen_order(
  p_pedido_id integer,
  p_target_status text,
  p_expected_version integer,
  p_actor text DEFAULT 'kitchen_ui',
  p_notes text DEFAULT NULL,
  p_notify boolean DEFAULT true,
  p_idempotency_key text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE
  v_order api.pedidos%ROWTYPE;
  v_target text := upper(trim(coalesce(p_target_status,'')));
  v_payment_status text;
  v_event_id bigint;
  v_message jsonb;
  v_outbox jsonb;
BEGIN
  IF p_idempotency_key IS NOT NULL THEN
    SELECT id INTO v_event_id FROM api.kitchen_order_events
      WHERE idempotency_key=p_idempotency_key;
    IF v_event_id IS NOT NULL THEN
      RETURN jsonb_build_object('ok',true,'duplicate',true,'event_id',v_event_id);
    END IF;
  END IF;

  SELECT * INTO v_order FROM api.pedidos WHERE id=p_pedido_id FOR UPDATE;
  IF v_order.id IS NULL THEN
    RETURN jsonb_build_object('ok',false,'error','Pedido not found');
  END IF;
  IF p_expected_version IS NULL OR p_expected_version <> v_order.kitchen_version THEN
    RETURN jsonb_build_object('ok',false,'error','STALE_KITCHEN_VERSION',
      'expected_version',p_expected_version,'current_version',v_order.kitchen_version);
  END IF;
  IF v_target NOT IN ('NUEVO','EN_PREPARACION','LISTO','ENTREGADO','ANULADO') THEN
    RETURN jsonb_build_object('ok',false,'error','Invalid kitchen status');
  END IF;
  IF NOT (
    (v_order.kitchen_status='NUEVO' AND v_target IN ('EN_PREPARACION','ANULADO')) OR
    (v_order.kitchen_status='EN_PREPARACION' AND v_target IN ('NUEVO','LISTO','ANULADO')) OR
    (v_order.kitchen_status='LISTO' AND v_target IN ('EN_PREPARACION','ENTREGADO','ANULADO'))
  ) THEN
    RETURN jsonb_build_object('ok',false,'error','Invalid kitchen transition',
      'from_status',v_order.kitchen_status,'to_status',v_target);
  END IF;

  IF v_target='EN_PREPARACION' THEN
    SELECT status INTO v_payment_status FROM api.payment_fulfillments
      WHERE pedido_id=p_pedido_id;
    IF v_payment_status IS NULL OR v_payment_status NOT IN
      ('RELEASED','COD_DUE','COD_COLLECTED','RECONCILED','SETTLED') THEN
      RETURN jsonb_build_object('ok',false,'error','PAYMENT_NOT_READY',
        'payment_status',v_payment_status);
    END IF;
  END IF;

  UPDATE api.pedidos SET
    kitchen_status=v_target,
    kitchen_version=kitchen_version+1,
    kitchen_started_at=CASE WHEN v_target='EN_PREPARACION'
      THEN coalesce(kitchen_started_at,now()) ELSE kitchen_started_at END,
    kitchen_ready_at=CASE WHEN v_target='LISTO' THEN now()
      WHEN v_target IN ('NUEVO','EN_PREPARACION') THEN NULL ELSE kitchen_ready_at END,
    kitchen_notes=coalesce(p_notes,kitchen_notes),
    estado=CASE WHEN v_target='EN_PREPARACION' AND estado='CONFIRMADO' THEN 'EN_PREPARACION'
      WHEN v_target='ENTREGADO' THEN 'ENTREGADO'
      WHEN v_target='ANULADO' THEN 'ANULADO' ELSE estado END,
    updated_at=now()
  WHERE id=p_pedido_id;

  INSERT INTO api.kitchen_order_events
    (pedido_id,event_type,from_status,to_status,kitchen_version,actor,notes,idempotency_key)
  VALUES (p_pedido_id,'STATUS_TRANSITION',v_order.kitchen_status,v_target,
    v_order.kitchen_version+1,coalesce(nullif(trim(p_actor),''),'kitchen_ui'),
    p_notes,p_idempotency_key) RETURNING id INTO v_event_id;

  IF p_notify AND to_regprocedure('api.build_kitchen_whatsapp_message(integer,text)') IS NOT NULL THEN
    v_message := api.build_kitchen_whatsapp_message(p_pedido_id,v_target);
    IF coalesce((v_message->>'ok')::boolean,false) THEN
      v_outbox := api.registrar_whatsapp_outbox(
        p_pedido_id,v_message->>'event_type',v_message->>'message_text');
    END IF;
  END IF;
  RETURN jsonb_build_object('ok',true,'pedido_id',p_pedido_id,
    'kitchen_status',v_target,'kitchen_version',v_order.kitchen_version+1,
    'event_id',v_event_id,'notification',v_outbox);
END $$;

CREATE OR REPLACE FUNCTION api.acknowledge_kitchen_order(
  p_pedido_id integer, p_expected_version integer,
  p_actor text DEFAULT 'kitchen_ui', p_reason text DEFAULT 'CLEARED_FROM_BOARD'
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE v_order api.pedidos%ROWTYPE; v_event_id bigint;
BEGIN
  SELECT * INTO v_order FROM api.pedidos WHERE id=p_pedido_id FOR UPDATE;
  IF v_order.id IS NULL THEN RETURN jsonb_build_object('ok',false,'error','Pedido not found'); END IF;
  IF p_expected_version IS NULL OR p_expected_version<>v_order.kitchen_version THEN
    RETURN jsonb_build_object('ok',false,'error','STALE_KITCHEN_VERSION',
      'current_version',v_order.kitchen_version);
  END IF;
  INSERT INTO api.kitchen_board_acknowledgements
    (pedido_id,acknowledged_version,actor,reason,acknowledged_at)
  VALUES (p_pedido_id,v_order.kitchen_version,p_actor,p_reason,now())
  ON CONFLICT (pedido_id) DO UPDATE SET
    acknowledged_version=excluded.acknowledged_version,actor=excluded.actor,
    reason=excluded.reason,acknowledged_at=excluded.acknowledged_at;
  INSERT INTO api.kitchen_order_events
    (pedido_id,event_type,from_status,to_status,kitchen_version,actor,notes)
  VALUES (p_pedido_id,'BOARD_ACKNOWLEDGED',v_order.kitchen_status,
    v_order.kitchen_status,v_order.kitchen_version,p_actor,p_reason)
  RETURNING id INTO v_event_id;
  RETURN jsonb_build_object('ok',true,'pedido_id',p_pedido_id,'event_id',v_event_id);
END $$;

-- Compatibility wrapper for existing integrations.
CREATE OR REPLACE FUNCTION api.update_kitchen_status(
  p_pedido_id integer, p_kitchen_status text,
  p_kitchen_notes text DEFAULT NULL, p_notify boolean DEFAULT true
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=api,public AS $$
DECLARE v_version integer;
BEGIN
  SELECT kitchen_version INTO v_version FROM api.pedidos WHERE id=p_pedido_id;
  RETURN api.transition_kitchen_order(p_pedido_id,p_kitchen_status,v_version,
    'legacy_kitchen_api',p_kitchen_notes,p_notify,
    'legacy:'||p_pedido_id||':'||coalesce(v_version,0)||':'||upper(trim(p_kitchen_status)));
END $$;

CREATE OR REPLACE VIEW api.v_kitchen_orders AS
WITH base AS (
 SELECT p.id,p.pedido_num,p.cliente_id,c.nombre cliente_nombre,c.whatsapp_number,
   p.estado,coalesce(p.kitchen_status,'NUEVO') kitchen_status,p.kitchen_version,
   p.total,p.created_at,p.updated_at,p.kitchen_started_at,p.kitchen_ready_at,
   p.kitchen_notes,p.observacion,
   coalesce(pd.direccion_confirmada,pd.direccion_detectada) direccion,p.metodo_pago,
   pf.status payment_fulfillment_status,
   (pf.status IN ('RELEASED','COD_DUE','COD_COLLECTED','RECONCILED','SETTLED')) payment_ready,
   extract(epoch from (now()-coalesce(
     CASE WHEN p.kitchen_status='EN_PREPARACION' THEN p.kitchen_started_at END,p.created_at)))/60 stage_minutes_raw,
   extract(epoch from (now()-p.created_at))/60 queue_minutes_raw
 FROM api.pedidos p
 LEFT JOIN api.clientes_whatsapp c ON c.id=p.cliente_id
 LEFT JOIN api.payment_fulfillments pf ON pf.pedido_id=p.id
 LEFT JOIN LATERAL (SELECT * FROM api.pedido_direcciones d WHERE d.pedido_id=p.id ORDER BY d.id DESC LIMIT 1) pd ON true
 LEFT JOIN api.kitchen_board_acknowledgements a ON a.pedido_id=p.id
 WHERE p.canal='WHATSAPP'
   AND (a.pedido_id IS NULL OR a.acknowledged_version<p.kitchen_version)
   AND ((coalesce(p.kitchen_status,'NUEVO')='NUEVO' AND p.estado='CONFIRMADO' AND p.created_at>=now()-interval '8 hours')
     OR (coalesce(p.kitchen_status,'NUEVO') IN ('EN_PREPARACION','LISTO') AND p.estado IN ('CONFIRMADO','EN_PREPARACION')))
)
SELECT
 id,pedido_num,cliente_id,cliente_nombre,whatsapp_number,estado,kitchen_status,
 total,created_at,updated_at,kitchen_started_at,kitchen_ready_at,kitchen_notes,
 direccion,metodo_pago,
 round(queue_minutes_raw::numeric,1) queue_minutes,
 CASE WHEN NOT payment_ready THEN 'BLOCKED' WHEN queue_minutes_raw>30 THEN 'RED'
   WHEN queue_minutes_raw>20 THEN 'YELLOW' ELSE 'GREEN' END queue_color,
 kitchen_version,observacion,payment_fulfillment_status,payment_ready,
 round(stage_minutes_raw::numeric,1) stage_minutes
FROM base ORDER BY created_at;

GRANT SELECT ON api.kitchen_order_events,api.kitchen_board_acknowledgements TO web_anon;
GRANT EXECUTE ON FUNCTION api.transition_kitchen_order(integer,text,integer,text,text,boolean,text) TO web_anon;
GRANT EXECUTE ON FUNCTION api.acknowledge_kitchen_order(integer,integer,text,text) TO web_anon;
GRANT EXECUTE ON FUNCTION api.update_kitchen_status(integer,text,text,boolean) TO web_anon;
NOTIFY pgrst,'reload schema';
COMMIT;
