BEGIN;

CREATE SCHEMA IF NOT EXISTS api;

-- =========================================================
-- KITCHEN WHATSAPP NOTIFICATIONS UPGRADE
--
-- Adds api.whatsapp_outbox and updates api.update_kitchen_status()
-- so kitchen status changes can create pending WhatsApp messages.
--
-- The worker sends PENDING rows later through OpenClaw.
-- =========================================================

CREATE TABLE IF NOT EXISTS api.whatsapp_outbox (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    pedido_id integer REFERENCES api.pedidos(id) ON DELETE SET NULL,
    cliente_id integer REFERENCES api.clientes_whatsapp(id) ON DELETE SET NULL,

    whatsapp_number text NOT NULL,
    message_text text NOT NULL,

    event_type text NOT NULL,
    status text NOT NULL DEFAULT 'PENDING',

    attempts integer NOT NULL DEFAULT 0,
    last_attempt_at timestamptz,
    sent_at timestamptz,
    error_message text,

    raw_response jsonb,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT whatsapp_outbox_status_check
    CHECK (status IN ('PENDING','SENDING','SENT','ERROR','CANCELLED')),

    CONSTRAINT whatsapp_outbox_event_type_check
    CHECK (event_type IN (
        'KITCHEN_EN_PREPARACION',
        'KITCHEN_LISTO',
        'KITCHEN_ENTREGADO',
        'KITCHEN_ANULADO',
        'CUSTOM'
    ))
);

CREATE INDEX IF NOT EXISTS idx_whatsapp_outbox_status
ON api.whatsapp_outbox(status);

CREATE INDEX IF NOT EXISTS idx_whatsapp_outbox_pedido
ON api.whatsapp_outbox(pedido_id);

CREATE INDEX IF NOT EXISTS idx_whatsapp_outbox_created_at
ON api.whatsapp_outbox(created_at);

CREATE INDEX IF NOT EXISTS idx_whatsapp_outbox_whatsapp_number
ON api.whatsapp_outbox(whatsapp_number);


CREATE OR REPLACE FUNCTION api.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_updated_at_whatsapp_outbox ON api.whatsapp_outbox;

CREATE TRIGGER set_updated_at_whatsapp_outbox
BEFORE UPDATE ON api.whatsapp_outbox
FOR EACH ROW
EXECUTE FUNCTION api.set_updated_at();


-- =========================================================
-- Helper: insert an outbox message
-- =========================================================

CREATE OR REPLACE FUNCTION api.registrar_whatsapp_outbox(
    p_pedido_id integer,
    p_event_type text,
    p_message_text text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
    v_order record;
    v_event_type text;
    v_outbox_id integer;
BEGIN
    v_event_type := upper(trim(COALESCE(p_event_type, 'CUSTOM')));

    IF v_event_type NOT IN (
        'KITCHEN_EN_PREPARACION',
        'KITCHEN_LISTO',
        'KITCHEN_ENTREGADO',
        'KITCHEN_ANULADO',
        'CUSTOM'
    ) THEN
        v_event_type := 'CUSTOM';
    END IF;

    SELECT
        p.id AS pedido_id,
        p.pedido_num,
        p.cliente_id,
        c.nombre AS cliente_nombre,
        c.whatsapp_number
    INTO v_order
    FROM api.pedidos p
    JOIN api.clientes_whatsapp c ON c.id = p.cliente_id
    WHERE p.id = p_pedido_id;

    IF v_order.pedido_id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'error', 'Pedido not found');
    END IF;

    IF v_order.whatsapp_number IS NULL OR trim(v_order.whatsapp_number) = '' THEN
        RETURN jsonb_build_object('ok', false, 'error', 'Customer has no whatsapp_number');
    END IF;

    IF p_message_text IS NULL OR trim(p_message_text) = '' THEN
        RETURN jsonb_build_object('ok', false, 'error', 'message_text is required');
    END IF;

    INSERT INTO api.whatsapp_outbox (
        pedido_id,
        cliente_id,
        whatsapp_number,
        message_text,
        event_type,
        status
    )
    VALUES (
        v_order.pedido_id,
        v_order.cliente_id,
        v_order.whatsapp_number,
        p_message_text,
        v_event_type,
        'PENDING'
    )
    RETURNING id INTO v_outbox_id;

    RETURN jsonb_build_object(
        'ok', true,
        'outbox_id', v_outbox_id,
        'pedido_id', v_order.pedido_id,
        'pedido_num', v_order.pedido_num,
        'whatsapp_number', v_order.whatsapp_number,
        'event_type', v_event_type,
        'status', 'PENDING'
    );
END;
$$;


-- =========================================================
-- Helper: build kitchen notification text
-- =========================================================

CREATE OR REPLACE FUNCTION api.build_kitchen_whatsapp_message(
    p_pedido_id integer,
    p_kitchen_status text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
    v_order record;
    v_status text;
    v_text text;
    v_event_type text;
BEGIN
    v_status := upper(trim(COALESCE(p_kitchen_status, '')));

    SELECT
        p.id AS pedido_id,
        p.pedido_num,
        p.total,
        p.order_url,
        c.nombre AS cliente_nombre,
        c.whatsapp_number
    INTO v_order
    FROM api.pedidos p
    JOIN api.clientes_whatsapp c ON c.id = p.cliente_id
    WHERE p.id = p_pedido_id;

    IF v_order.pedido_id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'error', 'Pedido not found');
    END IF;

    IF v_status = 'EN_PREPARACION' THEN
        v_event_type := 'KITCHEN_EN_PREPARACION';
        v_text :=
            'Tu pedido ' || v_order.pedido_num || ' ya está en preparación 👨‍🍳' || E'\n\n' ||
            'Te avisaremos cuando esté listo.';

    ELSIF v_status = 'LISTO' THEN
        v_event_type := 'KITCHEN_LISTO';
        v_text :=
            'Tu pedido ' || v_order.pedido_num || ' ya está listo ✅' || E'\n\n' ||
            'Gracias por esperar.';

    ELSIF v_status = 'ENTREGADO' THEN
        v_event_type := 'KITCHEN_ENTREGADO';
        v_text :=
            'Tu pedido ' || v_order.pedido_num || ' fue marcado como entregado ✅' || E'\n\n' ||
            'Gracias por tu compra.';

    ELSIF v_status = 'ANULADO' THEN
        v_event_type := 'KITCHEN_ANULADO';
        v_text :=
            'Tu pedido ' || v_order.pedido_num || ' fue anulado.' || E'\n\n' ||
            'Si necesitas ayuda, responde este mensaje.';

    ELSE
        RETURN jsonb_build_object(
            'ok', false,
            'skipped', true,
            'reason', 'No WhatsApp notification for this kitchen status',
            'status', v_status
        );
    END IF;

    RETURN jsonb_build_object(
        'ok', true,
        'pedido_id', v_order.pedido_id,
        'pedido_num', v_order.pedido_num,
        'whatsapp_number', v_order.whatsapp_number,
        'event_type', v_event_type,
        'message_text', v_text
    );
END;
$$;


-- =========================================================
-- Replace kitchen status update function.
-- Same first 3 parameters, plus optional p_notify.
-- Existing Kitchen UI still works.
-- =========================================================

CREATE OR REPLACE FUNCTION api.update_kitchen_status(
    p_pedido_id integer,
    p_kitchen_status text,
    p_kitchen_notes text DEFAULT NULL,
    p_notify boolean DEFAULT true
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
    v_new_status text;
    v_order record;
    v_msg jsonb;
    v_outbox jsonb;
BEGIN
    v_new_status := upper(trim(COALESCE(p_kitchen_status, '')));

    IF v_new_status NOT IN ('NUEVO','EN_PREPARACION','LISTO','ENTREGADO','ANULADO') THEN
        RETURN jsonb_build_object(
            'ok', false,
            'error', 'Invalid kitchen status',
            'allowed', jsonb_build_array('NUEVO','EN_PREPARACION','LISTO','ENTREGADO','ANULADO')
        );
    END IF;

    SELECT id, pedido_num, estado, kitchen_status
    INTO v_order
    FROM api.pedidos
    WHERE id = p_pedido_id;

    IF v_order.id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'error', 'Pedido not found');
    END IF;

    -- Avoid duplicate notifications if status did not change.
    IF v_order.kitchen_status IS NOT DISTINCT FROM v_new_status THEN
        UPDATE api.pedidos
        SET kitchen_notes = COALESCE(p_kitchen_notes, kitchen_notes),
            updated_at = now()
        WHERE id = p_pedido_id;

        RETURN jsonb_build_object(
            'ok', true,
            'pedido_id', p_pedido_id,
            'pedido_num', v_order.pedido_num,
            'kitchen_status', v_new_status,
            'status_changed', false,
            'notification_created', false
        );
    END IF;

    UPDATE api.pedidos
    SET
        kitchen_status = v_new_status,
        kitchen_started_at = CASE
            WHEN v_new_status = 'EN_PREPARACION' AND kitchen_started_at IS NULL THEN now()
            ELSE kitchen_started_at
        END,
        kitchen_ready_at = CASE
            WHEN v_new_status = 'LISTO' THEN now()
            WHEN v_new_status IN ('NUEVO','EN_PREPARACION') THEN NULL
            ELSE kitchen_ready_at
        END,
        kitchen_notes = COALESCE(p_kitchen_notes, kitchen_notes),
        estado = CASE
            WHEN v_new_status = 'EN_PREPARACION' AND estado = 'CONFIRMADO' THEN 'EN_PREPARACION'
            WHEN v_new_status = 'ENTREGADO' THEN 'ENTREGADO'
            WHEN v_new_status = 'ANULADO' THEN 'ANULADO'
            ELSE estado
        END,
        updated_at = now()
    WHERE id = p_pedido_id;

    v_outbox := NULL;

    IF p_notify THEN
        v_msg := api.build_kitchen_whatsapp_message(p_pedido_id, v_new_status);

        IF COALESCE((v_msg ->> 'ok')::boolean, false) THEN
            v_outbox := api.registrar_whatsapp_outbox(
                p_pedido_id,
                v_msg ->> 'event_type',
                v_msg ->> 'message_text'
            );
        ELSE
            v_outbox := v_msg;
        END IF;
    END IF;

    RETURN jsonb_build_object(
        'ok', true,
        'pedido_id', p_pedido_id,
        'pedido_num', v_order.pedido_num,
        'kitchen_status', v_new_status,
        'status_changed', true,
        'notification_created',
            CASE
                WHEN v_outbox IS NOT NULL AND COALESCE((v_outbox ->> 'ok')::boolean, false) THEN true
                ELSE false
            END,
        'notification', v_outbox
    );
END;
$$;


-- =========================================================
-- Views for monitoring
-- =========================================================

CREATE OR REPLACE VIEW api.v_whatsapp_outbox AS
SELECT
    o.id,
    o.pedido_id,
    p.pedido_num,
    o.cliente_id,
    c.nombre AS cliente_nombre,
    o.whatsapp_number,
    o.event_type,
    o.status,
    o.attempts,
    o.last_attempt_at,
    o.sent_at,
    o.error_message,
    o.message_text,
    o.created_at,
    o.updated_at
FROM api.whatsapp_outbox o
LEFT JOIN api.pedidos p ON p.id = o.pedido_id
LEFT JOIN api.clientes_whatsapp c ON c.id = o.cliente_id
ORDER BY o.created_at DESC;


GRANT SELECT, INSERT, UPDATE, DELETE
ON api.whatsapp_outbox
TO web_anon;

GRANT SELECT ON api.v_whatsapp_outbox TO web_anon;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA api
TO web_anon;

GRANT EXECUTE ON FUNCTION api.registrar_whatsapp_outbox(integer, text, text) TO web_anon;
GRANT EXECUTE ON FUNCTION api.build_kitchen_whatsapp_message(integer, text) TO web_anon;
GRANT EXECUTE ON FUNCTION api.update_kitchen_status(integer, text, text, boolean) TO web_anon;

NOTIFY pgrst, 'reload schema';

COMMIT;
