BEGIN;

CREATE TABLE IF NOT EXISTS api.driver_auth_credentials (
    driver_account_id integer PRIMARY KEY REFERENCES api.driver_accounts(id) ON DELETE CASCADE,
    pin_salt text NOT NULL,
    pin_hash text NOT NULL,
    credential_version integer NOT NULL DEFAULT 1 CHECK (credential_version > 0),
    failed_attempts integer NOT NULL DEFAULT 0 CHECK (failed_attempts >= 0),
    locked_until timestamptz,
    pin_changed_at timestamptz NOT NULL DEFAULT now(),
    last_login_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS api.driver_auth_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_account_id integer REFERENCES api.driver_accounts(id) ON DELETE SET NULL,
    event_type text NOT NULL CHECK (event_type IN (
        'PIN_SET',
        'LOGIN_SUCCEEDED',
        'LOGIN_FAILED',
        'LOGIN_LOCKED',
        'LOGOUT',
        'SESSION_REJECTED'
    )),
    success boolean NOT NULL,
    ip_hash text,
    user_agent text,
    detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_driver_auth_events_account_created
ON api.driver_auth_events(driver_account_id, created_at DESC);

CREATE OR REPLACE FUNCTION api.driver_record_auth_attempt(
    p_driver_account_id integer,
    p_success boolean,
    p_ip_hash text DEFAULT NULL,
    p_user_agent text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, pg_temp
AS $$
DECLARE
    v_credential api.driver_auth_credentials%ROWTYPE;
    v_now timestamptz := now();
    v_locked_until timestamptz;
    v_attempts integer;
BEGIN
    SELECT *
      INTO v_credential
      FROM api.driver_auth_credentials
     WHERE driver_account_id = p_driver_account_id
     FOR UPDATE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('ok', false, 'error', 'PIN_NOT_CONFIGURED');
    END IF;

    IF v_credential.locked_until IS NOT NULL AND v_credential.locked_until > v_now THEN
        INSERT INTO api.driver_auth_events(
            driver_account_id, event_type, success, ip_hash, user_agent, detail
        ) VALUES (
            p_driver_account_id, 'LOGIN_LOCKED', false, left(p_ip_hash, 128),
            left(p_user_agent, 300),
            jsonb_build_object('locked_until', v_credential.locked_until)
        );
        RETURN jsonb_build_object(
            'ok', false,
            'error', 'LOCKED',
            'locked_until', v_credential.locked_until
        );
    END IF;

    IF p_success THEN
        UPDATE api.driver_auth_credentials
           SET failed_attempts = 0,
               locked_until = NULL,
               last_login_at = v_now,
               updated_at = v_now
         WHERE driver_account_id = p_driver_account_id;
        INSERT INTO api.driver_auth_events(
            driver_account_id, event_type, success, ip_hash, user_agent
        ) VALUES (
            p_driver_account_id, 'LOGIN_SUCCEEDED', true, left(p_ip_hash, 128),
            left(p_user_agent, 300)
        );
        RETURN jsonb_build_object(
            'ok', true,
            'credential_version', v_credential.credential_version
        );
    END IF;

    v_attempts := v_credential.failed_attempts + 1;
    v_locked_until := CASE
        WHEN v_attempts >= 10 THEN v_now + interval '24 hours'
        WHEN v_attempts >= 5 THEN v_now + interval '15 minutes'
        ELSE NULL
    END;
    UPDATE api.driver_auth_credentials
       SET failed_attempts = v_attempts,
           locked_until = v_locked_until,
           updated_at = v_now
     WHERE driver_account_id = p_driver_account_id;
    INSERT INTO api.driver_auth_events(
        driver_account_id, event_type, success, ip_hash, user_agent, detail
    ) VALUES (
        p_driver_account_id,
        CASE WHEN v_locked_until IS NULL THEN 'LOGIN_FAILED' ELSE 'LOGIN_LOCKED' END,
        false,
        left(p_ip_hash, 128),
        left(p_user_agent, 300),
        jsonb_build_object('failed_attempts', v_attempts, 'locked_until', v_locked_until)
    );
    RETURN jsonb_build_object(
        'ok', false,
        'error', CASE WHEN v_locked_until IS NULL THEN 'INVALID_PIN' ELSE 'LOCKED' END,
        'failed_attempts', v_attempts,
        'locked_until', v_locked_until
    );
END;
$$;

CREATE OR REPLACE FUNCTION api.driver_write_auth_event(
    p_driver_account_id integer,
    p_event_type text,
    p_success boolean,
    p_ip_hash text DEFAULT NULL,
    p_user_agent text DEFAULT NULL,
    p_detail jsonb DEFAULT '{}'::jsonb
)
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, pg_temp
AS $$
DECLARE
    v_id bigint;
BEGIN
    IF p_event_type NOT IN ('PIN_SET', 'LOGOUT', 'SESSION_REJECTED') THEN
        RAISE EXCEPTION 'Unsupported direct auth event';
    END IF;
    INSERT INTO api.driver_auth_events(
        driver_account_id, event_type, success, ip_hash, user_agent, detail
    ) VALUES (
        p_driver_account_id, p_event_type, p_success, left(p_ip_hash, 128),
        left(p_user_agent, 300), COALESCE(p_detail, '{}'::jsonb)
    ) RETURNING id INTO v_id;
    RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION api.driver_record_auth_attempt(integer, boolean, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION api.driver_write_auth_event(integer, text, boolean, text, text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION api.driver_record_auth_attempt(integer, boolean, text, text) TO web_anon;
GRANT EXECUTE ON FUNCTION api.driver_write_auth_event(integer, text, boolean, text, text, jsonb) TO web_anon;
GRANT SELECT, INSERT, UPDATE ON api.driver_auth_credentials TO web_anon;
GRANT SELECT ON api.driver_auth_events TO web_anon;
GRANT USAGE, SELECT ON SEQUENCE api.driver_auth_events_id_seq TO web_anon;

NOTIFY pgrst, 'reload schema';
COMMIT;
