BEGIN;

CREATE SCHEMA IF NOT EXISTS api;

-- =========================================================
-- REPLAU DRIVER APP PHASE 1
-- Onboarding, verification evidence, online sessions,
-- locations, and nearby offer candidates.
-- Existing api.repartidores remains the operational dispatch table.
-- =========================================================

CREATE TABLE IF NOT EXISTS api.driver_accounts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repartidor_id integer UNIQUE REFERENCES api.repartidores(id) ON DELETE SET NULL,
    phone text NOT NULL UNIQUE,
    email text,
    legal_name text,
    date_of_birth date,
    status text NOT NULL DEFAULT 'CREATED',
    trust_tier text NOT NULL DEFAULT 'TIER_0_APPLICANT',
    risk_score integer NOT NULL DEFAULT 0,
    rejection_reason text,
    suspension_reason text,
    approved_at timestamptz,
    rejected_at timestamptz,
    suspended_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT driver_accounts_status_check CHECK (status IN (
        'CREATED',
        'PHONE_VERIFIED',
        'CONSENTED',
        'IDENTITY_PENDING',
        'IDENTITY_VERIFIED',
        'LICENSE_PENDING',
        'LICENSE_VERIFIED',
        'VEHICLE_PENDING',
        'VEHICLE_VERIFIED',
        'PAYOUT_PENDING',
        'PAYOUT_VERIFIED',
        'APPROVED',
        'ACTIVE',
        'SUSPENDED',
        'REJECTED',
        'DELETED'
    )),
    CONSTRAINT driver_accounts_trust_tier_check CHECK (trust_tier IN (
        'TIER_0_APPLICANT',
        'TIER_1_PHONE_ID_VERIFIED',
        'TIER_2_LICENSE_VEHICLE_SUBMITTED',
        'TIER_3_FULLY_VERIFIED',
        'TIER_4_TRUSTED',
        'TIER_5_RESTRICTED'
    )),
    CONSTRAINT driver_accounts_phone_check CHECK (phone ~ '^[0-9]{8,20}$')
);

CREATE INDEX IF NOT EXISTS idx_driver_accounts_status
ON api.driver_accounts(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_driver_accounts_repartidor
ON api.driver_accounts(repartidor_id);

CREATE TABLE IF NOT EXISTS api.driver_consents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_account_id integer NOT NULL REFERENCES api.driver_accounts(id) ON DELETE CASCADE,
    consent_type text NOT NULL,
    version text NOT NULL,
    accepted boolean NOT NULL DEFAULT false,
    accepted_at timestamptz,
    ip_address text,
    user_agent text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT driver_consents_type_check CHECK (consent_type IN (
        'TERMS',
        'PRIVACY',
        'LOCATION',
        'BIOMETRIC',
        'BACKGROUND_CHECK',
        'PAYOUT'
    )),
    CONSTRAINT driver_consents_unique UNIQUE (driver_account_id, consent_type, version)
);

CREATE TABLE IF NOT EXISTS api.driver_documents (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_account_id integer NOT NULL REFERENCES api.driver_accounts(id) ON DELETE CASCADE,
    document_type text NOT NULL,
    storage_key text NOT NULL,
    sha256 text NOT NULL,
    content_type text,
    original_filename text,
    byte_size integer,
    ocr_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    extracted_name text,
    extracted_document_number text,
    extracted_expiry_date date,
    status text NOT NULL DEFAULT 'SUBMITTED',
    review_notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT driver_documents_type_check CHECK (document_type IN (
        'GOV_ID_FRONT',
        'GOV_ID_BACK',
        'SELFIE',
        'LIVENESS_VIDEO',
        'LICENSE_FRONT',
        'LICENSE_BACK',
        'VEHICLE_REGISTRATION',
        'VEHICLE_PHOTO_FRONT',
        'VEHICLE_PHOTO_REAR',
        'VEHICLE_PHOTO_LEFT',
        'VEHICLE_PHOTO_RIGHT',
        'INSURANCE',
        'PAYOUT_PROOF',
        'OTHER'
    )),
    CONSTRAINT driver_documents_status_check CHECK (status IN (
        'SUBMITTED',
        'OCR_PENDING',
        'OCR_COMPLETE',
        'PASSED',
        'FAILED',
        'REVIEW_REQUIRED',
        'REPLACED'
    ))
);

CREATE INDEX IF NOT EXISTS idx_driver_documents_account_type
ON api.driver_documents(driver_account_id, document_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_driver_documents_sha256
ON api.driver_documents(sha256);

CREATE TABLE IF NOT EXISTS api.driver_verification_checks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_account_id integer NOT NULL REFERENCES api.driver_accounts(id) ON DELETE CASCADE,
    document_id integer REFERENCES api.driver_documents(id) ON DELETE SET NULL,
    check_type text NOT NULL,
    provider text NOT NULL DEFAULT 'replau_manual',
    provider_check_id text,
    status text NOT NULL DEFAULT 'PENDING',
    score numeric(7,4),
    reason_code text,
    summary_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    raw_payload_storage_key text,
    created_at timestamptz NOT NULL DEFAULT now(),
    completed_at timestamptz,
    CONSTRAINT driver_verification_checks_status_check CHECK (status IN (
        'PENDING',
        'PASSED',
        'FAILED',
        'REVIEW',
        'ERROR',
        'CANCELLED'
    )),
    CONSTRAINT driver_verification_checks_type_check CHECK (check_type IN (
        'PHONE_OTP',
        'GOV_ID_OCR',
        'GOV_ID_AUTHENTICITY',
        'SELFIE_FACE_MATCH',
        'LIVENESS',
        'DUPLICATE_ID',
        'DUPLICATE_FACE',
        'LICENSE_OCR',
        'LICENSE_CATEGORY',
        'VEHICLE_PLATE_OCR',
        'VEHICLE_REGISTRATION',
        'INSURANCE_OCR',
        'PAYOUT_NAME_MATCH',
        'BACKGROUND_CHECK',
        'DEVICE_RISK',
        'MANUAL_REVIEW'
    ))
);

CREATE INDEX IF NOT EXISTS idx_driver_verification_checks_account
ON api.driver_verification_checks(driver_account_id, created_at DESC);

CREATE TABLE IF NOT EXISTS api.driver_vehicles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_account_id integer NOT NULL REFERENCES api.driver_accounts(id) ON DELETE CASCADE,
    vehicle_type text NOT NULL,
    plate text NOT NULL,
    make text,
    model text,
    color text,
    registration_number text,
    insurance_number text,
    insurance_expires_at date,
    status text NOT NULL DEFAULT 'SUBMITTED',
    review_notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT driver_vehicles_type_check CHECK (vehicle_type IN ('MOTORCYCLE','CAR','BICYCLE','CARGO_BIKE','OTHER')),
    CONSTRAINT driver_vehicles_status_check CHECK (status IN (
        'SUBMITTED',
        'PLATE_OCR_MATCHED',
        'REGISTRATION_MATCHED',
        'INSURANCE_VALID',
        'PHOTO_REVIEW_REQUIRED',
        'VERIFIED',
        'REJECTED',
        'EXPIRED',
        'SUSPENDED'
    ))
);

CREATE INDEX IF NOT EXISTS idx_driver_vehicles_account_status
ON api.driver_vehicles(driver_account_id, status);

CREATE INDEX IF NOT EXISTS idx_driver_vehicles_plate
ON api.driver_vehicles(plate);

CREATE TABLE IF NOT EXISTS api.driver_manual_reviews (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_account_id integer NOT NULL REFERENCES api.driver_accounts(id) ON DELETE CASCADE,
    reviewer text NOT NULL,
    decision text NOT NULL,
    reason text,
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT driver_manual_reviews_decision_check CHECK (decision IN (
        'APPROVE',
        'REJECT',
        'SUSPEND',
        'REQUEST_MORE_INFO',
        'MARK_REVIEWED'
    ))
);

CREATE TABLE IF NOT EXISTS api.driver_online_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_account_id integer NOT NULL REFERENCES api.driver_accounts(id) ON DELETE CASCADE,
    status text NOT NULL DEFAULT 'ONLINE',
    device_id text,
    app_version text,
    started_at timestamptz NOT NULL DEFAULT now(),
    ended_at timestamptz,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT driver_online_sessions_status_check CHECK (status IN (
        'ONLINE',
        'OFFLINE',
        'PAUSED',
        'FORCED_OFFLINE'
    ))
);

CREATE INDEX IF NOT EXISTS idx_driver_online_sessions_status
ON api.driver_online_sessions(status, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS api.driver_locations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_account_id integer NOT NULL REFERENCES api.driver_accounts(id) ON DELETE CASCADE,
    session_id integer REFERENCES api.driver_online_sessions(id) ON DELETE SET NULL,
    latitude numeric(12,8) NOT NULL,
    longitude numeric(12,8) NOT NULL,
    accuracy_m numeric(10,2),
    speed_mps numeric(10,2),
    heading numeric(7,2),
    captured_at timestamptz NOT NULL,
    received_at timestamptz NOT NULL DEFAULT now(),
    risk_flags jsonb NOT NULL DEFAULT '[]'::jsonb,
    CONSTRAINT driver_locations_lat_check CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT driver_locations_lon_check CHECK (longitude BETWEEN -180 AND 180)
);

CREATE INDEX IF NOT EXISTS idx_driver_locations_account_recent
ON api.driver_locations(driver_account_id, captured_at DESC);

CREATE INDEX IF NOT EXISTS idx_driver_locations_received
ON api.driver_locations(received_at DESC);

CREATE TABLE IF NOT EXISTS api.driver_risk_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_account_id integer NOT NULL REFERENCES api.driver_accounts(id) ON DELETE CASCADE,
    event_type text NOT NULL,
    severity text NOT NULL DEFAULT 'INFO',
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT driver_risk_events_severity_check CHECK (severity IN ('INFO','LOW','MEDIUM','HIGH','BLOCKING'))
);

CREATE INDEX IF NOT EXISTS idx_driver_risk_events_account
ON api.driver_risk_events(driver_account_id, created_at DESC);

CREATE TABLE IF NOT EXISTS api.pickup_points (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo text NOT NULL UNIQUE,
    nombre text NOT NULL,
    direccion text NOT NULL,
    referencia text,
    telefono text,
    latitude numeric(12,8) NOT NULL,
    longitude numeric(12,8) NOT NULL,
    activo boolean NOT NULL DEFAULT true,
    service_radius_km numeric(8,3) NOT NULL DEFAULT 8.05,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pickup_points_lat_check CHECK (latitude BETWEEN -90 AND 90),
    CONSTRAINT pickup_points_lon_check CHECK (longitude BETWEEN -180 AND 180)
);

CREATE TABLE IF NOT EXISTS api.order_pickup_points (
    pedido_id integer PRIMARY KEY REFERENCES api.pedidos(id) ON DELETE CASCADE,
    pickup_point_id integer NOT NULL REFERENCES api.pickup_points(id) ON DELETE RESTRICT,
    assigned_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS api.delivery_offer_batches (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id integer NOT NULL REFERENCES api.pedidos(id) ON DELETE CASCADE,
    pickup_point_id integer REFERENCES api.pickup_points(id) ON DELETE SET NULL,
    status text NOT NULL DEFAULT 'OPEN',
    radius_km numeric(8,3) NOT NULL DEFAULT 8.05,
    max_candidates integer NOT NULL DEFAULT 3,
    assigned_assignment_id integer REFERENCES api.delivery_asignaciones(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL DEFAULT now() + interval '60 seconds',
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT delivery_offer_batches_status_check CHECK (status IN ('OPEN','ASSIGNED','EXPIRED','CANCELLED'))
);

CREATE INDEX IF NOT EXISTS idx_delivery_offer_batches_pedido
ON api.delivery_offer_batches(pedido_id, created_at DESC);

CREATE TABLE IF NOT EXISTS api.delivery_offer_candidates (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id integer NOT NULL REFERENCES api.delivery_offer_batches(id) ON DELETE CASCADE,
    pedido_id integer NOT NULL REFERENCES api.pedidos(id) ON DELETE CASCADE,
    driver_account_id integer NOT NULL REFERENCES api.driver_accounts(id) ON DELETE CASCADE,
    repartidor_id integer REFERENCES api.repartidores(id) ON DELETE SET NULL,
    distance_km numeric(8,3),
    eta_seconds integer,
    score numeric(10,4),
    status text NOT NULL DEFAULT 'OFFERED',
    offered_at timestamptz NOT NULL DEFAULT now(),
    viewed_at timestamptz,
    responded_at timestamptz,
    expires_at timestamptz NOT NULL DEFAULT now() + interval '60 seconds',
    CONSTRAINT delivery_offer_candidates_status_check CHECK (status IN (
        'OFFERED',
        'VIEWED',
        'ACCEPTED',
        'DECLINED',
        'EXPIRED',
        'LOST',
        'CANCELLED'
    )),
    CONSTRAINT delivery_offer_candidates_unique UNIQUE (batch_id, driver_account_id)
);

CREATE INDEX IF NOT EXISTS idx_delivery_offer_candidates_driver
ON api.delivery_offer_candidates(driver_account_id, status, offered_at DESC);

CREATE INDEX IF NOT EXISTS idx_delivery_offer_candidates_batch_status
ON api.delivery_offer_candidates(batch_id, status);

CREATE OR REPLACE FUNCTION api.driver_distance_km(
    lat1 numeric,
    lon1 numeric,
    lat2 numeric,
    lon2 numeric
)
RETURNS numeric
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT 6371 * 2 * asin(sqrt(
        power(sin(radians(($3 - $1) / 2)), 2) +
        cos(radians($1)) * cos(radians($3)) *
        power(sin(radians(($4 - $2) / 2)), 2)
    ));
$$;

CREATE OR REPLACE VIEW api.v_driver_latest_locations AS
SELECT DISTINCT ON (l.driver_account_id)
    l.driver_account_id,
    l.session_id,
    l.latitude,
    l.longitude,
    l.accuracy_m,
    l.speed_mps,
    l.heading,
    l.captured_at,
    l.received_at,
    l.risk_flags
FROM api.driver_locations l
ORDER BY l.driver_account_id, l.captured_at DESC, l.id DESC;

CREATE OR REPLACE VIEW api.v_driver_accounts AS
SELECT
    a.id,
    a.repartidor_id,
    r.codigo AS repartidor_codigo,
    r.nombre AS repartidor_nombre,
    r.activo AS repartidor_activo,
    a.phone,
    a.email,
    a.legal_name,
    a.date_of_birth,
    a.status,
    a.trust_tier,
    a.risk_score,
    a.rejection_reason,
    a.suspension_reason,
    a.approved_at,
    a.rejected_at,
    a.suspended_at,
    a.created_at,
    a.updated_at,
    (
        SELECT COUNT(*)
        FROM api.driver_documents d
        WHERE d.driver_account_id = a.id
    )::integer AS document_count,
    (
        SELECT COUNT(*)
        FROM api.driver_verification_checks c
        WHERE c.driver_account_id = a.id
          AND c.status IN ('FAILED','REVIEW','ERROR')
    )::integer AS open_check_count,
    loc.latitude AS latest_latitude,
    loc.longitude AS latest_longitude,
    loc.captured_at AS latest_location_at
FROM api.driver_accounts a
LEFT JOIN api.repartidores r ON r.id = a.repartidor_id
LEFT JOIN api.v_driver_latest_locations loc ON loc.driver_account_id = a.id;

CREATE OR REPLACE FUNCTION api.driver_approve_to_repartidor(
    p_driver_account_id integer,
    p_reviewer text DEFAULT 'replau-admin',
    p_codigo text DEFAULT NULL,
    p_notes text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = api, public
AS $$
DECLARE
    v_account record;
    v_repartidor_id integer;
    v_codigo text;
BEGIN
    SELECT * INTO v_account
    FROM api.driver_accounts
    WHERE id = p_driver_account_id
    FOR UPDATE;

    IF v_account.id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'error', 'Driver account not found');
    END IF;

    IF v_account.repartidor_id IS NOT NULL THEN
        v_repartidor_id := v_account.repartidor_id;
    ELSE
        v_codigo := COALESCE(NULLIF(upper(trim(p_codigo)), ''), 'DRV' || lpad(v_account.id::text, 4, '0'));

        INSERT INTO api.repartidores(codigo, nombre, whatsapp_number, activo, orden_turno)
        VALUES (
            v_codigo,
            COALESCE(NULLIF(trim(v_account.legal_name), ''), 'Driver ' || v_account.id::text),
            v_account.phone,
            false,
            COALESCE((SELECT max(orden_turno) + 1 FROM api.repartidores), 1)
        )
        ON CONFLICT (whatsapp_number) DO UPDATE SET
            nombre = EXCLUDED.nombre,
            updated_at = now()
        RETURNING id INTO v_repartidor_id;
    END IF;

    UPDATE api.driver_accounts
    SET repartidor_id = v_repartidor_id,
        status = 'APPROVED',
        trust_tier = 'TIER_3_FULLY_VERIFIED',
        approved_at = COALESCE(approved_at, now()),
        rejection_reason = NULL,
        suspension_reason = NULL,
        updated_at = now()
    WHERE id = p_driver_account_id;

    INSERT INTO api.driver_manual_reviews(driver_account_id, reviewer, decision, notes)
    VALUES (p_driver_account_id, COALESCE(NULLIF(trim(p_reviewer), ''), 'replau-admin'), 'APPROVE', p_notes);

    RETURN jsonb_build_object(
        'ok', true,
        'driver_account_id', p_driver_account_id,
        'repartidor_id', v_repartidor_id,
        'status', 'APPROVED'
    );
END;
$$;

GRANT SELECT, INSERT, UPDATE ON
    api.driver_accounts,
    api.driver_consents,
    api.driver_documents,
    api.driver_verification_checks,
    api.driver_vehicles,
    api.driver_manual_reviews,
    api.driver_online_sessions,
    api.driver_locations,
    api.driver_risk_events,
    api.pickup_points,
    api.order_pickup_points,
    api.delivery_offer_batches,
    api.delivery_offer_candidates
TO web_anon;

GRANT SELECT ON
    api.v_driver_latest_locations,
    api.v_driver_accounts
TO web_anon;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA api
TO web_anon;

GRANT EXECUTE ON FUNCTION api.driver_distance_km(numeric, numeric, numeric, numeric) TO web_anon;
GRANT EXECUTE ON FUNCTION api.driver_approve_to_repartidor(integer, text, text, text) TO web_anon;

NOTIFY pgrst, 'reload schema';

COMMIT;
