
BEGIN;

CREATE SCHEMA IF NOT EXISTS api;

CREATE TABLE IF NOT EXISTS api.stock_reservas (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id integer NOT NULL REFERENCES api.pedidos(id) ON DELETE CASCADE,
    pedido_item_id integer NOT NULL REFERENCES api.pedido_items(id) ON DELETE CASCADE,
    producto_id integer NOT NULL REFERENCES api.productos(id) ON DELETE RESTRICT,
    almacen_id integer REFERENCES api.almacenes(id) ON DELETE RESTRICT,
    cantidad numeric(14,3) NOT NULL,
    unidad text,
    factor numeric(14,3) NOT NULL DEFAULT 1,
    cantidad_base numeric(14,3) NOT NULL,
    estado text NOT NULL DEFAULT 'RESERVADA',
    movimiento_salida_id integer REFERENCES api.movimientos_stock(id) ON DELETE SET NULL,
    observacion text,
    reserved_at timestamptz NOT NULL DEFAULT now(),
    released_at timestamptz,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT stock_reservas_unique_item UNIQUE (pedido_item_id),
    CONSTRAINT stock_reservas_cantidad_check CHECK (cantidad > 0 AND factor > 0 AND cantidad_base > 0),
    CONSTRAINT stock_reservas_estado_check CHECK (estado IN ('RESERVADA', 'LIBERADA', 'CONSUMIDA'))
);

CREATE INDEX IF NOT EXISTS idx_stock_reservas_pedido ON api.stock_reservas(pedido_id);
CREATE INDEX IF NOT EXISTS idx_stock_reservas_producto ON api.stock_reservas(producto_id);
CREATE INDEX IF NOT EXISTS idx_stock_reservas_estado ON api.stock_reservas(estado);
CREATE INDEX IF NOT EXISTS idx_stock_reservas_almacen ON api.stock_reservas(almacen_id);

CREATE OR REPLACE FUNCTION api.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_updated_at_stock_reservas ON api.stock_reservas;
CREATE TRIGGER set_updated_at_stock_reservas
BEFORE UPDATE ON api.stock_reservas
FOR EACH ROW EXECUTE FUNCTION api.set_updated_at();

CREATE OR REPLACE FUNCTION api.get_default_almacen_id()
RETURNS integer LANGUAGE plpgsql STABLE AS $$
DECLARE v_id integer;
BEGIN
    SELECT id INTO v_id FROM api.almacenes WHERE codigo = 'ALM-PRIN' ORDER BY id LIMIT 1;
    IF v_id IS NULL THEN
        SELECT id INTO v_id FROM api.almacenes WHERE active = true ORDER BY id LIMIT 1;
    END IF;
    RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION api.get_producto_factor(p_producto_id integer, p_unidad text)
RETURNS numeric LANGUAGE plpgsql STABLE AS $$
DECLARE v_factor numeric(14,3);
BEGIN
    IF p_producto_id IS NULL THEN RETURN 1; END IF;

    IF p_unidad IS NOT NULL AND trim(p_unidad) <> '' THEN
        SELECT pp.factor INTO v_factor
        FROM api.producto_packs pp
        WHERE pp.producto_id = p_producto_id
          AND pp.active = true
          AND upper(pp.pack_name) = upper(trim(p_unidad))
        ORDER BY pp.is_default DESC, pp.id
        LIMIT 1;
    END IF;

    IF v_factor IS NULL THEN
        SELECT pp.factor INTO v_factor
        FROM api.producto_packs pp
        WHERE pp.producto_id = p_producto_id
          AND pp.active = true
          AND pp.is_default = true
        ORDER BY pp.id
        LIMIT 1;
    END IF;

    RETURN COALESCE(v_factor, 1);
END;
$$;

CREATE OR REPLACE FUNCTION api.reservar_stock_pedido_item(p_pedido_item_id integer)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = api, public AS $$
DECLARE
    v_item record;
    v_factor numeric(14,3);
    v_cantidad_base numeric(14,3);
    v_almacen_id integer;
    v_reserva_id integer;
BEGIN
    SELECT pi.id, pi.pedido_id, pi.producto_id, pi.producto_texto, pi.cantidad, pi.unidad, p.estado AS pedido_estado
    INTO v_item
    FROM api.pedido_items pi
    JOIN api.pedidos p ON p.id = pi.pedido_id
    WHERE pi.id = p_pedido_item_id;

    IF v_item.id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'error', 'pedido_item not found', 'pedido_item_id', p_pedido_item_id);
    END IF;

    IF v_item.producto_id IS NULL THEN
        RETURN jsonb_build_object('ok', false, 'error', 'pedido_item has no producto_id', 'pedido_item_id', p_pedido_item_id);
    END IF;

    IF v_item.pedido_estado NOT IN ('CONFIRMADO', 'EN_PREPARACION', 'DESPACHADO') THEN
        RETURN jsonb_build_object('ok', false, 'skipped', true, 'reason', 'pedido status does not reserve stock', 'estado', v_item.pedido_estado);
    END IF;

    SELECT sr.id INTO v_reserva_id FROM api.stock_reservas sr WHERE sr.pedido_item_id = p_pedido_item_id;

    IF v_reserva_id IS NOT NULL THEN
        RETURN jsonb_build_object('ok', true, 'already_exists', true, 'reserva_id', v_reserva_id);
    END IF;

    v_factor := api.get_producto_factor(v_item.producto_id, v_item.unidad);
    v_cantidad_base := round((v_item.cantidad * v_factor)::numeric, 3);
    v_almacen_id := api.get_default_almacen_id();

    INSERT INTO api.stock_reservas (
        pedido_id, pedido_item_id, producto_id, almacen_id,
        cantidad, unidad, factor, cantidad_base, estado, observacion
    ) VALUES (
        v_item.pedido_id, v_item.id, v_item.producto_id, v_almacen_id,
        v_item.cantidad, v_item.unidad, v_factor, v_cantidad_base, 'RESERVADA',
        'Reserva automática por pedido WhatsApp'
    ) RETURNING id INTO v_reserva_id;

    RETURN jsonb_build_object(
        'ok', true, 'reserva_id', v_reserva_id, 'pedido_id', v_item.pedido_id,
        'pedido_item_id', v_item.id, 'producto_id', v_item.producto_id,
        'cantidad', v_item.cantidad, 'unidad', v_item.unidad,
        'factor', v_factor, 'cantidad_base', v_cantidad_base, 'almacen_id', v_almacen_id
    );
END;
$$;

CREATE OR REPLACE FUNCTION api.reservar_stock_pedido(p_pedido_id integer)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = api, public AS $$
DECLARE
    v_item record;
    v_results jsonb := '[]'::jsonb;
BEGIN
    IF p_pedido_id IS NULL THEN RAISE EXCEPTION 'p_pedido_id is required'; END IF;

    FOR v_item IN SELECT id FROM api.pedido_items WHERE pedido_id = p_pedido_id ORDER BY id LOOP
        v_results := v_results || jsonb_build_array(api.reservar_stock_pedido_item(v_item.id));
    END LOOP;

    RETURN jsonb_build_object('ok', true, 'pedido_id', p_pedido_id, 'results', v_results);
END;
$$;

CREATE OR REPLACE FUNCTION api.liberar_reserva_pedido(p_pedido_id integer, p_reason text DEFAULT 'Reserva liberada')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = api, public AS $$
DECLARE v_count integer;
BEGIN
    UPDATE api.stock_reservas
    SET estado = 'LIBERADA',
        released_at = now(),
        observacion = COALESCE(p_reason, 'Reserva liberada'),
        updated_at = now()
    WHERE pedido_id = p_pedido_id AND estado = 'RESERVADA';

    GET DIAGNOSTICS v_count = ROW_COUNT;
    RETURN jsonb_build_object('ok', true, 'pedido_id', p_pedido_id, 'released_count', v_count);
END;
$$;

CREATE OR REPLACE FUNCTION api.consumir_reserva_pedido(p_pedido_id integer)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = api, public AS $$
DECLARE
    v_res record;
    v_mov_id integer;
    v_count integer := 0;
BEGIN
    FOR v_res IN
        SELECT sr.*, p.pedido_num
        FROM api.stock_reservas sr
        JOIN api.pedidos p ON p.id = sr.pedido_id
        WHERE sr.pedido_id = p_pedido_id AND sr.estado = 'RESERVADA'
        ORDER BY sr.id
    LOOP
        INSERT INTO api.movimientos_stock (
            fecha_movimiento, movimiento_tipo, almacen_origen_id, producto_id, lote_id,
            cantidad, doc_tipo, doc_id, doc_linea_id, referencia, observacion
        ) VALUES (
            now(), 'SALIDA', v_res.almacen_id, v_res.producto_id, NULL,
            v_res.cantidad_base, 'PEDIDO_WHATSAPP', v_res.pedido_id, v_res.pedido_item_id,
            v_res.pedido_num, 'Salida automática por entrega de pedido WhatsApp'
        ) RETURNING id INTO v_mov_id;

        UPDATE api.stock_reservas
        SET estado = 'CONSUMIDA',
            consumed_at = now(),
            movimiento_salida_id = v_mov_id,
            observacion = 'Reserva consumida por pedido entregado',
            updated_at = now()
        WHERE id = v_res.id;

        v_count := v_count + 1;
    END LOOP;

    RETURN jsonb_build_object('ok', true, 'pedido_id', p_pedido_id, 'consumed_count', v_count);
END;
$$;

CREATE OR REPLACE FUNCTION api.trg_pedido_items_reservar_stock()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    PERFORM api.reservar_stock_pedido_item(NEW.id);
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS pedido_items_reservar_stock_after_insert ON api.pedido_items;
CREATE TRIGGER pedido_items_reservar_stock_after_insert
AFTER INSERT ON api.pedido_items
FOR EACH ROW EXECUTE FUNCTION api.trg_pedido_items_reservar_stock();

CREATE OR REPLACE FUNCTION api.trg_pedidos_reservas_estado()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.estado IS DISTINCT FROM OLD.estado THEN
        IF NEW.estado = 'ANULADO' THEN
            PERFORM api.liberar_reserva_pedido(NEW.id, 'Reserva liberada por pedido anulado');
        ELSIF NEW.estado = 'ENTREGADO' THEN
            PERFORM api.consumir_reserva_pedido(NEW.id);
        ELSIF NEW.estado IN ('CONFIRMADO', 'EN_PREPARACION', 'DESPACHADO') THEN
            PERFORM api.reservar_stock_pedido(NEW.id);
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS pedidos_reservas_estado_after_update ON api.pedidos;
CREATE TRIGGER pedidos_reservas_estado_after_update
AFTER UPDATE OF estado ON api.pedidos
FOR EACH ROW EXECUTE FUNCTION api.trg_pedidos_reservas_estado();

CREATE OR REPLACE VIEW api.v_stock_reservas AS
SELECT
    sr.id, sr.pedido_id, p.pedido_num, p.estado AS estado_pedido,
    sr.pedido_item_id, sr.producto_id, pr.cdg_prod, pr.nombre AS producto_nombre,
    sr.almacen_id, a.codigo AS almacen_codigo, a.nombre AS almacen_nombre,
    sr.cantidad, sr.unidad, sr.factor, sr.cantidad_base, sr.estado,
    sr.movimiento_salida_id, sr.reserved_at, sr.released_at, sr.consumed_at,
    sr.observacion, sr.created_at, sr.updated_at
FROM api.stock_reservas sr
JOIN api.pedidos p ON p.id = sr.pedido_id
JOIN api.productos pr ON pr.id = sr.producto_id
LEFT JOIN api.almacenes a ON a.id = sr.almacen_id;

CREATE OR REPLACE VIEW api.v_stock_reservado_productos AS
SELECT
    sr.producto_id, pr.cdg_prod, pr.nombre AS producto_nombre,
    sr.almacen_id, a.codigo AS almacen_codigo, a.nombre AS almacen_nombre,
    SUM(sr.cantidad_base) AS stock_reservado
FROM api.stock_reservas sr
JOIN api.productos pr ON pr.id = sr.producto_id
LEFT JOIN api.almacenes a ON a.id = sr.almacen_id
WHERE sr.estado = 'RESERVADA'
GROUP BY sr.producto_id, pr.cdg_prod, pr.nombre, sr.almacen_id, a.codigo, a.nombre;

CREATE OR REPLACE VIEW api.v_stock_disponible_productos AS
WITH actual AS (
    SELECT producto_id, cdg_prod, producto_nombre, almacen_id, almacen_codigo, almacen_nombre,
           SUM(stock_actual) AS stock_actual
    FROM api.v_stock_actual
    GROUP BY producto_id, cdg_prod, producto_nombre, almacen_id, almacen_codigo, almacen_nombre
),
reservado AS (
    SELECT producto_id, cdg_prod, producto_nombre, almacen_id, almacen_codigo, almacen_nombre,
           SUM(stock_reservado) AS stock_reservado
    FROM api.v_stock_reservado_productos
    GROUP BY producto_id, cdg_prod, producto_nombre, almacen_id, almacen_codigo, almacen_nombre
),
keys AS (
    SELECT producto_id, almacen_id FROM actual
    UNION
    SELECT producto_id, almacen_id FROM reservado
)
SELECT
    k.producto_id,
    COALESCE(a.cdg_prod, r.cdg_prod, p.cdg_prod) AS cdg_prod,
    COALESCE(a.producto_nombre, r.producto_nombre, p.nombre) AS producto_nombre,
    k.almacen_id,
    COALESCE(a.almacen_codigo, r.almacen_codigo, al.codigo) AS almacen_codigo,
    COALESCE(a.almacen_nombre, r.almacen_nombre, al.nombre) AS almacen_nombre,
    COALESCE(a.stock_actual, 0) AS stock_actual,
    COALESCE(r.stock_reservado, 0) AS stock_reservado,
    COALESCE(a.stock_actual, 0) - COALESCE(r.stock_reservado, 0) AS stock_disponible,
    CASE WHEN COALESCE(a.stock_actual, 0) - COALESCE(r.stock_reservado, 0) < 0 THEN true ELSE false END AS sobre_reservado
FROM keys k
JOIN api.productos p ON p.id = k.producto_id
LEFT JOIN api.almacenes al ON al.id = k.almacen_id
LEFT JOIN actual a ON a.producto_id = k.producto_id AND a.almacen_id IS NOT DISTINCT FROM k.almacen_id
LEFT JOIN reservado r ON r.producto_id = k.producto_id AND r.almacen_id IS NOT DISTINCT FROM k.almacen_id;

CREATE OR REPLACE VIEW api.v_pedidos_reserva_resumen AS
SELECT
    p.id AS pedido_id, p.pedido_num, p.estado AS estado_pedido,
    c.nombre AS cliente_nombre, c.whatsapp_number,
    COUNT(sr.id) AS total_reservas,
    COUNT(sr.id) FILTER (WHERE sr.estado = 'RESERVADA') AS reservas_activas,
    COUNT(sr.id) FILTER (WHERE sr.estado = 'LIBERADA') AS reservas_liberadas,
    COUNT(sr.id) FILTER (WHERE sr.estado = 'CONSUMIDA') AS reservas_consumidas,
    COALESCE(SUM(sr.cantidad_base) FILTER (WHERE sr.estado = 'RESERVADA'), 0) AS cantidad_reservada_activa,
    COALESCE(SUM(sr.cantidad_base) FILTER (WHERE sr.estado = 'CONSUMIDA'), 0) AS cantidad_consumida,
    p.total, p.created_at, p.updated_at
FROM api.pedidos p
JOIN api.clientes_whatsapp c ON c.id = p.cliente_id
LEFT JOIN api.stock_reservas sr ON sr.pedido_id = p.id
GROUP BY p.id, p.pedido_num, p.estado, c.nombre, c.whatsapp_number, p.total, p.created_at, p.updated_at;

DO $$
DECLARE v_pedido record;
BEGIN
    FOR v_pedido IN
        SELECT id FROM api.pedidos WHERE estado IN ('CONFIRMADO', 'EN_PREPARACION', 'DESPACHADO') ORDER BY id
    LOOP
        PERFORM api.reservar_stock_pedido(v_pedido.id);
    END LOOP;
END $$;

GRANT SELECT, INSERT, UPDATE, DELETE ON api.stock_reservas TO web_anon;
GRANT SELECT ON api.v_stock_reservas, api.v_stock_reservado_productos, api.v_stock_disponible_productos, api.v_pedidos_reserva_resumen TO web_anon;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA api TO web_anon;
GRANT EXECUTE ON FUNCTION api.get_default_almacen_id() TO web_anon;
GRANT EXECUTE ON FUNCTION api.get_producto_factor(integer, text) TO web_anon;
GRANT EXECUTE ON FUNCTION api.reservar_stock_pedido_item(integer) TO web_anon;
GRANT EXECUTE ON FUNCTION api.reservar_stock_pedido(integer) TO web_anon;
GRANT EXECUTE ON FUNCTION api.liberar_reserva_pedido(integer, text) TO web_anon;
GRANT EXECUTE ON FUNCTION api.consumir_reserva_pedido(integer) TO web_anon;

NOTIFY pgrst, 'reload schema';

COMMIT;
